### ISSUE TITLE
Enable scanning tag while phone is locked

### ISSUE THREAD

**Issue by engrbm87** [home-assistant/android#1016]
**Describe the solution you'd like**
Add the option to scan tags while screen is locked. Currently I need to unlock my phone before the tag is scanned.

**Comment by andriej** [comment]
I guess it's androids 'feature' not to have active NFC for apps with locked phone?

**Comment by engrbm87** [comment]
I have another application used for access control that works with NFC while the device is locked. I am not an expert coder but I though that this might be something that can be enabled in the app itself.

**Comment by dshokouhi** [comment]
@engrbm87 what device lets you do that and on what version of android are you on? AFAIK google removed this ability in later versions of android due to security concerns around Android Pay.

Check out this XDA article that talks about why its not possible and how to get around it on a rooted device: https://www.xda-developers.com/nfcscreenoff-scan-nfc-tags-phone-locked/

**Comment by softint2** [comment]
What happened to this? Looking for exactly the same.
Paying with Google Pay kinda every day and almost never have to unlock my phone.

**Comment by pepsonEL** [comment]
Any news about this problem ?

**Comment by Jon8RFC** [comment]
> Any news about this problem ?

You could try this:
https://github.com/Jon8RFC/NfcScreenOff/releases/tag/v2.0.1
