### ISSUE TITLE
Home Assistant causes constant Proximity Sensor activation on Pixel 5

### ISSUE THREAD

**Issue by pwae** [home-assistant/android#1064]
**Home Assistant Android version:**
2.5.0-full

**Android version:**
Android 11 (5 October Security Patch)

**Phone model:**
Pixel 5

**Home Assistant version:**
0.115.6

**Last working Home Assistant release (if known):**
0.115.6

**Description of problem:**

From reddit thread/comments https://www.reddit.com/r/GooglePixel/comments/jbq1uj/what_is_this_annoying_flashing_white_dot_in_the/g8wpue7/
https://www.reddit.com/r/GooglePixel/comments/jbq1uj/what_is_this_annoying_flashing_white_dot_in_the/g8zhbvz/

It was found by a number of people that on their new Pixel 5 phones, that the Proximity Sensor would continually flash all the time, while the phone was in use. (There is a number of videos/photos in the thread of this issue)

After some tracking down by users in the thread, it was found that it appears to have been tied to the Home Assistant app interacting with this sensor.
Force Quitting the Home Assistant app, would stop the issue occurring. as soon as Home Assistant was started up again, the issue would resume.
Going into the App Configuration inside Home Assistant and disabling this sensor was able to stop the root cause of the issue.

However this leaves this sensor permanently disabled from home assistant. The questions remain now are:

a) Should this sensor be disabled by default?
b) Should how Home Assistant grabs/users the sensor data be refined to not cause the above issue

**Screenshot of problem:**
https://streamable.com/5bvp4a

**Comment by dshokouhi** [comment]
This sensor has been disabled by default since 2.5.0, if you had it enabled in a previous release from when it was introduced you just need to disable it.  Some proximity sensors have a light on it to show when it is in use and we can't get around that.  It is up to the user to decide if they want to use it or not.

**Comment by pwae** [comment]
hi @dshokouhi - thanks for the prompt response. i just found #856  as well.
Assume there is no way to limit the use of Home Assistant with that sensor either?

**Comment by dshokouhi** [comment]
You have the option to use it and be ok with the light or not use it, it has to do with how the proximity sensor was built.  We ask for a report from the sensor and we wait to get a report back.  Otherwise we never get a value at all.  Sensor is a bit trivial but not all devices do the light thing, its a hardware decision from the manufacturer to select one with a light.  Samsung devices also have a light to indicate when it is in use.

**Comment by pwae** [comment]
Thanks again @dshokouhi - Understood, and makes sense.

**Comment by pkern** [comment]
It's not actually a "light thing" that is optional. It turns out that the proximity sensor triggers the OLED pixel to light up. So if it's built below the display and the display technology is OLED, you don't really have other options. I do wonder, though, if there is a single use beyond "export all sensors".

Per #856 I also still suspect a bug in the code that keeps this open too long (see https://github.com/home-assistant/android/issues/856#issuecomment-685141878). I didn't open a bug as I didn't get a reply and work interrupt based. ;)
