### ISSUE TITLE
Deployment fails for Nightly Playstore Beta

### ISSUE THREAD

**Issue by p4sI** [home-assistant/android#1082]
Hi,

I just enrolled for the PlayStore Beta and saw, that the latest deployed image is this one: https://github.com/home-assistant/android/releases/tag/beta-406-ae25e7f
It was released from this Action: https://github.com/home-assistant/android/actions/runs/281674320

I checked the GitHub Actions and the other "Nightly Playstore Beta"-Workflows are failing in their step "Play publish" at the "Deploy to Playstore Beta" task.
see: https://github.com/home-assistant/android/runs/1197047732?check_suite_focus=true#step:11:148

> 
> > Task :app:publishFullReleaseBundle
> Starting App Bundle upload: /home/runner/work/android/android/app/build/outputs/bundle/fullRelease/app-full-release.aab
> App Bundle upload complete
> Updating [completed*** release (io.homeassistant.companion.android:[409***) in track 'beta'
> 
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':commitEditForIoDotHomeassistantDotCompanionDotAndroid'.
> > A failure occurred while executing com.github.triplet.gradle.play.tasks.CommitEdit$Committer
>    > 403 Forbidden
>      ***
>        "code" : 403,
>        "errors" : [ ***
>          "domain" : "global",
>          "message" : "Release artifacts require permissions that are missing from permission declaration.",
>          "reason" : "forbidden"
>        *** ***
>        "message" : "Release artifacts require permissions that are missing from permission declaration.",
>        "status" : "PERMISSION_DENIED"
>      ***

It is also failing in the last Workflow from today: https://github.com/home-assistant/android/runs/1278957187?check_suite_focus=true#step:11:120

I'm not sure if this is an issue or if it is a desired behaviour.

Best
Pascal

**Comment by JBassett** [comment]
We are aware of the issue.  It took us a while to figure out what the problem was.  We are working on becoming compliant with new polices from Google.  Feel free to download the latest APK from Github, it should update what you have from Google Play until we get the application approved again.
![image](https://user-images.githubusercontent.com/1051414/96590906-964d6580-12b4-11eb-9108-4a70b25af5cf.png)

We also have a change for not trying to deploy to Google Play when no commits in last 24 hours to fix the duplicate version code issue. (https://github.com/home-assistant/android/pull/1073)

**Comment by p4sI** [comment]
Thanks for the information. I will download it then directly.
