### ISSUE TITLE
App update event

### ISSUE THREAD

**Issue by stipe76** [home-assistant/android#1155]
I was wondering if the an event is sent after an app update? I have some persistent notifications that are removed when the app is update.

I'd like to be able to listen for an app update event and trigger an automation to resend the notifications. Thanks!

**Comment by dshokouhi** [comment]
Now that we have the Last Update Trigger sensor in version 3.0 you should be able to tell when this happens with `android.intent.action.PACKAGE_REPLACED` state for taht sensor

**Comment by stipe76** [comment]
Thank you very much for the prompt response mate!

**Comment by dshokouhi** [comment]
@stipe76 just a FYI to the linked PR, you'll need to adjust your automation slightly to `android.intent.action.MY_PACKAGE_REPLACED`

**Comment by stipe76** [comment]
> @stipe76 just a FYI to the linked PR, you'll need to adjust your automation slightly to `android.intent.action.MY_PACKAGE_REPLACED`

Will do. Thanks!

**Comment by stipe76** [comment]
Hi again. 

After updating the app, my automation didn't fire. I checked the logbook, and android.intent.action.MY_PACKAGE_REPLACED doesn't seem to appear. The update happened between the 2 events in the screenshot.

Cheers
![Screenshot_20201108-205209](https://user-images.githubusercontent.com/32793572/98462008-ffb1fb80-2204-11eb-93e8-e737d18d4201.jpg)

**Comment by dshokouhi** [comment]
It looks like the intent registers however because the Sensor Worker needs to restart since it was stopped it ends up taking over the actual intent.  The purpose of this intent is to ensure the sensor worker starts after an update, I was hopeful it would also give you what you need :)

 I think a more suitable approach would be to have a new sensor that reports the current installed app version as its state, this way when the app updates and restarts it will report a new value for you to use.

**Comment by stipe76** [comment]
That would ne great. 

Thanks!
