### ISSUE TITLE
Unlocking phone shows toast message "Unable to fetch data for configured entity"

### ISSUE THREAD

**Issue by swbradshaw** [home-assistant/android#1164]
**Home Assistant Android version:** 3.0.1-full

**Android version:** 10

**Phone model:** OnePlus 5

**Home Assistant version:** 0.117.2

**Last working Home Assistant release (if known):**

**Description of problem:**
Every time I unlock my phone, a toast message is shown. I don't have any widgets. I'm not sure why it would say this. It didn't say this before the app update.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![Screenshot_20201107-171140](https://user-images.githubusercontent.com/2023547/98457146-008a5500-2153-11eb-8246-358d77ccb3ef.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
This is caused by a recent breaking change where your widgets were lost from the homescreen.  Please visit the Manage Widgets screen in App configuration, and delete any widget that does not exist.

**Comment by swbradshaw** [comment]
I saw the breaking change about widgets, but I haven't had any widgets on my home screens for some time. I'll visit the Widget section and delete any old data that is there.

**Comment by dshokouhi** [comment]
The old widget data is still there since we had an older breaking change about widgets.  We store all widgets as they get created but if the home screen loses them we don't get notified, we only get notified if a user removes them.  The editable widgets allow us to see what was left over in the database so we can delete them in these unique cases.  The reason why you see it now is because we are using that data to make widgets update faster so we just need to clean it up.

**Comment by swbradshaw** [comment]
Thanks for the explanation.
