### ISSUE TITLE
Power menu buttons don't update if light is on at 100% brightness

### ISSUE THREAD

**Issue by ingenium13** [home-assistant/android#1179]
**Home Assistant Android version:** 3.0.3 and beta-509-4255ee1-full

**Android version:** 11

**Phone model:** Pixel 4 XL

**Home Assistant version:** 0.117.5

**Last working Home Assistant release (if known):** None

**Description of problem:** For some lights, the power menu button will not update if the light is at 100% brightness, but they work fine from the HA app itself. Dimming the light from the HA app restores functionality of the power menu button. This video shows the behavior when the lights are at 100% brightness https://drive.google.com/file/d/1kDfQg5bnX2Jk2Lp4YCiOPzADhw0ZyRuW/view?usp=sharing

The affected lights are all Leviton DZ6HD-1BZ Decora 600W Smart Dimmers connected with zwave2mqtt. State info from an affected light:

**Bathroom:**
State: off
Attributes:
friendly_name: Bathroom
supported_features: 41

State: on
Attributes:
brightness: 258
friendly_name: Bathroom
supported_features: 41

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Interesting the `brightness` on that device is `258` but the accepted maximum is `255` per HA docs. Is that a value you can control in zwave2mqtt?  Because that current value is invalid per the HA docs which expects the maximum to be 255.

https://www.home-assistant.io/integrations/light/#service-lightturn_on

**Comment by dshokouhi** [comment]
Are you getting any HA log errors when this happens too?

**Comment by ingenium13** [comment]
No, there's no HA errors at all. zwave2mqtt allows me to set the max brightness by percent, but that's it:
![Screenshot 2020-11-09 at 6 16 11 PM](https://user-images.githubusercontent.com/3280458/98607760-d2725580-22b7-11eb-9d8c-cbdd605e24b6.png)

The lights were all auto-configured from zwave2mqtt. Here is the hass device json from zwave2mqtt
```
{
  "type": "light",
  "object_id": "dimmer",
  "discovery_payload": {
    "schema": "template",
    "brightness_template": "{{ (value_json.value / 99 * 255) | round(0) }}",
    "state_topic": "homeassistant/bedroom/38/1/0",
    "state_template": "{{ \"off\" if value_json.value == 0 else \"on\" }}",
    "command_topic": "homeassistant/bedroom/38/1/0/set",
    "command_on_template": "{{ ((brightness / 255 * 99) | round(0)) if brightness is defined else 255 }}",
    "command_off_template": "0",
    "device": {
      "identifiers": [
        "zwave2mqtt_0xead14a91_node3"
      ],
      "manufacturer": "Leviton",
      "model": "DZ6HD-1BZ Decora 600W Smart Dimmer (0x0001)",
      "name": "bedroom",
      "sw_version": "1.13"
    },
    "name": "bedroom_dimmer",
    "unique_id": "zwave2mqtt_0xead14a91_3-38-1-0"
  },
  "discoveryTopic": "light/bedroom/dimmer/config",
  "values": [
    "38-1-0"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "light_dimmer"
}
```

**Comment by dshokouhi** [comment]
if you change `255 * 99` to `255 * 100` does it fix the issue? looks to be a conversion issue from zwave2mqtt when its trying to convert 0 to 100% because sending 100% causes it to report 258 which is incorrect.

**Comment by ingenium13** [comment]
Change it at which location? Both?

**Comment by dshokouhi** [comment]
I would do both, one controls the command to turn the light on and off and the other controls the actual attribute value

**Comment by ingenium13** [comment]
Yes, changing them to 100 instead of 99 fixes it. Should I file a bug report for zwave2mqtt? I wonder why they picked 99.... it seems like a deliberate choice for some reason

**Comment by dshokouhi** [comment]
Yea this would be a zwave2mqtt issue.  Per HA docs brightness must be 0 to 255 and we depend on that to do the percentage you see in the power menu screen.  Not all devices give brightness percent so we have to go by whats in `brightness` as all lights have that attribute.

It is odd that they picked 99 but I believe at some point in time the original zwave integration did something similar and it was since corrected so it could be some left over clean up?

**Comment by ingenium13** [comment]
I reported the bug to zwave2mqtt, but they seem reluctant to fix it because it might break other templates that depend on the broken behavior. The broken formula template seems to be used for all zwave dimmers, not just Leviton. 

Is there a reason to not add a sanity check to the power controls, and if brightness is > 255, just change it to 255?

**Comment by dshokouhi** [comment]
The app needs to go by HA dev docs and they specifically call out 0-255 range for `brightness` it's even in the HA core code

https://developers.home-assistant.io/docs/core/entity/light#properties

 https://github.com/home-assistant/core/blob/master/homeassistant/components/light/__init__.py#L86

It looks like they offered a solution for this as well that you can use.

Fixing the issue here is only a band-aid to the problem, it should really be fixed at the integration level.
