### ISSUE TITLE
Steps Sensor doesn't update if the app is in background

### ISSUE THREAD

**Issue by ippo112** [home-assistant/android#1191]
Home Assistant Android version: 3.0.1
Android version:  Android 10
Phone model: Samsung Note 10
Home Assistant version:  0.116.4

Description of problem:
The Steps sensor works only if the App is in Foreground.
If I close the App there are no update for Step Sensor, all others sensors works fine also if the App works in background.
To Update again the Steps Sensor I have to force to stop the App and start it gain.

Someone have the same problem?
Any help to resolve?

thanls
luca

**Comment by dshokouhi** [comment]
This sensor will only report as it gets an update, if it doesn't have an update when we ask for one then we don't get it.  Some devices give an update right away and others do not.  Every device is different.  You will need to wait for the device to have an update.  You more than likely need to be patient and wait a few hours for it to check in.  Double check that the app is actually able to run in the background and battery optimizations are turned off.

Here is my graph and you can see the results come in as whenever they do: 
![image](https://user-images.githubusercontent.com/1634145/99091560-ea322e00-2584-11eb-83b0-223001f9f63b.png)

**Comment by ippo112** [comment]
it's different.
If I force to stop and then I restart the App, the "counter" will update and so update also HA on server.
the counter of the mobile device works fine, it seems that the App isn't be able to cacth the data from device untill it is restarted...

**Comment by dshokouhi** [comment]
Double check that the app has proper background permissions.  It doesnt seem like it does.

**Comment by ippo112** [comment]
yes it have, 
all others sensor works in background, only the  steps_sensor doesn't.

**Comment by dshokouhi** [comment]
How long do you wait in between updates?   Did you disable the sensor worker channel or change its priority?

**Comment by ippo112** [comment]
the sensor is embedded in the Smartphone.
every time that i force stop and restart the App,  the "counter" of the App wil update, both if I do evry 5 minutes or after 2/3 Hour

**Comment by dshokouhi** [comment]
I asked how long do you wait in between updates, not how often you force stop.  It can be hours or longer for your device to check in with an update from this sensor naturally.  If you don't force stop the app do you eventually get an update?  You can't expect this sensor to update in any discernable interval, just look at my graph where I don't force stop the app and notice how it goes hours before an update.  Also you forgot to answer my question about the Sensor Worker notification channel.

**Comment by ippo112** [comment]
about the Sensor Worker notification channel: 
I don't know. Where can I check?


I wait for 3/4 Hour and nothing happen.

also:
1.when the App is open the update is every 2/3 minutes
2. for the other sensors (light, proximity, battery life, etc) the update is also from 4 to 10  minutes both if the App is open or closed.

**Comment by ippo112** [comment]
@dshokouhi I see your grafh, and I think that also you have my problem ...
it semms that you make more than 2.000 steps in 2 minut (around 1 p.m.), 
around 6 p.m. the sensor works fine

**Comment by dshokouhi** [comment]
@ippo112 this is not an issue, this is expected behavior as I was trying to explain to you and hence why I shared my graph to help point that out.  I think you just need to have patience or set your expectations for this sensors data properly.  If you really require consistent data you should consider using Google Fit and the custom integration mentioned in the forums.

**Comment by ippo112** [comment]
ok, thanks for your help.
I was sure that the behavior  of the steps sensor is similar to "battery level" ...

![image](https://user-images.githubusercontent.com/57571607/99101605-1d081080-25dd-11eb-991f-6699e49adc09.png)

**Comment by dshokouhi** [comment]
So the steps sensor is actually a motion sensor and unlike 90% of the other sensors which are just based off an API.  Steps, light, proximity and pressure are all actual on device sensors that report their data to a `onChanged` event instead of us just querying the API for results and sending it.  Steps in particular accumulates data in the background and if it has data to send when we ask for it, we send it.  If the data it sends to us to matches the existing state we don't do anything.  These 4 sensors are completely different from the rest.  Light and Pressure typically have an event every time we ask for it which is why those feel more up to date.  Proximity and Steps don't so we have to wait and hence the results are not as consistent.
