### ISSUE TITLE
The Dialog - Your location is disabled keeps reappearing

### ISSUE THREAD

**Issue by aleksandrov1995** [home-assistant/android#1213]
**Home Assistant Android version:**
Beta - 527
**Android version:**
Android 10
**Phone model:**
Galaxy Note 20 Ultra
**Home Assistant version:**
0.118.2
**Last working Home Assistant release (if known):**

**Description of problem:**
The Dialog stating that the location is disabled, keeps reappearing, even if I click No as an answer if I want to switch it on. Is this the expected behaviour, for example, I don't keep my location on, when I am home, but I use it frequently when I am out. Does it interfere if the location is disabled, but the location sensors are on?
**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
So this is new expected behavior.  I am going to assume that in the app you are using the internal connection URL and/or Wifi sensors along with the device tracker.  For any of these to work at all, location needs to be left on.  We do not  get any Wifi info without it.  This pop-up shows up when you have one of the above stated as the pop-up itself also mentions.  We had a lot of users wondering why certain things were not working so now we need to inform and it seems you are hitting one of those issues yourself :)

In order to prevent the pop-up you will need to stop using those features or deal with it when at home, most likely though you will want to leave it on as you probably did not know the features stop working like that.

**Comment by aleksandrov1995** [comment]
Seems fairly reasonable, although I know that those sensors rely on location to be working, so when I at home they will not update. Thanks for the info, I will have to reapproach how location tracking is currently configured for me.

**Comment by dshokouhi** [comment]
Its not jsut the sensors but the internal connection URL switching too.  The android system does not return an SSID and therefore all features dependent on that cease to work or return junk data.  It was confusing a lot of users.

**Comment by aleksandrov1995** [comment]
I fully understand that, I will see how I can approach the location tracking. I am user since the first beta of the app and have been using the betas since then, also reading through every changelog, thanks for taking the time to explain.
