### ISSUE TITLE
White background in dark mode 

### ISSUE THREAD

**Issue by xuefer** [home-assistant/android#1214]
**Home Assistant Android version:**
3.0.2-full

**Android version:**
7.1.2
LineageOS 14.1 20170927 NIGHTLY

**Phone model:**
kenzo

**Home Assistant version:**
0.118.3

**Last working Home Assistant release (if known):**
None on this device

**Description of problem:**
Everything (except APP configuration) is same in light/dark mode, always white background

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**
Works on other device on other android version

**Comment by dshokouhi** [comment]
Can you check your HA user profile too?  That is different from device to device.

**Comment by dshokouhi** [comment]
Also check that android system webview is up to date and selected as the webview app as well.

**Comment by xuefer** [comment]
App Configuration set to Dark (no follow device, since not supported by device)

in use Profile:
Auto always equal to Light
Dark works as expected

**Comment by dshokouhi** [comment]
This seems to be a custom rom issue so I am closing this issue as you should not be seeing "follow system settings" it is hidden on stock roms that do not support it.  Please make sure android system webview is up to date and it is selected as the default webview app since this is needed on lineage OS.  If this doesnt work then you will need to stick to dark theme in your user profile since the custom ROM is not behaving correctly.

**Comment by xuefer** [comment]
at least sidebar scrolling works after switching webview to "chrome stable" (was Android System WebView) in android developer setting
as I stated "follow system settings" is not an option in this device, "auto" shouldn't be available either.  I fail to see the reason why similar theme setting is provided by both "App Configuration" and "User profile"
