### ISSUE TITLE
Device temperature sensor

### ISSUE THREAD

**Issue by LittleFox94** [home-assistant/android#1235]
**Is your feature request related to a problem? Please describe.**

I'd love to have the temperature around me available in Hass to control my radiators without wiring sensors.

**Describe the solution you'd like**

Android has environment sensors[1], containing the ambient temperature. The app could query it and send it to Hass with all the other enabled sensors.

**Describe alternatives you've considered, if any**

Only known alternative is external sensors connected to Hass.

**Additional context**

Seems like a kinda easy thing to do and I will try to code it myself (or look at it) in a few minutes, but would also make this issue in case I don't succeed and to read opinions/ideas.

I'm aware the sensor isn't perfect, but might be ok enough for simple heating control - at least for a proof of concept.

[1] https://developer.android.com/guide/topics/sensors/sensors_environment#:~:text=You%20can%20use%20these%20sensors,built%20them%20into%20a%20device.

**Comment by dshokouhi** [comment]
Not all devices have an actual ambient temperature sensor (like the pixel 4 xl), also the actual device temperature sensor has been deprecated since Android 4.0 so we may not want to use that one too.  But that is the internal sensor on the device and not an ambient one its more for device internals.

If you want to take this on take a look at the existing device sensors like the light sensor and you can base things off that one, that should help show you how to add these sensors :)

**Comment by LittleFox94** [comment]
Copied PressureSensorManager for ambient temperature - it's probably working, but my Pixel 4 has no ambient temperature sensor - which is a shame x.x

I'll give the code I have in a pull request, but maybe I'll refactor it to not copy PressureSensorManager but have a DeviceSensorManager or something that does all the things using the same API (it's really just some changed strings/enums)

**Comment by dshokouhi** [comment]
So the problem with a device sensor manager is that it wont work well with our `hasSensor` check....its more an issue with the apps architecture since its either we include the manager or don't.  Some devices for example have a light sensor but no pressure sensor.

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/sensors/PressureSensorManager.kt#L50

So we would need to make some changes to allow for a combined manager.

There is also an available sensor check but that does not hide the entire manager block which is what this check is meant for :)

But please do feel free to submit what you have working :) I personally did not opt to submit this sensor for the same reason my device didn't have it and the device temperature sensor just sounded weird lol.  There is nothing wrong with adding more sensors to the app!!!  I always love to see more :)
