### ISSUE TITLE
Add Bulgarian language 

### ISSUE THREAD

**Issue by TUISTERa** [home-assistant/android#1247]
**Is your feature request related to a problem? Please describe.**

Missing Bulgarian language in app
**Describe the solution you'd like**

Add Bulgarian language in lokalise Code is bg-BG. Thank you
**Describe alternatives you've considered, if any**

**Additional context**

**Comment by TUISTERa** [comment]
What is the reason for not adding bulgarian language to the project? Do you have something against my country or language ?

**Comment by HOTnCOOL** [comment]
> What is the reason for not adding bulgarian language to the project? Do you have something against my country or language ?

I am trying to find a way for Bulgarian language. I even started subscription in Nabu Casa because it has Bulgarian listed as supported language.
It seems it has been available till December 2020 when for some reason discontinued. 

I guess that nobody has anything against Bulgaria or our language. We are just unfortunate to be so small and the only EU country using Cyrillic. Would be nice to have back the Bulgarian language where the Cyrillic has been developed before spreading to Russia and the rest of the world...

**Comment by TUISTERa** [comment]
Bulgarian is available in nabucasa and homeassistant,  i personally translated some of the homeassistant part, but to be able to add bulgarian in the android app someone from the maintainers need to create the blank language first.

**Comment by robbiet480** [comment]
Nothing against you or your country, just no one with admin powers had gotten to this request yet!

Please join the Lokalise team [here](https://lokalise.com/public/145814835dd655bc5ab0d0.36753359/) at which point you should be able to start contributing to the translations (I’ve already enabled the language). Let me know if you have any issues.

Thanks for volunteering!
