### ISSUE TITLE
Lost entities in HA when logout/login

### ISSUE THREAD

**Issue by Squale76** [home-assistant/android#1255]
**Home Assistant Android version:** 3.0.2-full

**Android version:** 9

**Phone model:** A8 - 2018

**Home Assistant version:** 2020.12.1

**Last working Home Assistant release (if known):**

**Description of problem:** Lost entities in HA when logout/login in HA companion

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**how to reproduce:**

On HA Companion, in the profile, click on `logout`.
Enter HA's url, then his login / pass (the same as before disconnecting)
Enter the name of the device (the same as before disconnecting) then click on Finish.
In HA we only see one entity.

**Screenshot of problem:**

![image](https://user-images.githubusercontent.com/6738458/103148887-d58cac80-4764-11eb-8e6b-943055f30a7f.png)

To find the 5 entities, you must delete the device in HA and reconnect via HA Companion

**Screenshot of correct operation:**

![image](https://user-images.githubusercontent.com/6738458/103148813-e852b180-4763-11eb-9eae-ed4c8016f7c0.png)

**Additional information:**

**Comment by dshokouhi** [comment]
This is to be expected.  When your config entry does not have a device ID, which happens if you used the app in a much early state before Device ID was a thing.  You actually need to start fresh for the code change to work: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

See: #149 for details
