### ISSUE TITLE
Wake up the device based on a motion event from a external motion sensor

### ISSUE THREAD

**Issue by lerra** [home-assistant/android#1272]
**Is your feature request related to a problem? Please describe.**
I want to wake up a android tablet based on a motion event near by (and not based on the camera on the device) and have it ready to be used (unlocked if possible).

**Describe the solution you'd like**
A entity in home assistant that will wake up and unlock the device so it is ready to be used

**Describe alternatives you've considered, if any**
A entity in home assistant that will wake up the display

**Additional context**
I don't want to use a active camera to detect events and instead use the motion sensors I have deployed and a automation that can wake up the device so its ready to be used instead of needing to press the home / power button to wake it up. Due to privacy I would like to cover the camera and not have such running and there is even better coverage by the sensors then the camera angel.

**Comment by dshokouhi** [comment]
Took a quick look into this.  While it is possible to turn on the screen, we cannot unlock the device without disabling the Device Admin Policy.  Personally that sounds like a bad idea.  I think in cases like this it would be best if the device just didn't have any lock screen, meaning when the screen turns on its on.  This feature is really intended for wall mounted tablets and messing with the device admin policy would not be good especially if the app were to crash and unable to re-enable the device admin policy.  Some pretty serious security implications there.

**Comment by lerra** [comment]
it will not have access to any sensitive data/info and there is also other sensors that I am planning to combine this through a secure presence sensor with that confirms that I am home. 

But you are right, removing the lock screen is also doable and fit more a generic use case :-)

**Comment by MeisterBob** [comment]
Would like have that feature for my wall mounted Android tablet as well. I would suggest a .turn_on and .turn_off service so one can trigger it from any sensor, time controlled or event.

**Comment by dshokouhi** [comment]
So I don't think the app should be doing anything around the device admin policy in the background because if something fails then you will be left without a lock screen and that is not good. Not to mention you probably have to setup the lock screen again too.

For this feature I think we should just turn on the screen.  Turning off the screen involves changing the screen timeout setting and I think this is better kept for a setting on the device itself so you can have it turn on and know it will turn off at your own specified time interval.  As this will be used on wall mounted tablets you should consider removing the lock screen altogether for this feature to work as intended.
