### ISSUE TITLE
Be able to send broadcast intent from other app to home assistant app

### ISSUE THREAD

**Issue by AlexKnowsIt** [home-assistant/android#1278]
**Is your feature request related to a problem? Please describe.**

I would like to integrate my smartwatch into home assistant. Both gadgetbridge as well as home assistant are now able to send now broadcast messages but neither of them is accepting one from another. 

**Describe the solution you'd like**

A way to wait for broadcast intents from other services. This could be made into a sensor where the properties of the broadcast intents are saved in. Like this it would be possible for example to send an broadcast to home assistant when I fall asleep and this could trigger turning of the lights

**Describe alternatives you've considered, if any**

Right now I thought about using tasker and let with their app wait for the signal from gadgetbridge and then create a notification that home assistant can grab but this is not as reliable as it could be

**Additional context**

Thanks already for all the cool features of the app, I find everyday something new to automate with it because of all the cool sensors that are now available!

**Comment by dshokouhi** [comment]
So the android app can't just wait for any broadcast intent sent from any app.  What we can probably do is setup a broadcast intent that we listen to and other apps can send data to, but this means the other app has to update to support it.  We discussed having some type of intent API for other apps to integrate like Sleep as Android.  Sleep as Android has actually since supported webhooks and mqtt so all of those intents can be sent to directly to HA without needing to send data to our app.  This is something you can also ask the developers of gadgetbridge while we try to come up with a way to integrate other apps.  However honestly speaking I think if the app were to support sending data to HA natively then you take out one step in the process.

**Comment by AlexKnowsIt** [comment]
Ah OK. Didn't know that. But gadgetbridge is sending to the nodomain domain, I think that's the reason I can use for example easer or tasker to receive the broadcast.
A broadcast would look like this
`nodomain.freeyourgadget.gadgetbridge.WokeUp`
Would this be possible for the home assistant companion app?

**Comment by dshokouhi** [comment]
> A broadcast would look like this
> `nodomain.freeyourgadget.gadgetbridge.WokeUp`
> Would this be possible for the home assistant companion app?

We will not hard code another apps intents into our app.  More than likely whatever we build will require other apps to update to work with us.  Much like a Tasker plugin requires changes from the app.

**Comment by AlexKnowsIt** [comment]
Maybe I am missing something but as far as I understand this isn't hard coded in easer either. There is a function called "receive broadcast" and there I was able to put in the broadcast content by myself. As far as I understand you could use any app broadcast in there and not just predefined ones. Like this it would be a cool feature for the app because you could define in the app the broadcast triggers from other apps and automate stuff around it.

**Comment by dshokouhi** [comment]
Yea I am familiar with that function.  It does have its own limitations but for intents like you describe it will work.  I don't think sending the data in a sensor will work although the Last Update sensor could benefit from it.  I believe firing an event for requested intents would be better fit so we can ensure each event gets sent.  The app has logic that prevents any sensor from sending an update if the state has not changed.  We can also include any `extras` that gets sent with the broadcast.
