### ISSUE TITLE
Setting to switch off Location services notification

### ISSUE THREAD

**Issue by rosscullen** [home-assistant/android#1303]
**Is your feature request related to a problem? Please describe.**

In version 2021.1.1-full I get a notification every time I open app saying "Location is disabled. The following enabled option(s) require you to enable location. If you do not...". Could you be given the option to "remind me again in x weeks" or "never remind me again".? Many thanks and well done on an excellent app. Really much appreciated.

**Describe the solution you'd like**

Option in "App Configuration to disable notification

**Describe alternatives you've considered, if any**

There may be an option but I haven't found it (sorry). I don't want to disable the features either as I turn on location services (but I've an old phone and I need to conserve power)!

**Additional context**

**Comment by dshokouhi** [comment]
All you have to do is stop using the features mentioned in the pop-up and it will stop.

**Comment by rosscullen** [comment]
Understood @dshokouhi I can see where your coming from. Thanks for clarification 👍 😊

**Comment by stevoh6** [comment]
Hi  I dont wont to create duplicity  thats why I writing here.

I agree, lot of peaople are complaining about not workig features, I understand. 
But anyway I would love to see possibily to turn of this notification in some "advanced/expert" menu for other skilled users. Im using home assistnat on lot of devices, which are present at home due to Covid almost all the time. Its really annoing to confirm this message all the time I open the app. Lot of us have  settuped automations in correct way, that they are not reliable on one source of true, so there is no problem if you accidentaly forgot turn on location services. I dont want to enable disable sensors when im leaving/arriving home in order to get rid of this popup. 

Once again, its good, but it will be better if there is possibility to be able turn if off.

Thanks

**Comment by rosscullen** [comment]
I agree @stevoh6 but @dshokouhi has closed the issue. 

I reluctantly disabled all the related sensors that required Location Services... but I still not the error. It would appear that even using the "Home Network WiFi SSID" option requires location services enabled. I don't know enough about android's inner workings... but why would being connected to my own WiFi SSID require location services enabled??
