### ISSUE TITLE
New device automatically added to person on first login

### ISSUE THREAD

**Issue by sgofferj** [home-assistant/android#1336]
**Home Assistant Android version:**
2021-.1.1-full
**Android version:**
10
**Phone model:**
Blackview Tab8
**Home Assistant version:**
2021.1.5
**Last working Home Assistant release (if known):**
N/A

**Description of problem:**
When the Home Assistant app is installed on a new device and a user logs into Home Assistant through this app for the first time, the device tracker object is assigned to the person object of the user who logged in.

I use the device trackers for presence detection including automatically activating and deactivating various things. Home Assistant is sending me push messages on these events. After I bought a new tablet, I saw the problem that when I left home, the status of my person item would change basically every 15 or so minutes to "home" and shortly after back to "away". It took me quite a while to figure out that the problem was the tablet sitting at home and sending its coordinates, thus setting my person object to "home" which - of course - was changed again when my phone sent its coordinates.

A possible solution would be to open a pop up and ask if the device should be added to the person object.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
N/A
```

**Screenshot of problem:**
N/A
**Additional information:**
N/A

**Comment by dshokouhi** [comment]
This is actually something that HA core does for all mobile app integrations. This request will need to be put on the forums as this impacts everyone who uses mobile app.

**Comment by jchhenderson** [comment]
This is driving me insane as well.

I was sitting watching TV this evening when all my lights went out because HA decided I was away.  After looking at my 'people' settings, HA had added some device trackers that should not and never have been there.  This has happened before and is a big enough issue to make device-tracking unreliable for me as there's no point running automation off something that isn't locked-down (I'm referring to which devices are considered part of my 'people').

The only workaround I can think of is to have 2 'people' for every person (one for device tracking and the other for non-tracking devices).  What a hassle.
