### ISSUE TITLE
Integration of Huawei Push notifications

### ISSUE THREAD

**Issue by Haringstad** [home-assistant/android#1371]
**Is your feature request related to a problem? Please describe.**

Right now, new Huawei devices do not use Firebase for their push notifications. Due to the fact that they are no longer allowed to use Google services. This implies that my new devices do not support notifications.
**Describe the solution you'd like**

Huawei provides their own push notification system. https://developer.huawei.com/consumer/en/hms/huawei-pushkit/ which could be included in the app, so this will start to work on Huawei devices without Firebase.

**Describe alternatives you've considered, if any**

I have been trying to modify the devices to run with Firebase, without any luck. 

**Additional context**

**Comment by dshokouhi** [comment]
This will not be accepted by the Google play store. If the app were to do something like this it would need to be it's own version since this is specific to one manufacturer. Not to mention we can't even test it if we don't have the device. If you install google play services on the device you should get firebase working.

**Comment by andriej** [comment]
I have google play services installed on P40 Pro and firebase does not work unfortunately

**Comment by dshokouhi** [comment]
It doesn't make any sense to do something like this for one manufacturer.

**Comment by Haringstad** [comment]
> It doesn't make any sense to do something like this for one manufacturer.

And why is that? Because you put aside that they are one of the biggest manufacturers of mobile hardware, with a gigantic user base. And, purely based on semantics: Why only support one manufacturer: Google ?

**Comment by dshokouhi** [comment]
> > It doesn't make any sense to do something like this for one manufacturer.
> 
> And why is that? Because you put aside that they are one of the biggest manufacturers of mobile hardware, with a gigantic user base. And, purely based on semantics: Why only support one manufacturer: Google ?

Its not just 1 manufacturer.  Google, LG, Samsung, Sony, Motorola just to name a few all use google play services.  Google is also the primary contributor to Android and they do showcase their new stuff and do also make new releases of Android so yes we do support them otherwise how can we support Android?

closing as we had previously mentioned only the google play services version will support notifications and other services that depend on Google.

If the app were to do something like this it will need to universal, until then we only support notifications on google play services.

**Comment by Haringstad** [comment]
Exactly my point...Sent from my Huawei phone-------- Original message --------From: Andrzej <notifications@github.com>Date: Mon, 22 Feb 2021, 16:05To: home-assistant/android <android@noreply.github.com>Cc: Jacco van Koll <jacco.van.koll@gmail.com>, Author <author@noreply.github.com>Subject: Re: [home-assistant/android] Integration of Huawei Push notifications (#1371)
I have google play services installed on P40 Pro and firebase does not work unfortunately

**Comment by dtila** [comment]
Hi @[dshokouhi](https://github.com/dshokouhi), actually the reporter is right, push notifications don't work on huawei device.

I am developer and I own a Huawei phone with Google Play Services and even with this, they don't work real-time or none. It is normal that applications have integrations with huawei play services for device functions.

Hence, I will try in my spare time to download the SDK and see how I can implement, and if it works. Probably is simple to do, and challenging to implement in the app, but I will try.

The issue should be left opened, until there is a fix.

**Comment by dshokouhi** [comment]
> actually the reporter is right, push notifications don't work on huawei device.

We have decided not to include Huawei services and you can actually get push notifications by modifying the Persistent Connection setting and get the notifications directly.



> I am developer and I own a Huawei phone with Google Play Services and even with this, they don't work real-time or none.

Sounds like you were not using the critical notification format to get real time notifications when using play services.

https://companion.home-assistant.io/docs/notifications/critical-notifications#android

Please note this is not required when using persistent connection for notifications.

https://companion.home-assistant.io/docs/notifications/notification-local


> The issue should be left opened, until there is a fix.

The reason it is not left open is because we need a universal solution, which has already been implemented using the persistent connection.
