### ISSUE TITLE
Look on SD card for Torque log, parse for sensors.

### ISSUE THREAD

**Issue by TRusselo** [home-assistant/android#1408]
**Is your feature request related to a problem? Please describe.**

This feature is to fix a broken integration for "Torque".
Torque is an android application that connects to a vehicle via a bluetooth ODB2 adapter.
Torque allows logging of various vehicle, engine, location, diagnostics information, vehicle fault codes, fuel used, co2 emissions.  The torque app can be run on a phone, tablet, or aftermarket android radio in a vehicle,

The integration has been broken for some time, currently uses legacy authentication via "webserver upload" from the torque app directly to a web server of the users choosing (home asssistant server).  this is broken from a previous torque app update, it does not upload without receiving a special reply back from the webserver.

There are various workarounds that do not work for everyone, such as running a node js server on the android device to parse the torque log and upload it to home assistant server.....  other oddball methods...  none have worked for me.

https://childof69.co.uk/ha-car-telemetry/

**Describe the solution you'd like**

BUT....  the easy fix, no waiting for torque app to update, no webservers, no authentication, no 3rd party apps,

Have Home Assistant Companion app look for torque log on SD card of android device,
Parse the log for new sensors and data.

storage/emulated/0/TorqueLogs/trackLog-2021-Feb-28_11-45-38.csv

**Describe alternatives you've considered, if any**

https://childof69.co.uk/ha-car-telemetry/
https://community.home-assistant.io/t/torque-login-wont-work/3971

**Additional context**

home assistant server bugs related to torque not working:
https://github.com/home-assistant/core/issues/44241?_pjax=%23js-repo-pjax-container

**Comment by dshokouhi** [comment]
I think you can integrate Torque using existing functionality like intents

https://torque-bhp.com/wiki/PluginDocumentation

All of these tasker based intents can work from the app directly, we have outlined this in the latest blog post.  We won't be able to do anything specific for Torque but any type of intent they have you can utilize so should get you all that you need.

**Comment by TRusselo** [comment]
i have no idea what you are talking about.  who is we?  what are intents?  tasker... f##k i hate tasker....
my idea was to get away from need for 3rd party apps.

Your comment might as well been written in Chinese to me

**Comment by dshokouhi** [comment]
Intents are the official way for apps to communicate to one another on Android.  Tasker utilizes intents in the same fashion we (the app) do.  You do not need to use Tasker for this, a lot of apps document Tasker because that is what most users use but in reality they are documenting their Intent API which is what you need to be interested in.  Intents can be used to send data from our receive data, which is exactly what you are after.

To receive data from Torque you will need to refer to the link above to understand all the data you can get from Torque and then you will need to utilize the Last Update Trigger sensor to register for the data and receive it as an intent in Home Assistant.  From there you can use the data however you like.  You will need to do research on this, there is no easy way around it.

receive data using:
https://companion.home-assistant.io/docs/core/sensors#last-update-trigger-sensor

to send data from HA to control torque you will need to use:
https://companion.home-assistant.io/docs/notifications/notification-commands

More about intents in our recent blog post: https://www.home-assistant.io/blog/2021/03/04/android-2021-q1-releases/

If you need more help understanding these things then an issue or enhancement request is not the correct place.  You can get help on Discord or the forums so it can be more direct.

**Comment by TRusselo** [comment]
https://community.home-assistant.io/t/android-intents-sending-receiving-list-starting-activities-too/276192
hey... its you!

**Comment by dshokouhi** [comment]
@TRusselo you just want sensor data, so you want to use the Last Update Trigger to register for the intents.  In the Torque link above you want to focus on everything after this line

`Torque also sends an intent when an Alarm PID is triggered:`

Look at the table below to see what data you want, in the app register for `org.prowl.torque.ALARM_TRIGGERED`

Then listen for the `android.intent_received` event in Home Assistant and look at the data you receive in HA to use

**Comment by dshokouhi** [comment]
I have also added the Torque link to the forum post to help others out in the future :) if you still need help hop on Discord and there are a few users who can help out including myself.  Will be better than an issue to discuss

**Comment by larryallingham** [comment]
Late to the party, but still trying to solve the problem. The intents solution suggested above isn't practical as the only usable intent is the ALARM_TRIGGERED intent. Alarms in Torque are configured for each specific metric and value (threshold) that you want to be alerted to - and they result in a popup and an audible warning on the phone every time they are triggered. This is not a feasible way to capture Torque data. 
And yes, the Torque plugin is still broken 5 years later.

**Comment by TRusselo** [comment]
> Late to the party, but still trying to solve the problem. The intents solution suggested above isn't practical as the only usable intent is the ALARM_TRIGGERED intent. Alarms in Torque are configured for each specific metric and value (threshold) that you want to be alerted to - and they result in a popup and an audible warning on the phone every time they are triggered. This is not a feasible way to capture Torque data. And yes, the Torque plugin is still broken 5 years later.

Hey Larry thanks for the reply, please reopen a new issue. Closed issues rarely get looked at for updated comments
Make sure to link this in the new issue report.
@larryallingham
