### ISSUE TITLE
Temperature sensor

### ISSUE THREAD

**Issue by stipe76** [home-assistant/android#1440]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Is there any chance of adding a temperature sensor for to display the phone's current temperature? A lot of the battery apps have this data included. Any chance of adding it? 

Thanks

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
@stipe76 device temperature and battery temperature are 2 different things here.

Device temperature has been deprecated since Android 4.0 and I dont think many devices support it or its replacement: https://developer.android.com/reference/android/hardware/Sensor#TYPE_TEMPERATURE

Battery temperature is possible if thats what you are after: https://developer.android.com/reference/android/os/BatteryManager#EXTRA_TEMPERATURE

**Comment by stipe76** [comment]
Yes, battery temperature would be grest. Thanks
