### ISSUE TITLE
Long press Template Widget to open edit box and allows changes to template

### ISSUE THREAD

**Issue by nunojpg** [home-assistant/android#1468]
Currently it is required to use a third party app and copy and paste the template to manage any complex template. It is easy and very convenient to support a long press on the Template Widget to support opening the original edit box and allowing to edit the template content.

**Comment by dshokouhi** [comment]
Please don't remove the feature request template.

Also long press actions are not supported on widgets, at least according to stack overflow since it uses a remote view

https://stackoverflow.com/questions/5693782/is-it-possible-in-an-appwidget-to-detect-a-long-press

You can edit the template widget inside App Configuration > Widgets if you were unaware.

**Comment by nunojpg** [comment]
Sorry for not following the rules. Thanks for the suggestion. I really appreciate.
