### ISSUE TITLE
Improve default behavior for enabling/disabling app sensors

### ISSUE THREAD

**Issue by CarlosGS** [home-assistant/android#1507]
**Is your feature request related to a problem? Please describe.**

We always disable all app sensors, for privacy reasons and to keep HASS lean.
The current app makes it a bit tricky:
1. Some sensors are enabled by default, with no way of disabling them before app setup, so they are always updated at least once. This creates spurious items in the HASS database for each phone installation.
2. ~~In the selection menu, there is a checkbox to "enable all sensors". Given there are 70 sensors to check, we are forced to momentarily enable all of them, to be disabled afterwards.~~ Edit: There is already a filter option at the top
3. ~~Recently, an app update incorporated new sensors. Turns out these were enabled by default (!!). Suddenly we were getting the _updating sensors_ notification out of the blue. In our case it's all local, but it still felt like an intrusion of privacy, specially after unchecking _"enable all sensors"_ days earlier.~~ Edit: This only happened for one sensor

**Describe the solution you'd like**

1. Providing a checkbox "enable sensors" right after login, at the same page that says "Connect to Home Assistant".
The option would appear next to the "enable location tracking" checkbox. It could also become a drop down menu for different selections (disable all, enable location, location+basic sensors, enable all, etc).
2. ~~Adding the complementary option "disable all sensors".~~
3. ~~Any newly incorporated sensors should not be enabled by default. (_Maaybe for those who checked "enable all sensors"_).~~

**Describe alternatives you've considered, if any**

Another option would be to have a setting within HASS itself, to prevent arbitrary app sensor incorporation.

Please let us know of any tips or if we are doing anything wrong in our setup :sweat_smile:  Thanks! :D

**Additional context**

**Comment by dshokouhi** [comment]
> 1. Some sensors are enabled by default, with no way of disabling them before app setup, so they are always updated at least once. This creates spurious items in the HASS database for each phone installation.

This is to be expected as all battery sensors are included by default, most users expect this.



> 2\. In the selection menu, there is a checkbox to "enable all sensors". Given there are 70 sensors to check, we are forced to momentarily enable all of them, to be disabled afterwards.

This is not true as you can also go to each individual sensor and disable it one by one.  You can also filter by enabled sensors to make it easier to find to disable them



> 3\. Recently, an app update incorporated new sensors. Turns out these were enabled by default (!!). Suddenly we were getting the _updating sensors_ notification out of the blue. In our case it's all local, but it still felt like an intrusion of privacy, specially after unchecking _"enable all sensors"_ days earlier.

There was only 1 sensor and as it was a battery sensor it was enabled by default, as above this is to be expected because most users expect battery sensors by default.  The toggle above only reflects the sensors added and it does not mean that future sensors will not be enabled or disabled.  Most sensors are indeed disabled by default but this release introduced a new battery sensor that got enabled by default.

> 1. Providing a checkbox "enable sensors" right after login, at the same page that says "Connect to Home Assistant".
>    The option would appear next to the "enable location tracking" checkbox. It could also become a drop down menu for different selections (disable all, enable location, location+basic sensors, enable all, etc).

This is going to be too many options and confusing for most users.

> 3\. Any newly incorporated sensors should not be enabled by default. (_Maaybe for those who checked "enable all sensors"_).

This is already done but as explained above there was only 1 sensor added.

The only way I see us solving this is to keep all sensors disabled by default however thats not going to be ideal for new users. The app only enables a handful of battery sensors by default and I think thats a good compromise considering most users do indeed want battery sensors.  Also you are free to disable the sensor worker channel so you don't see those updates in the future.

**Comment by T-bond** [comment]
I support the idea of adding option to disable sensor on setup.
Or maybe a better one would be an option to delete the associated sensor entity if disabled.
My current workaround is to disable the sensor, logout, remove the integration, and login. This way it won't add the unnecessary sensors, like battery health, or charger type.

Removing after disabling it would also solve the problem, if after some time, I choose to disable one of my sensor, then I would not need the entity as it would be useless.

**Comment by dshokouhi** [comment]
> Or maybe a better one would be an option to delete the associated sensor entity if disabled.

we plan to do this once the mobile app integration is updated to support it

**Comment by CarlosGS** [comment]
@dshokouhi Thanks for the detailed answer! It solves 2 & 3 right away O:)

> You can also filter by enabled sensors to make it easier to find to disable them

Sorry, I didn't see that option before. Also, I didn't realise the update happened for only one sensor. I've crossed out 2 & 3.

> The only way I see us solving this is to keep all sensors disabled by default however thats not going to be ideal for new users. The app only enables a handful of battery sensors by default and I think thats a good compromise considering most users do indeed want battery sensors.

I agree, new users could miss interesting functionality if it's disabled by default, and sensors are a key element of the app. I'm unsure on the last part though, "most users" feels more difficult to define.

However I've realised of big fact - **at some point the lovelace page stopped showing phone sensors. We started with HASS a year ago, when the interface quickly became cluttered.** This doesn't seem to be the case anymore, hence it is not so important to "keep HASS lean" as those sensors are now hidden from the default view.
I'm afraid I had this in mind when writing this issue. After consciously testing, it doesn't seem so problematic to have a few battery sensors enabled by default, seeing they don't appear in lovelace at all.

And the biggest opt-in is location, which is already available as an option. Plus your latest comment on plans to delete the disabled entities. So, closing this issue now. Thanks for your prompt help!

> Also you are free to disable the sensor worker channel so you don't see those updates in the future.

Regarding the notification, I just want to point out that it was what "creeped us out" recently, as it started appearing suddenly after the app update.
Sounds like an Android requisite so that the app can work in the background. Otherwise, why is the notification enabled by default?

**Comment by dshokouhi** [comment]
> However I've realised of big fact - **at some point the lovelace page stopped showing phone sensors. We started with HASS a year ago, when the interface quickly became cluttered.** This doesn't seem to be the case anymore, hence it is not so important to "keep HASS lean" as those sensors are now hidden from the default view.
> I'm afraid I had this in mind when writing this issue. After consciously testing, it doesn't seem so problematic to have a few battery sensors enabled by default, seeing they don't appear in lovelace at all.

Some fun history on this, I believe it was the android app getting so many sensors that caused the frontend devs to hide it from default view.  It was done to prevent the very issue you see, overloaded with sensors once you sign in 😂 



> Regarding the notification, I just want to point out that it was what "creeped us out" recently, as it started appearing suddenly after the app update.
> Sounds like an Android requisite so that the app can work in the background. Otherwise, why is the notification enabled by default?

In order for the app to stay alive during sensor updates and to keep the sensor worker alive we had to convert the background service to a foreground service which requires the notification.  Before this we had issues where sensors would stop updating after a few days because the worker got killed.  The good thing is that all android devices running 8.0 and later support notification channels so users are in full control over this notification.  That was the best compromise we can do to keep the app running as expected and least intrusive.  All foreground services are required to be low priority which causes a notification to be visible briefly but given its a channel you can minimize or even turn off the channel completely.
