### ISSUE TITLE
Samsung Device Control doesn't show entity UI until screen is tapped

### ISSUE THREAD

**Issue by ruifung** [home-assistant/android#1522]
**Home Assistant Android version:**
2021.4.1-full
**Android version:**
11
**Phone model:**
Samsung S20 FE 5G
**Home Assistant version:**
2021.4.5
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
When clicking on a device in the samsung device control, it attempts to open the entity view from home assistant.
However, for me it appears to open a blank screen... until I tap anywhere on the screen at which point the HASS UI actually loads.... and shows the entity info screen for a moment before it is closed.

This results in a somewhat inconvenient usage as now I have to navigate back to said entity to actually access its settings.

This doesn't appear to happen with google home, so it is home assistant android specific.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20210418-065116_Photos](https://user-images.githubusercontent.com/1073945/115128748-9be0f980-a012-11eb-94d6-593e0c947255.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
Please disable and remove card-mod from your configuration. It interferes with the entity pop-up feature.

**Comment by T-bond** [comment]
I have the same issue. Only difference the, when I click on the blank space, and it loads, it **won't** dissappear. But the problem, that it does not load without a tap is here too. I don't have card-mod.

**Comment by dshokouhi** [comment]
So the issue where the screen needs to be tapped is not really controllable by the app. We provide the pending intent and the system handles it however it handles it.  When the feature was first introduced it was working as expected and the code hasnt changed since then.  As this is a new android 11 feature its probably has some bugs around including a webview activity instead of a normal activity. We launch the frontend from a shortcut in the exact same manner.

The issue where the entity pop-up disappears is related to card-mod.
