### ISSUE TITLE
[Feature request] Add option to disable toast messages for widget errors

### ISSUE THREAD

**Issue by jmoransalama** [home-assistant/android#1541]
**Is your feature request related to a problem? Please describe.**

Whenever my phone loses cell reception, my wifi connection is bad, or my home-assistant server is down I constantly get toast messages that say:
> Unable to fetch data for configured entity

This is super annoying for me, the message will appear constantly on top of other apps making them unusable (For example, I can't take pictures while the toast is appearing because it's on top of the shutter button). Force stopping the app doesn't make this toasts stop.

**Describe the solution you'd like**

Please consider adding an option in the app settings to disable this toast messages. Or maybe change them so they will only be shown once every couple hours. For example, if I already know that my home-assistant instance is down, I don't need to be reminded every 30 seconds.

**Describe alternatives you've considered, if any**

I don't know if its possible, but wouldn't it be better to completely remove this toasts, and just show an error sign on top of each widget?

**Additional context**

Related:
https://github.com/home-assistant/android/issues/1120
https://github.com/home-assistant/android/issues/1164

**Comment by dshokouhi** [comment]
So these toast error messages only show up during their normal update interval or when the user taps on them. If you are seeing it periodically it is probably staying for a long period of time because a toast message is shown for each widget that fails to update on its own.

the update interval is set to minimum of 30 minutes and not 30 seconds
