### ISSUE TITLE
App fails to connect

### ISSUE THREAD

**Issue by junalmeida** [home-assistant/android#1834]
**Home Assistant Android version:**
Latest October 16 2021 Beta

**Android version:**
10

**Phone model:**
Huawei P30

**Home Assistant version:**
2021.10.6

**Last working Home Assistant release (if known):**

**Description of problem:**
Android app fails with connection problems while the Chrome browser connects without problem on the same device and WiFi network. No crash happens. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/991675/138705652-f1b0c741-c437-4eae-8443-f5ad9e21e9fa.png)

**Additional information:**

**Comment by junalmeida** [comment]
Sorry, what evidences do you have to say my network is changing a url? I thought I was very clear that the scenario here is: DNS Split, using AdGuard, and that's it. 

I was clear to say this is not working. The app is supposed to reach a url and it is not reaching it. It only reaches when I force an IP address, which does not happen with the browser, and any other device. 

Ok you are clearly not willing to investigate or fix any bug, which is very sad for such a good solution as Home Assistant. Thank you for not looking into that.

**Comment by dshokouhi** [comment]
> Sorry, what evidences do you have to say my network is changing a url?

So like I said before the app gets an external and internal URL from the user. The only logic we use here is when to use which URL. The fact that you said yourself it works with a local IP when you don't use DNS Split and Ad Guard does indeed suggest the issue is on your end. There is no other way around that. You bypassed your unique setup and confirmed your setup is the issue externally speaking.

for me personally I do not use adguard or DNS split, my router supports NAT loopback and I use that along with my domain name. HA is also configured to serve my SSL cert so I cannot use the local IP address as a result.



> The app is supposed to reach a url and it is not reaching it. It only reaches when I force an IP address, or after some time, which does not happen with the browser, and any other device.

Have you tried looking at your DNS/network logs and observe the requests coming from the app?



> Ok you are clearly not willing to investigate or fix any bug, which is very sad for such a good solution as Home Assistant. Thank you for not looking into that.

All I can do is tell you how the app works and what the app expects. In terms of the app we treat the internal and external URL the same. They get the same data and use the same API's, there is no difference there.
