### ISSUE TITLE
[Feature request] Android Widget Template font-size and background color

### ISSUE THREAD

**Issue by chertvl** [home-assistant/android#1852]
**Describe the solution you'd like**
It would be great to implement possibility to change background color and trasparency of android Template Widget,
and also add the ability to change the font size with html-tags (like we can change color and style of the font (bold, etc) ).

This will create endless possibilities for changing the appearance, taking into account the existing html possibilities.

![photo_2021-10-29_13-22-51](https://user-images.githubusercontent.com/38353584/139419147-8f5aa5ae-8799-43e7-ac90-b5b08171d1b9.jpg)

**Comment by leonelsr** [comment]
I'd just like to note that currently, both `<big></big>` and `<small></small>` also work! See example below.

They're better than header tags because they don't add margins and such. But yes, I wish I could have parameters to define margin, padding, element size etc. That would save me from the `<small><br><br></small>` workaround I ended up using on the widget below, and could actually make it much more flexible and customizable.

Full `style="..."` CSS support would be insanely great, however I can imagine how difficult that must be to implement...

And yes, we definitely need at least background color and transparency customization ability for all the Widgets.

My example, I really wish this could have transparent background and white (or colored) fonts:
![unnamed](https://user-images.githubusercontent.com/490788/144100173-b4bea19b-2975-4ca3-9d3e-f337a6679696.png)

The code I've used on that template widget was this:
```
<big><strong>{{states('sensor.temperatura_externa')|float|round(1)}}</strong>°</big><br>
Rua
<small><br><br></small>
<big><strong>{{states('sensor.temperatura_interna')|float|round(1)}}</strong>°</big><br>
Quarto
```

**Comment by dshokouhi** [comment]
So you can try taking a look at the available flags `fromHtml` allows but as of now we are using the `LEGACY` because the app supports API 21 and those flags are only available from API 24 and onwards. None of them seem to allow what your real goals are unfortunately

https://developer.android.com/reference/android/text/Html#constants_1

**Comment by iridris** [comment]
I'd love to see transparency supported for the widgets - I'd like to see my background, not a big black box around the bit of data I'm looking at. 

For an example of what I'd like to achieve, here's a screenshot. On the left, is a widget from an app called SharpTools (which is tied to my SmartThings account). On the right is Home Assistant showing the same status. I'm trying to move away from SmartThings/Sharptools, but not having transparency on the widgets is a blocker for me. 
![Screenshot_20220429-191349](https://user-images.githubusercontent.com/952387/166079645-6a06214d-8bee-4183-836b-395579b94864.png)

**Comment by iridris** [comment]
I manually installed the latest build of the app and the new theming (specifically transparency) is working perfectly for me. Thank you so much @jpelgrom!!!
