### ISSUE TITLE
Wear OS - Show a toast notification and vibrate when pressing an item in wear os app

### ISSUE THREAD

**Issue by HunterX86** [home-assistant/android#1878]
**Is your feature request related to a problem? Please describe.**
When pressing an item, i don't know if for example a light is turned on or i run a script.

**Describe the solution you'd like**
Show a toast message and vibrate (haptic feedback) when pressing an item.

**Describe alternatives you've considered, if any**
[Android Toast](https://developer.android.com/guide/topics/ui/notifiers/toasts)
[Haptic Feedback](https://developer.android.com/reference/android/view/HapticFeedbackConstants)

**Additional context**

**Comment by dshokouhi** [comment]
Nice request! It looks like some of these are also mentioned in the material design guidelines. We should also show the time at the top.  I wonder if for haptic feedback if we should make it a setting users can enable/disable?

Also there is a new update coming where the chips are converted to toggles so that should help reflect the state in a better way.

https://developer.android.com/training/wearables/design/overlays#time

**Comment by leroyboerefijn** [comment]
I especially like the haptic feedback. Would it make sense to follow the system settings for haptics? If at all possible.

For toasts, I'm not personally a fan. But as a setting, why not!

Finally for the clock text, there should be a compose item for it ;)

**Comment by dshokouhi** [comment]
> Would it make sense to follow the system settings for haptics? If at all possible.

I think it should, is there a system setting for this? I didn't see it on my watch but we would need the vibrate permission

**Comment by leroyboerefijn** [comment]
On my Galaxy watch 4 I have a system vibrations toggle. No idea if we could even use that. But on second thought, maybe it makes more sense as an app setting?

**Comment by dshokouhi** [comment]
yea i think an app setting makes more sense, especially since I dont see a global setting on my Fossil watch lol.  Probably a good idea to leave it off by default so it matches current behavior?

**Comment by HunterX86** [comment]
Here is an example that can be implemented to show a toast for the chips
`chip_message.setOnClickListener {Toast.makeText(context, "Message", Toast.LENGTH_SHORT).show()}`

**Comment by dshokouhi** [comment]
@HunterX86 we have actually switched to Compose so the function call is a bit different. Right now we are trying to figure out what a good default value is. I think we may leave it all off and let user turn on in settings so the functionality is the same. If we were to leave any on maybe the haptic feedback because when I tested the toast message it takes up the whole screen so not sure how desirable that is but the haptic feedback makes sense.
