### ISSUE TITLE
Add details pane with entity controls in Wear OS

### ISSUE THREAD

**Issue by leroyboerefijn** [home-assistant/android#1892]
**Is your feature request related to a problem? Please describe.**
You cannot adjust brightness, color, fan speed, etc. from the Wear OS app

**Describe the solution you'd like**
When tapping the Chip (not the toggle), a details pane should open that allows for customization of the entity. For lights this could be brightness and color, for fans this could be speed, for covers this could be percentage opened, etc.

**Describe alternatives you've considered, if any**
Can't think of alternatives

**Additional context**

**Comment by dshokouhi** [comment]
So this will work great for existing `ToggleChip` as we can convert it to a `SplitToggleChip` however we may need to do specific domain overrides when it comes to things like `climate` entities. `script` and `scene` may not require this feature since there is nothing additional to set? But then it makes me wonder if `switch` needs it as well? 

hmm maybe a good place to start is what other details should we show on the details screen? Entity history maybe?  We should probably think about what the base details screen will look like so we can add domain specific functionality separately?  Lots of questions great request!

**Comment by leroyboerefijn** [comment]
Indeed, this only applies to entities that do more than just toggle. The sliders/settings on the details pane also need to depend on the abilities of the entity. Next to entity type, not all lights support color for example. Some only support dimming, or color temperature, or whatever other property. So it might not be easy to get this to support all possibilities nicely.

For other details, that is a good question indeed. On one hand, Wear OS is intended for quick actions and glanceable information. On the other hand we want to provide some flexibility to our users. I think it will be a fine balance.

**Comment by dshokouhi** [comment]
> Indeed, this only applies to entities that do more than just toggle. The sliders/settings on the details pane also need to depend on the abilities of the entity. Next to entity type, not all lights support color for example. Some only support dimming, or color temperature, or whatever other property. So it might not be easy to get this to support all possibilities nicely.

So we can actually perform a check in the entity attributes here. If the entity supports it then it will have a `supports_feature` flag in its attributes. We do a similar check in device controls: https://github.com/home-assistant/android/blob/1c748663e4e896e74f9ef4fddb9c45d26e8bea93/app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt#L46

https://developers.home-assistant.io/docs/core/entity/light#support-feature

**Comment by dshokouhi** [comment]
Started looking into this and came to realize that `SplitToggleChip` does not offer `appIcon` which we use to display the icon for the entity. Made a request to Google since based on the description you would think the only difference between a `ToggleChip` is the 2 different targets for a user to select. The chips also do not accept the `onLongClick` modifier.  So not sure what the best path forward is. Definitely don't want to convert back to `Chip` but also don't want to lose the functionality of custom icons.

**Comment by leroyboerefijn** [comment]
Ah I see now that the divider in the split toggle takes up a lot of space. So kinda makes sense that it doesn't have an icon. 
If they add long press support, that would also work I guess.

**Comment by dshokouhi** [comment]
The problem with long press is that it then becomes hidden to users even though long pressing is common to us.  I had asked google about possibly adding the icon but its just not possible, they gave a very thoughtful answer and some considerations for our use case :) https://issuetracker.google.com/issues/206022561#comment5 

5 characters for a label would never cut it lol

![image](https://user-images.githubusercontent.com/1634145/143327150-24416fba-0b0d-46bd-94b5-3f7b845f70b2.png)


So I think maybe we need to add a new chip for entity details so users can access that there. Now another thing to consider when building the UI out. I suppose maybe we can make an option to always load entity details or possibly just a new chip for getting to the details. As of now only the `light` domain would qualify for additional actions.

**Comment by leroyboerefijn** [comment]
So the example makes it understandable, great that they gave such an elaborate answer!

I don't like adding a second chip, that would double the already long list of lights.

I see two options: long press, or separate press action on the icon. Both are indeed a bit hidden to the user. Could we add an explanation to some introduction/tutorial flow that you also mentioned for the favorites?

**Comment by dshokouhi** [comment]
> I see two options: long press, or separate press action on the icon.

So long press on the chip didn't work, I think the parent has a modifier that overrides what we set. Maybe I didn't find the correct way to do it?

Pressing the icon is interesting but I wonder if the modifier would be overriden by the parent which is the chip 🤔 



> Could we add an explanation to some introduction/tutorial flow that you also mentioned for the favorites?

I think we are going to have to if details will be hidden as such.

Long press feels like the more natural response to me even if it is hidden. At least on the phone side long press is used for additional actions which is exactly this.

If all else fails we can always offer the user an option of adding quick glance toggles with icons or toggles that can have additional details and let the user decide.  Personally I like to think that users are adding custom icons for all favorites but that just may not be the case lol.  All that said though there are still some domains which will require the details screen. Like for example I can see `alarm_control_panel` being a chip that takes the user to the details screen where they will want to turn off the alarm by entering a code. Or they may want to adjust an input number. Hard to tell what users will really want without seeing feature requests come through. `climate` is another domain that has to have a details chip because of the modes and setpoints.

All this makes you wonder what the focus should be which is why I love that we are open source and volunteers. To me I feel like even though the list of entities can be crazy thats just the nature of HA, we all have tons of devices to control otherwise we wouldn't be here. So to me I think a good focus would be on getting all the domains supported in the app because with favorites the user will decide whats on the home screen.

**Comment by leroyboerefijn** [comment]
Fully agreed and very well put haha

So I think the way to go would be long press + tutorial. If long press is not possible that sounds like a compose bug to me...

**Comment by dshokouhi** [comment]
Yea we should file whichever bugs we feel are bugs and get an official response, I really like how responsive they are in the issue tracker. The more feedback we send the better things will get :)

**Comment by leroyboerefijn** [comment]
I also tried playing with a long press. What I found with testing and info online is:
- Adding a long press listener to the chip doesn't work, since the chip already has a click listener
- Adding a `Box` around the chip with a long press listener doesn't work, since the chip will still handle the click first

Options that do work
- Adding a long click listener to the `Text` composable in the label. Two downsides: we need to perform the same action in the Text click as we do in the Chip's `onCheckedChange` and long click will only work on the label, not the rest of the chip.
- Making a fully custom Chip that handles both click and longClick. The chip is basically a `Row` with an icon, text, toggle and rounded corner background. But it is of course a bit of work to implement nicely.

@dshokouhi what do you think the best approach would be?

**Comment by leroyboerefijn** [comment]
I've tested the long click on `Text` a bit now. It actually works pretty well. It is the largest part of the chip anyways

**Comment by dshokouhi** [comment]
I think long click on `Text` may make the most sense here as that is the same location we were thinking of having the long click.
