### ISSUE TITLE
Wear OS - Ability to disable entities displayed on the watch.

### ISSUE THREAD

**Issue by brewston** [home-assistant/android#1910]
**Is your feature request related to a problem? Please describe.**

The fear of accidentally toggling something. For example, I have a power plug on my washing machine, mainly to monitor power usage, but it also has an on/off. The on/off isn't exposed in any of my lovelace dashboards or automations, I always want my washing machine to have power :) Equally though, I don't want to disable the switch entity in HA, I just want my watch to not ever be able to see it.

There are also some entities, like input booleans, which probably never need to be seen on my watch.

**Describe the solution you'd like**
An ability to disable entities so they don't appear on my watch. Hopefully, it will also speed up load times if the watch is told never to look for them. I realise there is now a favorites section but the non-favorites are still loaded in the background right ?

**Describe alternatives you've considered, if any**
N/A

**Additional context**
N/A

**Comment by dshokouhi** [comment]
So far our plan for the home screen is to just show the favorites and move the loading of all entities to another screen.  I think that should suffice here.  Telling the app which entities/domain to hide during the loading of all entities won't help with the speed of things because we already have to get a list of all entities in one call as opposed to many calls for each and every entity.

The load times in the app are currently not of concern because the compose libraries we are using are in the Alpha phase. Google had mentioned in their slack channel for developers that performance will be worked once in the Beta phase of the libraries. The Alpha phase is expected to last a couple of quarters as they work in pulling the rest of the functionality because they got a bit of work to do there.

**Comment by blair287** [comment]
> So far our plan for the home screen is to just show the favorites and move the loading of all entities to another screen. I think that should suffice here. Telling the app which entities/domain to hide during the loading of all entities won't help with the speed of things because we already have to get a list of all entities in one call as opposed to many calls for each and every entity.
> 
> The load times in the app are currently not of concern because the compose libraries we are using are in the Alpha phase. Google had mentioned in their slack channel for developers that performance will be worked once in the Beta phase of the libraries. The Alpha phase is expected to last a couple of quarters as they work in pulling the rest of the functionality because they got a bit of work to do there.

Would still be nice to choose what appears like if I clicked on a lights section I have for example 3 lights and a group that contains those 3 lights now in lovelace I only show the group would be awesome to have same on watch and just keep it clean with only entities you need not hundreds of unused ones.

**Comment by dshokouhi** [comment]
> Would still be nice to choose what appears like if I clicked on a lights section I have for example 3 lights and a group that contains those 3 lights now in lovelace I only show the group would be awesome to have same on watch and just keep it clean with only entities you need not hundreds of unused ones.

You can do that today with Favorites, just select what you want and it will appear at the top.

What we were discussing was that the loading of all entities underneath favorites would be moved to a separate screen for users who would need that.

**Comment by blair287** [comment]
> > Would still be nice to choose what appears like if I clicked on a lights section I have for example 3 lights and a group that contains those 3 lights now in lovelace I only show the group would be awesome to have same on watch and just keep it clean with only entities you need not hundreds of unused ones.
> 
> You can do that today with Favorites, just select what you want and it will appear at the top.
> 
> What we were discussing was that the loading of all entities underneath favorites would be moved to a separate screen for users who would need that.

If favorites will be entities you want might be worth have categories inside favorites to make it easier to find stuff.

Still for example I have added a lock to my favorites (using script) so when I double tap my home button it opens HA and I can tap to unlock my door.

But I wouldn't mind having for example lights in favorites too but it would be nice to have the lock at the top still to prevent having to scroll to it.

Dunno if there is a way to facilitate that at all?

**Comment by brewston** [comment]
@blair287 categories _could_ be sorted by areas (lounge, kitchen etc) via https://github.com/home-assistant/android/issues/1795 - which would make it easier to find what you want. Personally, I'd prefer favorites to remain as a simple list.

**Comment by brewston** [comment]
@blair287 I don't disagree that being able to disable entities would be useful (I logged this ER ;-) ) Maybe the work being done phone side on https://github.com/home-assistant/android/pull/1908 will help here ? The point I was trying to make was that it's preferable to keep favorites list simple.

**Comment by dshokouhi** [comment]
> If favorites will be entities you want might be worth have categories inside favorites to make it easier to find stuff.

So thats our plan to split them up and have categories (if they want). For now we can do it by domain but we can also add area or maybe even let a user create a custom category :) 



> But I wouldn't mind having for example lights in favorites too but it would be nice to have the lock at the top still to prevent having to scroll to it.

My plan was actually to add some type of drag and drop method to the phone settings as its much easier to re-order things like that on a phone than on a watch 😁 



> categories _could_ be sorted by areas (lounge, kitchen etc) via #1795 - which would make it easier to find what you want. Personally, I'd prefer favorites to remain as a simple list.

This is why I would like to make it optional to show, I think the reordering of entities in favorites will be useful to all but I can see the desire for custom categories.

> I'm just thinking with no ability to disable entities from showing in app it is going to get very messy very quickly it already is a giant list with the domains that we only have now.

This is exactly why I think moving the loading of all entities to another screen needs to happen, it will make the home screen load faster and only show what matters to the user.

> I have over 50 inputs like booleans and number etc that I use in automations I don't need these on a watch.
> 
> Also if for example you have a chandelier with 6 bulbs in, I only need the group not 6 individual bulbs.
> 
> It's a small screen and cramming 500 entities into it doesn't look very user friendly.

So this is why we have favorites so users can choose what entities they want to appear, its also the reason as to why we have collapsing and expanding categories so it makes it easier to scroll. You can also use the bezel on your watch to scroll as well.



>  but I think overall from the phone app you should be able to select what entities show up on the watch to keep it clean.

Yup I agree which is why we have started the building blocks for the 2 way communication to achieve this :)



> If it takes 60 seconds to scroll past the 200 unused entities to find the one light I want to turn on it's pointless might as well get phone out and do it.

I assume you have not use the collapsing/expanding category feature? It doesnt take too long to close them and get to the next section :) I do agree its a bit much to show everything but that was the original design. Now that we have favorites setup we just need to use that to make the home screen experience better for all users. For now the favorites being at the top should help alleviate some of these concerns while we work on a better path forward

**Comment by blair287** [comment]
> > If favorites will be entities you want might be worth have categories inside favorites to make it easier to find stuff.
> 
> So thats our plan to split them up and have categories (if they want). For now we can do it by domain but we can also add area or maybe even let a user create a custom category :)
> 
> > But I wouldn't mind having for example lights in favorites too but it would be nice to have the lock at the top still to prevent having to scroll to it.
> 
> My plan was actually to add some type of drag and drop method to the phone settings as its much easier to re-order things like that on a phone than on a watch 😁
> 
> > categories _could_ be sorted by areas (lounge, kitchen etc) via #1795 - which would make it easier to find what you want. Personally, I'd prefer favorites to remain as a simple list.
> 
> This is why I would like to make it optional to show, I think the reordering of entities in favorites will be useful to all but I can see the desire for custom categories.
> 
> > I'm just thinking with no ability to disable entities from showing in app it is going to get very messy very quickly it already is a giant list with the domains that we only have now.
> 
> This is exactly why I think moving the loading of all entities to another screen needs to happen, it will make the home screen load faster and only show what matters to the user.
> 
> > I have over 50 inputs like booleans and number etc that I use in automations I don't need these on a watch.
> > Also if for example you have a chandelier with 6 bulbs in, I only need the group not 6 individual bulbs.
> > It's a small screen and cramming 500 entities into it doesn't look very user friendly.
> 
> So this is why we have favorites so users can choose what entities they want to appear, its also the reason as to why we have collapsing and expanding categories so it makes it easier to scroll. You can also use the bezel on your watch to scroll as well.
> 
> > but I think overall from the phone app you should be able to select what entities show up on the watch to keep it clean.
> 
> Yup I agree which is why we have started the building blocks for the 2 way communication to achieve this :)
> 
> > If it takes 60 seconds to scroll past the 200 unused entities to find the one light I want to turn on it's pointless might as well get phone out and do it.
> 
> I assume you have not use the collapsing/expanding category feature? It doesnt take too long to close them and get to the next section :) I do agree its a bit much to show everything but that was the original design. Now that we have favorites setup we just need to use that to make the home screen experience better for all users. For now the favorites being at the top should help alleviate some of these concerns while we work on a better path forward

Thanks for your replies.

I have used the collapsing categories but for example inside switch I still have over a hundred entities so it's still a lot of scrolling to find the one I want.

So far though it's good love the fact I can unlock my door from watch without having to use third party app, great work!

**Comment by dshokouhi** [comment]
We have moved the loading of all entities to a separate screen now so closing this request as the main issue is now solved :)
