### ISSUE TITLE
Script names in Wear Favorite Entities dialog on phone

### ISSUE THREAD

**Issue by Steltek** [home-assistant/android#2048]
**Is your feature request related to a problem? Please describe.**

The "Set Favorites on Wear OS Device" dialog on the phone shows the script names by their entity name in the config, not their set name. I can't distinguish between script.1546454997069 and script.1546454997070.

**Describe the solution you'd like**

Display the script names as defined in the UI, rather than the entity IDs.

**Describe alternatives you've considered, if any**

Manually looking up the script that I want to find its entity ID, so I know what to add.

**Additional context**

**Comment by dshokouhi** [comment]
so one thing we have to consider here is that the friendly name has the potential to be the same across different domains. I think we should look into displaying the domain of the entity so its easier to distinguish which entity it is. Not sure if we should keep the domain in the row next to the name or split things up by domain like we do in the watch app. 

This is why I originally opted to show the entity ID because those are indeed unique compared to a friendly name
