### ISSUE TITLE
minor UI defect in new persistent connection settings UI

### ISSUE THREAD

**Issue by w1ll1am23** [home-assistant/android#2282]
**Home Assistant Android version:**
2022.2.1-full

**Android version:**
11

**Phone model:**
Pixel 3

**Home Assistant version:**
2022.2.5

**Last working Home Assistant release (if known):**

**Description of problem:**
Bottom copy is cut off when selecting always. Maybe these view should be in a scroll view 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20220214-102502_Home_Assistant](https://user-images.githubusercontent.com/6432770/153893503-5639b950-4f7b-41a5-a9a1-f06b750ed29d.png)

**Additional information:**

**Comment by dshokouhi** [comment]
Yea we should make the column scrollable, good catch :)

**Comment by scop** [comment]
Is there any other way to reach the "Manage websocket notification channel" view than the button/link that is not visible due to this issue?

**Comment by dshokouhi** [comment]
> Is there any other way to reach the "Manage websocket notification channel" view than the button/link that is not visible due to this issue?

Yes you should be able to long press the notification and click on the gear icon, may be different on a different device. Or you can go to device settings and look at the notification channels for the app from there. Every device has different steps but the main thing is its an android setting change.

**Comment by scop** [comment]
Ok, I was actually there already. I didn't know I was in the right place (if I was?) because the message recommends to "minimize the notification to hide the icon" but I'm unable to locate such an option there. I do have an option to "disable notification" but I'm not sure that's the one (doesn't sound like it -- would that disable notifications from HA?) and a bunch in the categories view but nothing that would point towards "minimize notification". OnePlus Nord2 5G, Android 11. But perhaps this is already off topic for this issue.

**Comment by scop** [comment]
I won't bother you with the screenshot because it's in Finnish :), no idea what the original is but it translates to "disable notifications". Anyway I clicked that and then was presented a choice of options what notifications to disable, one of which was the persistent connection and the icon is gone now. Thanks!
