### ISSUE TITLE
Home Assistant on wear OS only connect when my home assistant instance using only http

### ISSUE THREAD

**Issue by wladikazoltan** [home-assistant/android#2376]
**Home Assistant Android version:**  2022.3.0-full

**Android version:** 12

**Phone model:** Galaxy S21 5G

**Home Assistant version:** 2022.3.5

**Last working Home Assistant release (if known):**

**Description of problem:**
HA working both from my phone and from desktop via browser without any problem. I have  installed HA to may Galaxy Watch 4.
 It worked well there too. 

After this I bought SSL cert and installed it to my HA server. I can reach HA both from my phone and my from my desktop via browser, but it is not working from my watch.  I have tried both from the Android Companion and  directly on my watch enter the new https based address of my HA.  I always getting the couldn't connect error message.  

I have uninstalled and reinstalled HA on my watch but it not solved the problem.  Strangely the initially used http based server address even after the uninstall/reinstall process is still there.

After this a configured back my HA to use plain http and  my watch connected again.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
If you are able to login using `http` but not `https` then most likely your android watch does not like the SSL certificate, android can be picky like that. We will need to get the actual error message from the watch in order to troubleshoot here.

 Can you try logging in from the Phone to the watch? Go to Configuration > Companion App > Wear OS and login from there. You'll need to clear data on the watch app for this step to work. This might give us more logging and the actual failure as well.

**Comment by wladikazoltan** [comment]
Hi, thank you for the hint.  :-) I have deployed the correct bundle cert 
and it solved the problem.

2022. 03. 15. 18:38 keltezéssel, Daniel Shokouhi írta:
