### ISSUE TITLE
Companion App Shortcut spawns new recent app

### ISSUE THREAD

**Issue by CKerswell** [home-assistant/android#2436]
**Home Assistant Android version: 2022.3.0-full**

**Android version: 12**

**Phone model: Samsung Galaxy S20 5G**

**Home Assistant version: 2022.2.9**

**Last working Home Assistant release (if known): N/A**

**Description of problem: When launching the app from a shortcut, a new copy of the app is displayed in recent apps.  In trying to ensure the phone does not kill the app in the background, I have selected "Keep Open" from the options in recent apps.  This now means that every time I launch the app from a shortcut, it creates a new, locked, copy in my recent apps. **

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs): N/A**

```

```

**Screenshot of problem:**
![Screenshot_20220407-000203_One UI Home](https://user-images.githubusercontent.com/70297519/162087395-37a39d3d-609b-4d9b-b5b0-1d41a540befa.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
This looks like launcher behavior, rather than app behavior as we had another user with the same issue on a samsung device as well.  Can you try the start fresh steps? 

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by CKerswell** [comment]
Thanks for your prompt reply.

I use Nova Launcher, tried switching to the default Samsung launcher and experience the same behaviour.

Also tested a fresh install on a Xiaomi Mi5 using Android 8 and exhibits the same behaviour, so it does look to be app related as opposed to device related.

**Comment by dshokouhi** [comment]
I remember now why we chose to go this route. The app creates a new activity to always ensure that the new shortcut will load. Without this the app can at times not load the correct path because its attempting to reuse the activity when we want to force a new one to ensure it loads as expected. So this is not a bug but an actual feature that the app is using.  We had fixed a bug that occurs when a user has multiple shortcuts with a mixture of dashboard and entities. Without the flag for multiple tasks at times the shortcut just wouldn't work.

https://developer.android.com/guide/components/activities/recents#flag-new-doc

**Comment by CKerswell** [comment]
Thanks again for the detailed response and informative link.

It looks like it would be possible to retain both behaviours by using a combination of android:documentLaunchMode / finishAndRemoveTask() / android:maxRecents.

I can't spot any of these being used currently in the code?

Can this be turned into a feature request to clean up the Recents screen?  I am afraid I have zero experience with developing mobile apps so is probably not something I would be able to directly help with, but happy to provide user input / testing / coffee to anyone who could help!

**Comment by dshokouhi** [comment]
> It looks like it would be possible to retain both behaviours by using a combination of android:documentLaunchMode / finishAndRemoveTask() /

`finishAndRemoveTask()` will not work here because the same activity is used when the app is launched and there are other places that open webview instead of just the shortcuts.  Also it needs to be called from an activity but shortcuts launch activities, they are not an activity themselves.

> android:maxRecents.

This does not work, I tested it myself and it does not respect this value

None of the options are viable for us here, as this activity is a webview activity we have things to workaround some of the odd quirks when it comes to multiple shortcuts.  The only option that may be viable would be to exclude the screen completely from recents but I also suspect that wont be nice.

**Comment by zhimsel** [comment]
> The only option that may be viable would be to exclude the screen completely from recents but I also suspect that wont be nice

For me, this is exactly how it works. When opening a shortcut from the home screen, no entry in the "recent apps" list appears. Which means if I open a shortcut then switch to another app, I can't switch back to the activity opened by the shortcut. I have to open it from scratch again from the home screen. This doesn't seem like desired behavior.

Did something change in the HA companion code since this comment was made? Or is there a setting I have set incorrectly (either in HA or Android)?

For reference, I'm using a Pixel 5 on Android 13 with Nova Launcher.

I haven't tried in the Pixel Launcher, but I can do that now.
