### ISSUE TITLE
Home assistant web card shows "Graphics is not supported" when using Google charts

### ISSUE THREAD

**Issue by aghuie** [home-assistant/android#2438]
Home Assistant Android version: 2022.3.0-full
Android version: 12, SP2A.220405.004
Phone model: Pixel 6 Pro (also an issue on Samsung Z Fold 3, Pixel 4 XL)
Home Assistant version: 2022.4.0
Last working Home Assistant release (if known): Been broken for a few months, not sure which version it last worked
Description of problem:

Web card with a webpage using google charts does not work correctly in Android app (regression) but used to work in past releases (sometime in 2021). Web card works correctly when viewing Home Assistant from Chrome browser (desktop and android).

Screenshot of problem on Home Assistant app
![Screenshot_20220407-160239_Home Assistant](https://user-images.githubusercontent.com/15203933/162333455-6a0d6d37-39c4-4bce-9d50-355ed8a074e5.jpg)

Screenshot of it working from Chrome Browser using web version
![Screenshot_20220407-160303_Chrome](https://user-images.githubusercontent.com/15203933/162333452-e1580d16-c71c-4900-ac4e-2fc6fb8e2fdc.jpg)

**Comment by dshokouhi** [comment]
This issue seems to be missing the issue template, please copy it from a new issue and fill it out completely so we can help. All requested information is important.

**Comment by jpelgrom** [comment]
I've been able to replicate this by embedding the example chart from the docs [here](https://developers.google.com/chart/interactive/docs/quick_start) in a webpage (iframe) card. It loads fine in the browser, and doesn't load in the app.

While searching I found this issue, it appears that Google blocks the chart from rendering based on the user agent: https://github.com/google/google-visualization-issues/issues/2209. When using Chrome remote debugging to change the user agent of the app to the default Chrome Mobile user agent it suddenly starts working: 
![image](https://user-images.githubusercontent.com/8148535/162542454-875a2c66-da77-43d6-bac8-be41362cde29.png)

A possible fix might be including the webview's default user agent with along with the app's user agent, although I'm not entirely sure in what order they should be placed and where it is used (for example by HA core)? Maybe someone else knows this? When updating https://github.com/home-assistant/android/blob/6c64b31f7e1e764ec27a25bf39bb67c4ca31759a/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L265 to also include the original UA (`settings.getUserAgentString()`):
```
settings.userAgentString = USER_AGENT_STRING + " ${Build.MODEL} ${BuildConfig.VERSION_NAME} " + settings.userAgentString
```
will result in the following user agent on my Pixel 4a:
```
HomeAssistant/Android Pixel 4a LOCAL-full Mozilla/5.0 (Linux; Android 12; Pixel 4a Build/SP2A.220405.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.79 Mobile Safari/537.36
```
and now the chart renders correctly in the app.

**Comment by dshokouhi** [comment]
So our request for a custom user agent string came from users who had the app being blocked as we were using the default `okhttp` agent string. We decided to make a new one that could also be predictable for users who monitor user agent strings in their own servers. There was probably a couple of bugs/requests around this if you wanted to look into the history of the changes :)

**Comment by jpelgrom** [comment]
Looking back at previous pull requests updating the user agent used by the app, it seems like it is not only to remove `okhttp`, which is a valid request (#1418), but also to use the same user agent everywhere to support a specific user's use case (#1776). 

The possible fix I mentioned will break that usage of the same user agent everywhere, because including the webview user agent when executing calls using okhttp is not desirable. At the same time, not including any regular browsers in the webview user agent like websites might be used to also is a bit unusual considering default user agents often mention 4 different browsers.

I'm not sure what the best approach is here, but I'm leaning towards appending an indication that the webview is using Chrome similar to the iOS app including Safari: https://github.com/home-assistant/iOS/blob/cd6534b12ce3e1cd30889cd2fcf74cf635ce80b5/Sources/App/WebView/WebViewController.swift#L177. There are more websites using the user agent for feature detection that you might want to embed in a dashboard. This would give the app two unique user agents. I will do some additional testing to see if it still solves this issue and will report back.

**Comment by dshokouhi** [comment]
I think its reasonable to append the webview string here for better compatibility. Cleaning up the user agent string is fine as long as we stick to the same data being sent as we need to be careful about sensitive data. We should just make sure to mention it as a breaking change for those who may need to update things on their end.

**Comment by jpelgrom** [comment]
I've opened a PR to update the user agent and include the original webview one in the webviews. @aghuie Could you try a test version of the app from [here](https://github.com/home-assistant/android/actions/runs/2141746807) (you must be logged in to download, use the file 'app-full-debug.apk') and check if the graphs load correctly for you now?

**Comment by aghuie** [comment]
Thanks for making the update. The test version of the app is working with
the website now.
