### ISSUE TITLE
Add a sensor for high_accuracy_update_interval

### ISSUE THREAD

**Issue by Mincka** [home-assistant/android#2485]
**Is your feature request related to a problem? Please describe.**
We are now able to update the high_accuracy_update_interval remotely thanks to #2356. Thanks again for this, it's working great. :)
However, we don't know the current value so we can't tell if the value was modified locally or if the latest remote update failed.

**Describe the solution you'd like**
A dedicated sensor to get the current value of high_accuracy_update_interval 

**Describe alternatives you've considered, if any**
None. To be honest, I don't have a specific use case. The idea is just to have the ability to reflect the state of something that can be set either locally or remotely. For instance, we can enable or disable high accuracy with a command, and there is a sensor to return its state because it can be changed in different contexts. I can tell that's useful in this case because I have a retry logic in my automations if the mobile app does not return the updated value.

**Additional context**
From a UX point of view, I think it would be strange to have the high_accuracy_update_interval as a parameter of the "Background location" sensor AND a dedicated sensor that would reflect the same thing. If this sensor is implemented, maybe it would require a little bit a work around this.

Now there is a command, I think it would be better to move the parameter from "Background location" sensor because:
1. this attribute is hidden when background location is off
2. this attribute is disabled when high accuracy is off

But in both cases it can still be changed by the command remotely (which is great and useful). But I am a bit puzzled by the fact that the user cannot always see it. The parameter would be with its own sensor that could be either enabled or not like the others.

**Comment by jpelgrom** [comment]
Reading this issue after looking at the linked PR, and I have some thoughts about "additional context".

Splitting high accuracy mode from background location could be a good idea to provide two distinct options (background location tracking and foreground location tracking) that are easier to understand for the user. This would reduce the number of visible settings and keep setting + state in one place, which might make it easier to understand.

At the same time, background location isn't actually a sensor but a device tracker, so it is already out of place. High accuracy mode also affects the background location. No visible attributes/settings in the app already happens for other commands (for example, persistent connection). Splitting the option creates even more questions: should we now provide two device trackers, how to handle attributes for trackers, ... 

I'm also thinking about future location tracking features, like only reporting zones instead of coordinates (like on iOS), or using another source like beacons or WiFi networks, which will raise similar requests and questions when commands are available to control their settings. Should those options be added to background location, or additional 'sensors'/device trackers? Should each option get additional sensors or should there be a 'location tracking' sensor with all information as attributes? 

I don't know the solution, location tracking is complicated, perhaps it is best to leave it as it is when adding a single sensor right now 🙂

**Comment by dshokouhi** [comment]
> At the same time, background location isn't actually a sensor but a device tracker, so it is already out of place.

Yea all location sensors are just a sensor so users can pick and choose the logic for the tracker. It was decided to make it a sensor because the logic was already there but also we needed the location updates to be part of sensor updates to ensure that location tracking is still registered. So they are out of place but they still need to have some of that shared logic to perform checks. For example if we were no longer registered for updates the checks would re-register on the next update.



> should we now provide two device trackers

this would require a change to the `mobile_app` integration

At the moment each device gets 1 device tracker, personally I think keeping location update logic in separate sensors make sense so users can ultimately control how often and when things happen. A lot of the changes done until today were done to help with making location tracking more accurate and reliable.  There has been quite the history of issues and fixes if you look at when things just got started :)

We could always change how users enable location tracking in the app and move it out of Manage Sensors so its in a better location visually. I think that when it comes to making changes we should add them in a way that users who like the current setup can keep it the way that it is. Adding separate sensors for the logic of the device tracker can eventually be used to add location tracking to the minimal version. Some users on the full version may also opt to use that logic like if we were to mark a user as `home` when connected to home wifi via #620.

In the long run, we also need to think about what sane default options would be too, most people would want updates to happen as fast as possible while also being battery friendly which I feel the current default does really well (but can always be improved upon!).

I think its ok to accept these requests from users to turn certain settings into a sensor. I don't think every setting should be a sensor but our users are really good at pointing out use cases we didn't think about.
