### ISSUE TITLE
Notifications are not showing up in lockscreen on specific scenario

### ISSUE THREAD

**Issue by thomasgermain** [home-assistant/android#2503]
**Home Assistant Android version:**  2022.3.0-full

**Android version:** 12

**Phone model:** Oneplus 10 pro (NE2213)

**Home Assistant version:** 2022.4.7

**Last working Home Assistant release (if known):** 2022.4.7

**Description of problem:**
HA notifications (and only HA notifications) are not showing up in lockscreen on specific scenario.

I have all the tracking sensors on (and so high accuracy). The high accuracy comes with a permanent notification.
Other notifications behavior sounds to only depend on how the "high accuracy" notification is configured:
- no high accuracy check (so no "high accuracy" notification) -> notifications are showing on lockscreen
- "high accuracy" notification present and configured in silent mode -> **no** notification on lockscreen
-  "high accuracy" notification present and configured in normal mode -> notifications on lock screen 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
The app doesn't really control which notifications are shown on your lock screen. Some things to check:

- The high accuracy mode notification should use a separate notification channel from your other notifications. However, it sounds like changing the settings for the high accuracy mode notification also affects other notification channels. Are you sure you've changed the right channel, and not all channels?
- In your phone settings, there should be an option to control which notifications are shown on the lock screen. On my device I can choose default+silent, default or none - make sure you've selected the right option. 

If that doesn't help, can you give an example of "other notifications" (for example, the YAML code or details from the app's notification history)?

**Comment by thomasgermain** [comment]
I confirm I'm changing the right channel. In french, it's "Localisation de haute précision", so it should be something like "High accuracy location".

My settings are correct (I believe), since other notifications (from other apps) are showing on lockscreen accordingly to what I configured.


> If that doesn't help, can you give an example of "other notifications" (for example, the YAML code or details from the app's notification history)?

By other notifications, I meant notifications from other app.

In order to test, I simply used the dev tools -> service. Here is an example (don't think it's relevant):
```yaml
service: notify.mobile_app_thomas
data:
  message: "Test message"
  title: "Test"
```

I'll try to clean data or install/uninstall the mobile.

**Comment by dshokouhi** [comment]
This is not app behavior but more device behavior, the app can only create notification channels and after that is on the user to adjust the settings on their device for how they see fit. I see that One Plus offers a help guide on this so may  be this is of help. I don't think we can accept this bug personally as we simply don't have control over this.  On my pixel for example there is a notification channel setting option for Lock Screen which allows me to control which channels can show on the lock screen. It is up to a manufacturer on how they want to implement these features and what to call them. Apps can only set initial channel data but users are ultimately in control.

https://www.oneplus.com/support/answer/detail/op328

**Comment by jpelgrom** [comment]
Adding to @dshokouhi 's comment: we cannot affect the appearance of notifications from _other apps_.

If changing the appearance of Home Assistant notifications also changes what notifications from other apps are visible, this is either an option you should be able to control in system settings or a bug in OnePlus's version of Android.

**Comment by thomasgermain** [comment]
I can reproduce:

1) activate high accuracy mode (either by turning it on manually or via notification command)
2) turn if off **via notification command**:
```
service: notify.mobile_app_thomas
data:
  title: turn_off
  message: command_high_accuracy_mode
```
3) Here, it depends on "something"
3a) high accuracy is turned off -> notifications are working as expected
3b) high accuracy **in android HA app** is  off (the checkbox is unthick), but at phone level this is still active: I have the localisation icon in my taskbar and the HA high accuracy notification is still there -> HA notifications are not showing in my lockscreen. If a deactivate the high accuracy via the action in the notification, notifications are working again as expected.

I also tried with beta-2300-f33743dc-full, but same results.




> Adding to @dshokouhi 's comment: we cannot affect the appearance of notifications from _other apps_.

I'm only speaking for HA notification, all other notifications from all other apps are still working as expected.

**Comment by jpelgrom** [comment]
If you're sending the on/off commands only 10 seconds after another, it is possible that they are received by your device at the same time or even out of order due to power saving. Unfortunately I am not able to reproduce it on my device, could you use the notification history in the app to check this? High accuracy mode being active while the toggle is off still shouldn't happen, but maybe there is a race condition here.

(Also, for your use case the [request location update command](https://companion.home-assistant.io/docs/notifications/notification-commands#request-location-updates) might be a better fit.)

Other HA notifications not being visible while high accuracy mode is on still sounds like a device setting/bug to me, sorry.

**Comment by thomasgermain** [comment]
I agree that 10 sec is maybe too short.

I did some tests: I'm sending turn_on and turn_off "randomly" (between 5 and 20sec) and the history is good, but I was home on wifi, so yeah, it might be another story on 4G while moving.

At the end of the test, high accuracy is supposed to be off, but I found something really interesting:
- in the app, the check box was unthick (so high accuracy supposed to be off)
- On my phone, the high accuracy was actually on
- On HA, it the sensor was also on (same as the phone).

At this point, I'm not able to turn off the high accuracy via notification command. I have to go to the app, tick and untick the box to effectively turn it off everywhere (HA, android app and phone)

**Comment by dshokouhi** [comment]
I see we are starting to talk about 2 separate issues. Lets make sure we fill separate issues for the high accuracy one still being enabled as that is not the same as the original bug. Mixing up 2 bugs means we will lose track of one bug.

When you perform these tests can you also look at the companion app logs to see what is going on there? We print as much as we can to look at the logs and make sure things behave properly so that may be of some help.

At the end of the day if the device is receiving the notification and just not displaying it properly that still points to a device issue and not an app issue.

I think that you also may want to look at the location troubleshooting guide, you should not be enabling high accuracy just to get a quick update like that. Sounds more like you want to follow the guide and make settings adjustments to better fit your scenario.

https://companion.home-assistant.io/docs/troubleshooting/faqs/#device-tracker-is-not-updating-in-android-app

After you check the steps then continue down to the logs section and look at the logs to see if you need to adjust any location settings.

**Comment by dshokouhi** [comment]
Closing due to lack of response
