### ISSUE TITLE
command_screen_off for turn off device screen

### ISSUE THREAD

**Issue by Anton-Ka** [home-assistant/android#2520]
I ask you to clarify whether it is possible to use the command to turn off the screen `command_screen_off` (or similar), similar to the notification command `command_screen_on` companion app for Android?

**Comment by jpelgrom** [comment]
Based on a quick search, there doesn't really seem to be a reliable way to do this other than becoming a device administrator app, and I'm not sure that is desirable ([reference](https://developer.android.com/reference/android/app/admin/DevicePolicyManager#lockNow())).

**Comment by dshokouhi** [comment]
I agree we definitely do not want to do any device admin stuff because if we crash during the action we may not be able to lock the device or leave the device in an unsecure state. Its best that users adjust their screen time out setting and rely on that instead. I will close this issue unless we can find another method to turn off the screen that does not require device admin permissions.
