### ISSUE TITLE
Recognize ethernet as Home Network

### ISSUE THREAD

**Issue by 5A52** [home-assistant/android#2532]
**Is your feature request related to a problem? Please describe.**

I use samsung phone as a phone and Desktop PC, and if it is connected to WIFI (undocked) it uses internal HA url. But When it is connected to ethernet (docked, same network bridged to wifi) app swiсhes to external HA url.

**Describe the solution you'd like**

Add a checkbox to recognize (or not) ethernet as a home network

**Describe alternatives you've considered, if any**

Checkbox or any other option, at least possibility to add "eth0" to list of home wifi networks

**Additional context**

Not only phones with docking possibilities, different android devices are able to use ethernet port.  I am attaching a screenshot of similar functionality implemented in "FolderSync" syncronization app.
![Screenshot_20220516-162547_FolderSync Pro](https://user-images.githubusercontent.com/65124087/168592787-c4d9f274-d1d6-4f7e-bf2f-ae3c251ce251.jpg)

**Comment by marazmarci** [comment]
I think the ideas described in #3480 can be relevant here, as for Ethernet, there's no equivalent single network identifier that is similar to a WiFi access point's BSSID and is available through the Android API. So in case of an Ethernet connection, using the IP range can be our only information to rely on, maybe? 🤷🏻‍♂️

**Comment by marazmarci** [comment]
But note that using IP ranges to detect the home network can be a security concern if the HA server uses HTTP on the LAN.

**Comment by dshokouhi** [comment]
I think for ethernet we can probably use NetworkInterface API to pull the hardware address to properly determine it?

https://developer.android.com/reference/java/net/NetworkInterface#getHardwareAddress()

**Comment by marazmarci** [comment]
Yeah, but you cannot expect a device with Ethernet to be stationary (I mean not mobile).

For example a user may move from place to place and connect to Ethernet at multiple places, to different networks.

**Comment by 5A52** [comment]
> I think the ideas about IP ranges described in #3480 can be relevant here, as for Ethernet, there's no equivalent single network identifier that is similar to a WiFi access point's BSSID and is available through the Android API. So in case of an Ethernet connection, using the IP range can be our only information to rely on, maybe? 🤷🏻‍♂️

In case of checkbox "use ethernet" I think it is inought to check if internal url is online, and if not use external.

> Yeah, but you cannot expect a device with Ethernet to be stationary (I mean not mobile).
For example a user may move from place to place and connect to Ethernet at multiple places, to different networks.

My device with Ethernet is not stationary, if I connect it to ethernet outside homenetwork, is it a security concernIt if it will try to access (ping?) homeassistant.lan?

**Comment by marazmarci** [comment]
@5A52
> My device with Ethernet is not stationary, if I connect it to ethernet outside homenetwork, is it a security concernIt if it will try to access (ping?) homeassistant.lan?

If you use HTTP (not HTTPS) for your LAN connection - which is true for almost everyone, and you mentioning your `homeassistant.lan` local domain name also indicates this about your setup - then I think **yes, it is a security concern**. The reason is that the app doesn't validate the server's identity before connecting to it, and since an attacker controlling a network can easily pose as `http://homeassistant.lan`, they can steal the session token when the app connects to the malicious server.

However, I'd note that this is a fairly unlikely scenario, since not much Android devices have Ethernet or are used with a USB Ethernet adapter, especially at multiple locations, and one of those locations needs to have a malicious server set up in order to steal HA session tokens.

And sorry for not responding to your question earlier, I somehow missed the email notification.
