### ISSUE TITLE
still getting updating sensor notifications while all sesnors are disabled

### ISSUE THREAD

**Issue by kinghat** [home-assistant/android#2605]
**Home Assistant Android version:**
2022.6.0-full
**Android version:**
11
**Phone model:**
pixel 2 xl
**Home Assistant version:**
HA Core 2022.5
**Last working Home Assistant release (if known):**

**Description of problem:**
i have all the sensors disabled and i get "updating sensors" every time my screen comes on after the last update to the android app.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
On Discord you mentioned that [you were using Home Assistant 2022.6.5](https://discord.com/channels/330944238910963714/562408603345092636/985260031933026394).

For Home Assistant 2022.6 and newer, it is expected that the app shows "updating sensors" because it will try to keep them in sync with the server. Even if you've disabled all sensors in the app, it still needs to sync because you might have enabled one on the server and the app wouldn't know otherwise.

**Comment by kinghat** [comment]
> On Discord you mentioned that [you were using Home Assistant 2022.6.5](https://discord.com/channels/330944238910963714/562408603345092636/985260031933026394).
> 
> For Home Assistant 2022.6 and newer, it is expected that the app shows "updating sensors" because it will try to keep them in sync with the server. Even if you've disabled all sensors in the app, it still needs to sync because you might have enabled one on the server and the app wouldn't know otherwise.

i have no integration setup for this phone on the server. i use the app to do everything else in HA not related to the phone.

**Comment by dshokouhi** [comment]
The android app is designed to function with the `mobile_app` integration, in fact that is how the android app gets its tokens and how device registration is stored, etc.... By saying you have no integration for this phone is like saying you don't use the app. You can't use the app without using the integration.

Closing this issue as the reasoning for the update notification was explained up above.

If you really dislike the notification just turn off the notification channel for Sensor Worker.

**Comment by kinghat** [comment]
> The android app is designed to function with the `mobile_app` integration, in fact that is how the android app gets its tokens and how device registration is stored, etc.... By saying you have no integration for this phone is like saying you don't use the app. You can't use the app without using the integration.

i use the app with all sensors disabled and no device integration to get the same functionality one would from managing via a browser. how is that not using the app? why is it unreasonable to think that someone wants to access and manage HA from a native mobile app vs mobile browser but doesnt want to integrate the device into HA?

> If you really dislike the notification just turn off the notification channel for Sensor Worker.

this is an ok solution if it prevents the app from using any resources via background processes trying to communicate with the server.

**Comment by dshokouhi** [comment]
> why is it unreasonable to think that someone wants to access and manage HA from a native mobile app vs mobile browser but doesnt want to integrate the device into HA?

Because in order for the app to even login the app creates a `mobile_app` integration.

The app uses sensors, widgets, notifications and lot of other android integration features all of which depend on the `mobile_app` integration.  If you don't need any of those then there is no need to use the app and you should be using the browser.



> if it prevents the app from using any resources via background processes trying to communicate with the server.

That is not the purpose of the app, as explained before the app will be checking into the server to find any enabled sensors server side so teh app can actually enable them.  Otherwise the feature will not work.

**Comment by jpelgrom** [comment]
A possible alternative if you want an app-like experience without the integration: if you use the 'Add to Home Screen' option in the browser, Home Assistant will basically function like an app instead of a website in the browser.
