### ISSUE TITLE
Support Cloudflared Zero Trust protected instance from App

### ISSUE THREAD

**Issue by kingamajick** [home-assistant/android#2650]
**Is your feature request related to a problem? Please describe.**
I use Cloudflared Zero Trust to protect my Home Assistance. To access my Home Assistant instance, I have to log in using oAuth. When I do this via the Home Assistant app, the process ends in Chrome rather than the Home Assistant App. 

Actual Results:
1. Open HA App
2. App opens Chrome to login to Zero Trust
3. After login, HA is shown in Chrome,

**Describe the solution you'd like**
1. Open HA App
2. Zero Trust login shown in HA App
3. After login, HA is shown in HA App

**Describe alternatives you've considered, if any**
Zero Trust also supports [Service Tokens](https://developers.cloudflare.com/cloudflare-one/identity/service-tokens), an alternative could be to allow custom headers to be attached to requests (this could potentially allow for a solution to other providers).

Another alternative is to use warp for login, buy this isn't feasible on my corporate phone.

**Additional context**

**Comment by marazmarci** [comment]
I like this idea! 👍

However, a problem came to my mind:
A Cloudflare Zero Trust session can last 1 month at most, see the documentation [here](https://developers.cloudflare.com/cloudflare-one/identity/users/session-management/).
When the session expires, suddenly the app will start to silently fail, and you won't get push notifications. That could be unpleasant at times when you want to be notified about some important smart home event.

**Comment by jpelgrom** [comment]
Isn't this the same as #1438, just with a different service? Or am I missing something?

> When the session expires, suddenly the app will start to silently fail, and you won't get push notifications.

This won't be a problem for most users because push notifications are delivered using Firebase.

**Comment by kingamajick** [comment]
Seems I searched for `Cloud flare` rather than `Cloudflare` when looking for previous issues :facepalm:

**Comment by momelod** [comment]
I have the same setup and use Cloudflare Zerotrust to protect my home-assistant.  I got this to work by only protecting the auth subfolder `auth/authorize`. I've been using it for some time and everything has been working flawlessly until today when I tried logging in from a new device. On the new device I see the same aforementioned useragent error, meanwhile my old device continues working with out issue.

**Comment by momelod** [comment]
After disabling ZeroTrust and authenticating on the new device it works. After the device has been authenticated I can re-enable ZeroTrust and everything continues to work just like it has on my original device. 

Hope that helps

**Comment by ported-pw** [comment]
I have a small addition to make: It works fine in the initial setup, seemingly using an internal WebView to display the auth prompt and it completes. Once the token expires or is revoked, I get redirected to the default web browser, where I then do not get redirected back into the app.

**Comment by ported-pw** [comment]
@kingamajick I would reclassify this as a bug, as it seems to be intended to work. It also works fine on iOS.

**Comment by dshokouhi** [comment]
> @kingamajick Maybe you could reclassify this as a bug, as it seems to be intended to work. It also works fine on iOS.

this is not a bug, the feature is just not supported yet.

**Comment by burnski666** [comment]
Here to give this a bump with same problem. Redirected from the CloudFlared git: https://github.com/brenner-tobias/addon-cloudflared/issues/287#issuecomment-1366551953

**Comment by spacebares** [comment]
Having the same issue. Have to delete the app and reinstall every month.
Why does initial setup work fine? Why cant it just open external links in the app instead of chrome?

**Comment by Meister1977** [comment]
I tried to add this, but I am not a kotlin expert, so I gave up after 6 hours, but maybe I will try again. What I would like is to add the 2 request headers to all http calls to the home server.

**Comment by dominicusmento** [comment]
> > @kingamajick Maybe you could reclassify this as a bug, as it seems to be intended to work. It also works fine on iOS.
> 
> this is not a bug, the feature is just not supported yet.

Definitely a bug: either the bug is that 3rd party login is working on the initial setup, or the bug is that it is not working afterwards.. So the app is not consistent in its behavior and please fix this..

**Comment by kingamajick** [comment]
Would a possible solution here to move to a [Trusted Web Activity](https://developer.chrome.com/docs/android/trusted-web-activity/quick-start/) rather than a webview, which would keep the same full screen experience, but have the advantage of sharing the chrome cookie jar, which would work for cloudflared, and anything similar.

**Comment by Meister1977** [comment]
To be honest, I implemented this to a forked branch, but in an uncomplicated way, only for myself. I cannot work with kotlin and with fronted, so I had to hardcode the two header values.

In the 
change this:
```
                it.request()
                    .newBuilder()
                    .header(USER_AGENT, USER_AGENT_STRING)
                    .build()
```

to this:
```
                it.request()
                    .newBuilder()
                    .header(USER_AGENT, USER_AGENT_STRING)
                    .addHeader("CF-Access-Client-Secret","e30ca682391121d19686de801355d588e7c497838d50701024b19551bd370138")
                    .addHeader("CF-Access-Client-Id","54d5121425b629aace75ded10823de32.access")
                    .build() 
```

Of curse, you should use the Cloudflare generated in Cloudflare in the /access/service-auth menu.
You must create a new policy for your app (so you should have 2 policies, one for your email for example), and this new policy should be Service Auth, and the Service Token should be added. 

![image](https://user-images.githubusercontent.com/10465690/223826952-33a07611-7e5e-4ae3-b43e-b024beed35dc.png)

**Comment by Meister1977** [comment]
> FYI next Friday I plan to implement a feature for adding custom headers from the settings UI (I'm an Android developer) 🙂

Ok, if you need help to test. write me directly, I am from Hungary too, so I can help you.

**Comment by panzerknacker20111** [comment]
> FYI next Friday I plan to implement a feature for adding custom headers from the settings UI (I'm an Android developer) 🙂
> 
That would be awesome. I am using Cloudflare + additional Protection layer. And beeing able to use some service tokens for my smartphone would be a huge approvement!

I would realy like to test that out! So if you need an test user just write me.

**Comment by npestana** [comment]
> FYI next Friday I plan to implement a feature for adding custom headers from the settings UI (I'm an Android developer) 🙂
> 
> With this, any authentication method can be used which is based on long-lived tokens, such as Cloudflare Access' Service Tokens.

@marazmarci Hi, did you have the opportunity for such development?

**Comment by npestana** [comment]
I see two possible solutions for this issue here. It would be excellent that official developers allow one of them.

For the use of the Service Settings, we could add an option like “External Connection Headers” after “Internal Connection URL” in the settings.

There are thousands of Home Assistant instances exposed to the Web. This would be a wonderful way to help users to keep access to their self-hosted away, and, not expose to the entire internet.

**Comment by helmbrandt** [comment]
aw man im looking really forward to that feature, at first I didnt understand why it wont work, drove me crazy

**Comment by Meister1977** [comment]
I created a version with this feature.
To be honest, first, you have to set up with your local server, because the settings is under the Server settings, but then, you can use this:
https://github.com/Meister1977/home-assistant-android

The master is created from the original home assistant code.

I built an APK too, but use only if you want to test this, and if you trust me. If it possible, please build your own version.
https://drive.google.com/drive/folders/14m_UiiSpZ0ZNQ_V65JxXvmHsGEssINZ6?usp=share_link

To test:
Open app, go to Settings, Mobile Application, Click on the server name, scroll down to Additional Http Headers.
Enter name1: CF_Access_Client-Id
Enter value1: xxxxxxxxxxxxxx.access (copy from Cloudflare)
Enter name1: CF_Access_Client-Secret
Enter value1: xxxxxxxxxxxxxxyyyyyyyyyyyyyyyyy (copy from Cloudflare)

**Comment by marazmarci** [comment]
> FYI next Friday I plan to implement a feature for adding custom headers from the settings UI (I'm an Android developer) :slightly_smiling_face:
> 
> With this, any authentication method can be used which is based on long-lived tokens, such as Cloudflare Access' Service Tokens.

Hi all! @Meister1977, @panzerknacker20111, @npestana, sorry for replying this late, I was struggling to find the time...

On that Friday, I gave this a shot, and unfortunately, I concluded that there's one big blocker that prevents implementing the custom HTTP headers feature (without [frontend](https://github.com/home-assistant/frontend) modifications). While you can easily add headers to an `OkHttpClient`'s HTTP requests, the problem is that Android's `WebView` doesn't allow adding arbitrary headers to all its HTTP requests. (See the technical details at the end of my comment)

(FYI for those who don't know: the `WebView` is used for displaying the frontend, just like if you opened your HA instance in your browser. For everything else, an `OkHttpClient` is used: sensor updates, widget controls, device controls, quick setting toggles, and persistent connection, so basically everything that happens when the app is in the background, and there may be other things I didn't list.)

However, it's possible to only add the custom headers to the `OkHttpClient` (just as @Meister1977 did it in #3510), and let the `WebView` "do its own authentication", so you get a CF login screen inside the `WebView` where you can log in with your email address and copy-paste the 6-digit code you received in e-mail. You cannot use Google or Facebook to authenticate, because they both prohibit logging in from a `WebView`. Currently, because of this very issue (#2650) I'm writing the comment on (and #3205 is also related), **you can log in when you set up the app**, but when your **session expires** (1 month is the maximum session duration CF Access allows you to set), you will be redirected to a browser, and **cannot authenticate CF Access** for the HA app, and AFAIK the only solution in this state is to clear the app's data and set it up again.


Technical details:
See [`WebViewClient::shouldInterceptRequest`](https://developer.android.com/reference/android/webkit/WebViewClient#shouldInterceptRequest(android.webkit.WebView,%20android.webkit.WebResourceRequest)). If you want to modify the `WebView`'s HTTP requests, you have to make the HTTP request yourself from the application code, with eg. using an `OkHttpClient`, but the `WebViewClient` API won't give you the request body, which makes it practically useless for `POST` requests, because those almost always have a body. Not to mention WebSocket requests, as they're 100% not interceptable, and there's currently no Android API for them.

**Comment by Meister1977** [comment]
@marazmarci : No, you missunderstood my solution. Please see https://github.com/home-assistant/android/issues/2650#issuecomment-1460754065,  because with the headers you can add "service tokens". You can use this kind of tokens for years. So, in this case you never be asked for reauthenticate with google or facebook. The token is generated once in Cloudflare.

**Comment by marazmarci** [comment]
Yes, I did exactly that :smile:

In your PR #3510, the Service Token will only be used by the `OkHttpClient`, not the `WebView` (as I wrote above, it even lacks the ability to add custom headers). And in the `WebView`, you still have to authenticate via SSO, that will eventually expire. Try to set the application timeout to 15 minutes.

**Comment by marazmarci** [comment]
I think I found the problem. I had the `Enable Binding Cookie` setting turned **on**. When I turned it **off**, I was able to authenticate in the browser, and when the session expires, it shows the `Unable to connect to Home Assistant. ... Retrying in xx seconds...` screen, but when I click on `Retry now`, it magically continues to work without showing the Cloudflare Access login page, and without opening a browser :man_shrugging:

[one.dash.cloudflare.com](https://one.dash.cloudflare.com/) → Applications → \<your HA application\> → Settings → turn off `Enable Binding Cookie`

@spacebares, :arrow_up: this :arrow_up: might solve your problem:
> Having the same issue. Have to delete the app and reinstall every month. Why does initial setup work fine? Why cant it just open external links in the app instead of chrome?

**Comment by spacebares** [comment]
This has gone off the rails. Losing sight of the original problem: When the 1 month token expires, any future attempts at authentication fail. Forcing you to delete Home-Assistant from the phone and reinstalling. Initial Authentication works... just not when it expires.

**Comment by marazmarci** [comment]
@spacebares please read https://github.com/home-assistant/android/pull/3510#issuecomment-1534509652, as it may probably solve your problem.

TL;DR: try turning off the `Enable Binding Cookie` setting for your CF Access application!

**Comment by marazmarci** [comment]
@spacebares please read https://github.com/home-assistant/android/pull/3510#issuecomment-1534509652, as it may probably solve your problem.

TL;DR: try turning off the `Enable Binding Cookie` setting for your CF Access application! (the initial auth should also happen with this setting **turned off**!)

**Comment by ported-pw** [comment]
@marazmarci Yes, of course there's a way to do this with a service token - but that's an entire different topic to the original issue as @spacebares correctly pointed out.  
Not everyone wants to make all their family etc. enter tokens into the app - we want the CF access login screen to appear in-app and work when necessary to follow the normal auth procedure, whether you use email codes or OAuth.

**Comment by marazmarci** [comment]
Sorry guys for causing confusion.
 
 > Not everyone wants to make all their family etc. enter tokens into the app ...
 
Yes, very good point. (I was so fixated on the Service Token way because I knew that when not using Service Tokens, the session will expire, and then sensor updates will stop working, and in case of persistent connection, notifications also, which I really didn't want. Service Tokens will keep these working, even when the frontend needs re-authentication.)
 
What I suggested in my previous comment is I think a potential workaround that doesn't require code changes. I would really appreciate it if someone would volunteer to try it out with their config! But to be honest, I don't exactly understand why it works. 😅 When you open the app after the session expires, you will be greeted with an `Unable to connect to Home Assistant. ... Retrying in xx seconds...` message. You just have to click on `Retry now`, and poof, you're in. You won't even see a CF login page. And I don't think my CF Access app is misconfigured, as I only changed the `Enable Binding Cookie` setting, and while it was enabled, I could 100% reproduce the original issue (being redirected to the browser infinitely and having to reinstall the app)

**Comment by EricMedina024** [comment]
Just leaving this comment about my zero trust setup here in case it is helpful to anyone: https://github.com/home-assistant/android/pull/3593#issuecomment-1597693594

**Comment by acelinkio** [comment]
@EricMedina024's above solution is an insecure workaround by passing credentials information via URL. https://owasp.org/www-community/vulnerabilities/Information_exposure_through_query_strings_in_url


The HomeAssistant developers have shown no interest in supporting additional authentication options.   https://github.com/home-assistant/architecture/issues/286#issuecomment-1085199740 Any solutions will be hacks rather than full integrations.  As seen in the above comments, a member began to mark this as a duplicate.  https://github.com/home-assistant/android/issues/2650#issuecomment-1171316619  


This topic has been approached multiple times recently, but ultimately is shut down.  References:

- Community Solution Proposal, punted to forums: https://github.com/home-assistant/architecture/issues/832#issuecomment-1328052330
- Related forum post, crickets: https://community.home-assistant.io/t/open-letter-for-improving-home-assistants-authentication-system-oidc-sso/494223
- PR for LDAP support, shut down: https://github.com/home-assistant/core/pull/37645#issuecomment-729720724
- PR for ProxyAuth support, shut down: https://github.com/home-assistant/core/pull/38175#issuecomment-704216357
- PR for OIDC support, shut down: https://github.com/home-assistant/core/pull/32926#issuecomment-890898052


The community is willing to create add-on, but it does require some amount of engagement for smooth implementation. If the developers could respond these authentication proposals and provide an approach for the community to build towards that would go a long way.

**Comment by EricMedina024** [comment]
> @EricMedina024's above solution is an insecure workaround by passing credentials information via URL. https://owasp.org/www-community/vulnerabilities/Information_exposure_through_query_strings_in_url

I'm definitely open to improvement but I'd have to disagree that it's insecure. The OWASP link you posted essentially says putting the key in the query parameters is bad because it may be logged somewhere (e.g. http server logs, browser history/cache or as part of a copied URL). This is good advice for most cases, but doesn't really apply here. In order for an attacker to access any of those sources, they would have had to have already breached either Google's actions servers (where the key is stored) or your HA instance. This is not really feasible for attackers for a couple reasons:
1. If someone managed to breach Google, I'm sure your HA instance is the last thing they're interested in
2. In order to breach your HA instance over the internet, they would have to know the key beforehand. Otherwise, Cloudflare would just block all their traffic (thereby preventing any intrusion attempts).

Just as an example, imagine a new zero-day was found in HA's Google Assistant endpoint. If you have this key system in place, the attacker wouldn't even be able to attempt the exploit on your instance (as Cloudflare would block it, preventing it from ever reaching your instance). Without the key system, the attacker can attempt the exploit no problem (as long as their request isn't deemed suspicious by Cloudflare).

Additionally, Google Actions don't allow you to set anything about the requests they send other than the fulfillment URL. That is why I went with query parameters for the key - it's the only choice (as far as I know). The Google Assistant part of my setup is also not something you have to configure if you would rather not, but I'm not aware of a more secure way to allow Google Assistant behind Zero Trust.

It's all about defense in depth. The key isn't the only defense mechanism you should have in place, but it is an additional layer that will help deter attackers.

**Comment by acelinkio** [comment]
A majority of compromises occur through chaining many of these approaches.  https://security.googleblog.com/2023/06/google-cloud-awards-313337-in-2022-vrp.html has several examples where Google bled information information and was able to be exploited.  Is it likely that you would be targeted, naw.  

My main point is that HomeAssistance should enable following best practices and allow for a cleaner way to pass information.   For a project looking to integrate everything together, they have actively go out of their way to avoid supporting industry standard authentication protocol.

**Comment by marazmarci** [comment]
In my opinion, the ultimate solution for this problem is using mTLS client certificates. It is more secure and is already supported by the Android app for some time. (On Wear OS, it's not yet done, but I have plans on implementing it...)

Contrary to popular belief, mTLS is available in Cloudflare's Free plan :slightly_smiling_face:

**Comment by wojciszpl** [comment]
> In my opinion, the ultimate solution for this problem is using mTLS client certificates. It is more secure and is already supported by the Android app for some time. (On Wear OS, it's not yet done, but I have plans on implementing it...)
> 
> Contrary to popular belief, mTLS is available in Cloudflare's Free plan 🙂

Where it can be find in android app?

**Comment by DarthSonic** [comment]
I had overcome the issues with simple client certificate. Enabled Cf Tunnel and Zero Trost with specific Client Certificate as authorization method. If not avaliable it will fail. App is configured with local IP in Home WLAN and external zero trust enables domain external.

You have to install client certificate on each android device once and select it in first opening of HA app. That's all.

In addition I block all requests without client certificate in Cf WAF. Also only allowing requests from my home country.

**Comment by PPP01** [comment]
> I had overcome the issues with simple client certificate. Enabled Cf Tunnel and Zero Trost with specific Client Certificate as authorization method. If not avaliable it will fail. HA App is configured with local IP in Home WLAN and external zero trust enabled domain for external.
> 
> You have to install client certificate on each android device once and select it in first opening of HA app. That's all.
> 
> In addition I block all requests without client certificate in Cf WAF. Also only allowing requests from my home country.

can you give me a tip on how to implement this in cloudflare? I can't find any authentication with a client certificat at zero trust.

**Comment by DarthSonic** [comment]
1. You need to establish Cloudflared (Tunnel)
2. Then I created Client Certificat (Dashboard > SSL) and stored it locally
3. Then I added a WAF rule (in Dashboard, not Zero Trust) with rule:

`(http.host eq "hass.example.com" and not cf.tls_client_auth.cert_verified and http.request.uri.path ne "/api/webhook/...")`

You need to define your HA Webhook URL here.

4. Now I needed to install that client certificate on each client that requires access to my hass custom domain (find manuals in google for your client os)
5. The first time you request your hass custom domain the OS should prompt for a client certificate that you need to choose. Select you uploaded certificate and you get access.
6. If you change certificate or did something wrong, you need to clear cache of page or HA app to be able to choose new certificate.

**Comment by PPP01** [comment]
Ok, a few grey hairs later ...
Thank you! It works now. For all the others who read this and also have problems:
~~~
# 1. save the certificate to cert.pem and key.pem 
# 2.  test the rule and the certificate
# If this does not work, check the tunnel without an activated certificate. 
curl --cert cert.pem --key key.pem https://hass.example.com
# 3. If curl is successful, then create the client certificate:
cat cert.pem key.pem > pkcs12.pem
openssl pkcs12 -in pkcs12.pem -export -out pkcs12.p12
# 4. import this certificate to your devices
# 5. You can generate separate certificates for each user/device.
~~~

**Comment by ther3zz** [comment]
> 1. You need to establish Cloudflared (Tunnel)
> 2. Then I created Client Certificat (Dashboard > SSL) and stored it locally
> 3. Then I added a WAF rule (in Dashboard, not Zero Trust) with rule:
> 
> `(http.host eq "hass.example.com" and not cf.tls_client_auth.cert_verified and http.request.uri.path ne "/api/webhook/...")`
> 
> You need to define your HA Webhook URL here, if you want to permit access to webhook. Otherwise remove that part of the rule:
> 
> `(http.host eq "hass.example.com" and not cf.tls_client_auth.cert_verified)`
> 
> 4. Now I needed to install that client certificate on each client that requires access to my hass custom domain (find manuals in google for your client os)
> 5. The first time you request your hass custom domain the OS should prompt for a client certificate that you need to choose. Select you uploaded certificate and you get access.
> 6. If you change certificate or did something wrong, you need to clear cache of page or HA app to be able to choose new certificate.

So I've followed your instructions on my android phone but it appears that I'm getting blocked when attempting to access my HA instance.
I've successfully imported the cert using @PPP01 's instructions but my phone never prompts me to select the installed certificate.
Did you happen to do this on an android device as well?

**Comment by DarthSonic** [comment]
> > 1. You need to establish Cloudflared (Tunnel)
> > 2. Then I created Client Certificat (Dashboard > SSL) and stored it locally
> > 3. Then I added a WAF rule (in Dashboard, not Zero Trust) with rule:
> > 
> > `(http.host eq "hass.example.com" and not cf.tls_client_auth.cert_verified and http.request.uri.path ne "/api/webhook/...")`
> > You need to define your HA Webhook URL here, if you want to permit access to webhook. Otherwise remove that part of the rule:
> > `(http.host eq "hass.example.com" and not cf.tls_client_auth.cert_verified)`
> > 
> > 4. Now I needed to install that client certificate on each client that requires access to my hass custom domain (find manuals in google for your client os)
> > 5. The first time you request your hass custom domain the OS should prompt for a client certificate that you need to choose. Select you uploaded certificate and you get access.
> > 6. If you change certificate or did something wrong, you need to clear cache of page or HA app to be able to choose new certificate.
> 
> So I've followed your instructions on my android phone but it appears that I'm getting blocked when attempting to access my HA instance. I've successfully imported the cert using @PPP01 's instructions but my phone never prompts me to select the installed certificate. Did you happen to do this on an android device as well?

Clear browser cache and clear cache of home assistant companion app!

**Comment by ther3zz** [comment]
> > > 1. You need to establish Cloudflared (Tunnel)
> > > 2. Then I created Client Certificat (Dashboard > SSL) and stored it locally
> > > 3. Then I added a WAF rule (in Dashboard, not Zero Trust) with rule:
> > > 
> > > `(http.host eq "hass.example.com" and not cf.tls_client_auth.cert_verified and http.request.uri.path ne "/api/webhook/...")`
> > > You need to define your HA Webhook URL here, if you want to permit access to webhook. Otherwise remove that part of the rule:
> > > `(http.host eq "hass.example.com" and not cf.tls_client_auth.cert_verified)`
> > > 
> > > 4. Now I needed to install that client certificate on each client that requires access to my hass custom domain (find manuals in google for your client os)
> > > 5. The first time you request your hass custom domain the OS should prompt for a client certificate that you need to choose. Select you uploaded certificate and you get access.
> > > 6. If you change certificate or did something wrong, you need to clear cache of page or HA app to be able to choose new certificate.
> > 
> > 
> > So I've followed your instructions on my android phone but it appears that I'm getting blocked when attempting to access my HA instance. I've successfully imported the cert using @PPP01 's instructions but my phone never prompts me to select the installed certificate. Did you happen to do this on an android device as well?
> 
> Clear browser cache and clear cache of home assistant companion app!

Seems to be my config on the WAF side since when I try to nav to "https://ha.example.com/api/webhook", I get the "you have been blocked" page.

This is how I have the expression currently set in WAF:
`(http.host eq "HA.example.com" and not cf.tls_client_auth.cert_verified and http.request.uri.path ne "/api/webhook/")`

**Comment by DarthSonic** [comment]
@ther3zz in Cloudflare you can view a log of the WAF and an exact reason why your request gets blocked. Everything else is just guessing and there are plenty of reasons why you could get blocked.

**Comment by Fabrizz** [comment]
> Ok, a few grey hairs later ... Thank you! It works now. For all the others who read this and also have problems:
> 
> ```
> # 1. save the certificate to cert.pem and key.pem 
> # 2.  test the rule and the certificate
> # If this does not work, check the tunnel without an activated certificate. 
> curl --cert cert.pem --key key.pem https://hass.example.com
> # 3. If curl is successful, then create the client certificate:
> cat cert.pem key.pem > pkcs12.pem
> openssl pkcs12 -in pkcs12.pem -export -out pkcs12.p12
> # 4. import this certificate to your devices
> # 5. You can generate separate certificates for each user/device.
> ```

That worked perfectly for the companion app thanks!
Has anyone encountered problems using mTLS with desktop clients? After adding the client certificate to Windows certificate manager and restarting chrome, it asks me what certificate to use, but it seems to only apply to the firsts calls, then for some reason it stops using the certs. I saw some guides generating the .p12 file using a "legacy" way. Any help appreciated, thanks!

**Comment by Alonzzzo2** [comment]
@PPP01 can you help me out, I don't understand something... so I created the certificate etc. and created a WAF rule, but shouldn't I also create a policy for my app in zero trust? If so, which policy should it be? without a policy, this app will be blocked for everyone... 

Plus, I've installed the certificate on my android device, it is now visible at credentials storage - user credentials, but although I cleared the cache many times, I don't get a popup or anything like that when trying to access the HA app via the tunnel, at the app

**Comment by PPP01** [comment]
I can try:
I have experimented with zero trust, but achieved little that was helpful. Zero trust is not required for the certificate-based login!
My WAF rule looks like this:
(http.host eq "hass.example.com" and (not cf.tls_client_auth.cert_verified or cf.tls_client_auth.cert_revoked))

This means that this domain can only be accessed with a certificate. However, once the certificate has been set up, it's a bit of a hassle until the browser actually uses it. Restarting the browser several times has helped me so far. So it worked under Android, too (i use a pixel 7 pro). Unfortunately, it doesn't work at all on iOS for me.

**Comment by dshokouhi** [comment]
As the PRs that attempted to resolve this has been [closed](https://github.com/home-assistant/android/pull/4160#issuecomment-1927929682) I am going to close this issue now. I will keep it open so the discussion can continue.

**Comment by cziter15** [comment]
I came here as I'm looking for a similar solution. Isn't it good idea to introduce custom HTTP header or User Agent string that can be used as a key that unlocks WAF? It should be relatively simple to implement.

**Comment by Meister1977** [comment]
> Isn't it good idea to introduce custom HTTP header

This is what I implemented in my fork, but HA team rejected my Pull Reuest.

https://github.com/Meister1977/home-assistant-android

**Comment by DarthSonic** [comment]
I am not a fan of that approach as it can simply be faked by anyone. Even if you have a unique string value for the header like a GUID, it can be read by "man on the middle" when you request HA instance. While client cert should be safe for such an attack.

**Comment by cziter15** [comment]
@DarthSonic these headers should go in encrypted HTTPS stream. I don't know about cloudflared implementation details, but when it comes to outside world, the first "firewall" is cloudflare. You can filter user agent and other things because they wrap all the traffic under their SSL cert. I don't know how the tunnel works under the hood, but I can imagine that is also working on top of strong encryption layer.

**Comment by DarthSonic** [comment]
If you connect you companion app non SSL to your HA instance the header will not be encrypted before sending. A trojaner eventually could read that header before it is send to cloudflare. Also you have to trust that the header value is stored encrypted on your phone so no one can read it out of any configuration file.

**Comment by EugeneKrapivin** [comment]
@DarthSonic but in this case a username/password over non-SSL traffic could be sniffed. and if I do MITM I could also capture them over an SSL connection as well as long as there is not mTLS process to verify both sides. Those cases are true for any over the internet interaction. Using APIKey or long-lived bearer tokens is a common practice.

**Comment by Meister1977** [comment]
The app doesn't connect without https. Cloudflare almost always uses https.
If somebody can read your configs, then the same can read your certificates too.

**Comment by trumpton** [comment]
I've a slightly different use-case which would benefit from custom headers, which is:

I would like to add a custom header so that an nginx proxy server I have running on one machine in a DMZ can pre-filter the thousands of spam messages I receive, and only forward messages through a reverse tunnel with a specific header to the HomeAssistant application running on a second machine.

The App produced by @Meister1977 here [https://github.com/Meister1977/home-assistant-android] is almost there, and I can add a location / filter rule based on the additional header which only allows certain requests to pass.

Unfortunately, that fork hasn't quite captured all of the possible requests within the companion app - and requests for these paths don't contain the header:

GET /lovelace?external_auth=1 HTTP/1.1
GET /sw-modern.js HTTP/1.1
GET /?external_auth=1 HTTP/1.1
GET /api/websocket HTTP/1.1

It would be great to see the custom headers in the trunk companion application.

Not holding up much hope for any useful response though :(

**Comment by ericmedina024** [comment]
@trumpton have you considered using mTLS instead? it would be more secure and is supported by the HA app

**Comment by trumpton** [comment]
@ericmedina024 - many thanks for the thought. 

Would I be right in thinking that I'd configure my nginx proxy to force mTLS, and I don't do anything on the HA server at all?
This way, the mTLS magic would go on directly between the companion app and the nginx proxy?

If this is the case, it  would indeed prevent rogue stuff getting through to the HA server.

I understand that Google also support mTLS so I suspect I could also use the same mechanism to restrict Google Assistant access (at the moment, I've told google to add a ?access=my-shared-secret to the end of any query, which I filter for in the nginx proxy).

Steve

**Comment by christerdk** [comment]
> I got this to work by only protecting the auth subfolder `auth/authorize`

I have HA set up as an application in CF Zero Trust, did you protect that path by using a application policy or did you set that up somewhere else?

**Comment by ClaudiuCudla** [comment]
> > I got this to work by only protecting the auth subfolder `auth/authorize`
> 
> I have HA set up as an application in CF Zero Trust, did you protect that path by using a application policy or did you set that up somewhere else?

He mentioned in his later reply that in fact the "disable protection, login, then re-enable protection" was the winning solution.
I use the mTLS solution (https://kcore.org/2024/06/28/using-cloudflare-zerotrust-and-mtls-with-home-assistant-via-the-internet/) and it always works for me. It is with a different domain that I only use for the mobile app, while the others are kept protected with the standard auth methods.
