### ISSUE TITLE
Add possibility to change settings on the phone app from HA

### ISSUE THREAD

**Issue by Hellis81** [home-assistant/android#2656]
**Is your feature request related to a problem? Please describe.**

As the only person in the home who understands HA and smart homes I have to manage all the smart devices that use the app.
It's not hard, not at all. But the issue is that sometimes there are new sensors added, or you realize how to use a sensor that is currently not used.
Let's say you add a ESP32 BLE sensor and want to add presence sensor in HA, but you need to add the BLE settings in all the phones.

On my own phone it's easy to just open the settings and change what I need to add a new sensor that I might use for something. 
But when it's other family members phones you need to ask them to add the sensor or I have to do it.
And it could be an issue to ask for someones phone.

**Describe the solution you'd like**

A control panel where I can change the settings on the phone remotely.
Either this sends a request to the phone owner for permission to change the setting, or it just changes the settings.

I believe this should be a setting on the phone so that the phone owner can set it to always just do all the changes or ask for permission to change.

**Describe alternatives you've considered, if any**

Ask for the phone and change the settings. 

**Additional context**

**Comment by dshokouhi** [comment]
Starting in HA 2022.6 you can enable sensors from HA directly and the app will enable them the next time it does a sensor check.  The user will still need to grant proper permissions depending on the sensor.  

In terms of other sensor settings I don't think we should include them all in a request like this, it makes sense to have separate requests on a case by case basis. Sensors like BLE already have commands and requests in place for the other settings users wish to change, we should continue that process here.

**Comment by Hellis81** [comment]
I can't see where you can edit the settings from HA.
The reason I made the request so broad is because it was meant to be broad.
I see no reason to limit this to one or a few settings. Today one of our phones stopped reporting the location. 
I assume this is due to Android disabling permissions every now and then.

**Comment by dshokouhi** [comment]
> I can't see where you can edit the settings from HA.

Settings no only some of those are done via a notification command. Disabling and enabling a sensor is on the device page in HA core 2022.6 and you also have to wait for the next sensor update for the app to pick up those changes.



> The reason I made the request so broad is because it was meant to be broad.
> I see no reason to limit this to one or a few settings.

It will take more than a single PR to add settings for each sensor, each one should have its own request created so it can be considered on a case by case basis.  When a contributor marks their PR for an issue, github closes it so its best to keep things split up instead of vague so its easier to track. We always ask users to break down their requests and not to combine multiple.



> Today one of our phones stopped reporting the location.
> I assume this is due to Android disabling permissions every now and then.

Correct and the app cannot regrant location permissions from a command or in the backend, that is something the user has to do when that happens.  This also only happens if the user turns off location, on my wifes phone who never uses the HA app location is still always granted because it is used that often during sensor updates.
