### ISSUE TITLE
TTS no longer working after latest update

### ISSUE THREAD

**Issue by ojundi** [home-assistant/android#2667]
Android beta-2478-0883ada4-full

The error message when TTS service is used. PLEASE SET A TITLE FOR TEXT TO SPEECH TO PROCESS

**Comment by ojundi** [comment]
had to remove the app and reinstall.. works now!.. Thanks

**Comment by EnochPrime** [comment]
Feel like this shouldn't be closed as it may effect others when upgrading from a stable version. I had the same issue and clearing cache did not fix it, but clearing the data did. I didn't have to reinstall.

**Comment by dshokouhi** [comment]
I didn't get a chance to respond but there was a breaking change in a recent beta version so the automation needs to be updated.

**Comment by EnochPrime** [comment]
> I didn't get a chance to respond but there was a breaking change in a recent beta version so the automation needs to be updated.

Yes I saw that in the beta change log. After the breaking change I was getting the audio message that the OP wrote even after updating the automation(s) and even reloading all automations (didn't go as far as restarting HA). None of that fixed the TTS which is why I cleared the app data which ultimately did allow it to work as intended.

**Comment by dshokouhi** [comment]
So in your case we would direct you to starting fresh quick would involve clearing data.

https://companion.home-assistant.io/docs/troubleshooting/faqs#starting-fresh-with-the-android-app

Personally I did not experience any issues after updating the app and automations. Sometimes things happen and that's why we have those steps.

**Comment by ojundi** [comment]
I guess i am reopening this issues again.. after upgrading to beta it caused the same issue removing and reinstalling didn't work neither did clearing data and cache!

**Comment by dshokouhi** [comment]
That's because the format changed in a recent update. Please see the docs for the updated format.

https://companion.home-assistant.io/docs/notifications/notifications-basic#text-to-speech-notifications
