### ISSUE TITLE
Last update sensor no longer showing settings on new installs

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#2673]
**Home Assistant Android version:**

latest master

**Android version:**
12
**Phone model:**
Pixel 6 pro
**Home Assistant version:**
2022.3.x
**Last working Home Assistant release (if known):**
Might be before #2585 
**Description of problem:**

On a fresh install the last update sensor settings page is not showing the add new intent button so users can add intents. On an upgraded install with 1 intent registered it does work.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

![image](https://user-images.githubusercontent.com/1634145/178769884-9694492c-de9b-4b4b-95af-9296e490379a.png)

**Additional information:**

Reference: https://community.home-assistant.io/t/last-update-trigger-sensor/438968/

**Comment by dshokouhi** [comment]
@marazmarci FYI in case this was introduced with #2585

**Comment by dshokouhi** [comment]
Fix incoming, just need to add the toggle if we don't need to create a new intent.

**Comment by marazmarci** [comment]
And there's another bug that I discovered recently, but I didn't have time yet to report it:

When there are >10x Intents, the order will change every time there's a sensor update. (It's caused by the alphabetical ordering of the numbers: "Intent 1" > "Intent 10")

And I think it can also cause data loss if the user is editing an Intent and there's an update happening in the background in the meantime, and the user hits save, because it will edit a different item in the list.

**Comment by dshokouhi** [comment]
Oh wow I have not noticed that yet, I only use 2 intents personally haha

**Comment by marazmarci** [comment]
@dshokouhi I created an issue for the aforementioned bug: #2703
