### ISSUE TITLE
Android App Stops Sending High Accuracy Location Updates

### ISSUE THREAD

**Issue by RockDuster** [home-assistant/android#2681]
**Home Assistant Android version:** 2022.6.0-full

**Android version:** 12

**Phone model:** Pixel 4 XL

**Home Assistant version:** 2022.5.5 (Core)

**Last working Home Assistant release (if known):** 2022.5.5 (Core)

**Description of problem:**

With High Accuracy mode enabled for location updates, the HA app at some point stops sending location updates (and accessing location) at the expected frequency (every 5 seconds). I can reproduce this reliably by doing the following:

- Enable High Accuracy mode
- Observe throughout the day that the Android location access icon ([this](https://community-assets.home-assistant.io/original/4X/c/3/b/c3b830ab8fb379f61213edf2ac78955b0f032bc2.png)) is persistent, and location updates are being sent every 5s.
- Go to bed.
- In the morning, the location access icon is gone, and high accuracy location updates are no longer being sent, even though High Accuracy mode is still enabled and the persistent notification for it is present. This continues until High Accuracy Mode is disabled and then re-enabled in the app.

I have already done the following to troubleshoot this:

- https://companion.home-assistant.io/docs/troubleshooting/faqs/#device-tracker-is-not-updating-in-android-app
- https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app
- Disabled "Include in Sensor Updates" for the Single Accurate Location sensor ([on advice from dshokouhi](https://community.home-assistant.io/t/location-updating-doesnt-work-very-serious-problem-for-my-automations/437206/14?u=rockduster))
- Tested the full debug APK from [this fix](https://github.com/home-assistant/android/actions/runs/2664693284), and confirmed the same behavior.

Zone based location updates still appear to function when the app has got into this state, but no other location updates do.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

Here are some app logs. I pulled these when I woke up and found that location updates had stopped, before disabling/re-enabling High Accuracy mode to fix it: [Logs](https://github.com/home-assistant/android/files/9122815/ha.app.logs.txt)

I've also been discussing this with dshokouhi in [this thread](https://community.home-assistant.io/t/location-updating-doesnt-work-very-serious-problem-for-my-automations/437206), who asked me to file this bug.

**Comment by johngianni** [comment]
I report the same problem with Huawei P40 Pro, with google services. I've also gone through the whole discussion in the HA forum, I thank you so much for the time dedicated to this bug @RockDuster. This is happening to me since always. My guess has always been something related to google play services. When my locations updates stop, I open up google maps app and the location updates to HA start working again. Just my 2 cents.

**Comment by dshokouhi** [comment]
If you don't see the log line for received location update, then that means Google is not sending the app updates. This is why we ask to look at the logs so we can see what's going on.

**Comment by dshokouhi** [comment]
Took a crack at this issue, not sure if the fix will work but would appreciate it if you guys can test the debug APK from: https://github.com/home-assistant/android/actions/runs/2764331147

Make sure to grab the full version as that is the one that contains location tracking :)

Basically we are going to keep track of the last location update received. Then when we perform our normal sensor checks we will evaluate if too much time has passed since the last update. If so then the app will restart its location services. A bit of a workaround but its the best I can think of for now. 

🤞

**Comment by johngianni** [comment]
will test. thank you!!

**Comment by ctml91** [comment]
I'm having a similar issue recently. Some of our phones are sporadic with location updates breaking and the automations don't trigger as a result.

For example I went for an hour walk today and location was only updated 30 min into it finally detecting me as away. I have 3 zones, home, neighbourhood, and city each one a bit bigger than it's child. Will location zone sensor affect the background location updates? Should only 1 be enabled? Both have a minimum accuracy of 200. It used to work much better, I think this issue started within the last month or so.

**Comment by dshokouhi** [comment]
> I'm having a similar issue recently. Some of our phones are sporadic with location updates breaking and the automations don't trigger as a result.
> 
> For example I went for an hour walk today and location was only updated 30 min into it finally detecting me as away. I have 3 zones, home, neighbourhood, and city each one a bit bigger than it's child. Will location zone sensor affect the background location updates? Should only 1 be enabled? Both have a minimum accuracy of 200. It used to work much better, I think this issue started within the last month or so.

> 

the best way to confirm you actually have this issue is to look at the companion app logs to see if google is sending you updates or not.

please take a moment to read the documentation and troubleshooting steps, then if the issue still exists reply back with logs.

Describes how location updates work and the purpose of the sensors and its settings: https://companion.home-assistant.io/docs/core/location#android-location-sensors

Troubleshooting to make sure its setup properly: https://companion.home-assistant.io/docs/troubleshooting/faqs#device-tracker-is-not-updating-in-android-app

The troubleshooting steps contain example log output, if you are seeing this issue then you will not be seeing updates from google in the logs.

**Comment by johngianni** [comment]
I've tested the beta app and for me the location updates are too much scarse and unpredictable. Sometimes location is updated every 5 minutes or so, sometimes every 15 minutes... Will try to re-enable the "include in sensor updates" option and see if it improves.

**Comment by dshokouhi** [comment]
> I've tested the beta app and for me the location updates are too much scarse and unpredictable. Sometimes location is updated every 5 minutes or so, sometimes every 15 minutes.

This is actually expected behavior. Please read the logs and see why. If location has not changed we don't send updates for 15 minutes.

> Will try to re-enable the "include in sensor updates" option and see if it improves.

I wouldn't do that.
