### ISSUE TITLE
Companion app not sending sensor updates after an (automatic) app update 

### ISSUE THREAD

**Issue by gitawayu** [home-assistant/android#2683]
With Google Play settings set to auto update apps, after an automatic update of the Android companion app, a HA automation that reports no sensor updates for 8 hours (from the device on which the companion app was updated) was triggered.  Normally the HA automation triggers when the device gets powered off because the battery has drained (not the case this time).

I opened the companion app on the device to investigate whether the sensor permissions had somehow been switched off and it started up with a "what's new" screen that has to be dismissed in order to enter the app.

I did not find anything wrong with the sensor settings.  

I am not sure whether there is an Android "feature" that means that the app is unable to operate normally until a user has manually dismissed the "what's new" screen.  Please just close this bug as "cannot fix", if that is the case!

If the Android companion app could send sensor updates before the "what's new" screen has been manually dismissed, but does not do so, it would be great if this could be fixed, such that it does send sensor updates.

Requiring manual intervention is undesirable: what if the Android device is in a different country and physical access is not possible?

(I have already disabled auto updates in Google Play, but this is more of a workaround).

**Comment by dshokouhi** [comment]
The issue template that gets presented wehn you create an issue is important. In order to get further help please put the template you removed back and fill in all information including the logs.  More than likely some other issue occured but we are missing it as we are missing are requested data.

**Comment by gitawayu** [comment]
Apologies...

**Home Assistant Android version:**
Companion app version is:
2022.6.0-full
(is that the question?)

**Android version:**
9

**Phone model:**
HTC U11+

**Home Assistant version:**
2022.5.5

**Last working Home Assistant release (if known):**
2022.5.5
It *was* working with this version.
Possible that an update to the companion app caused this.  i did not update HA version or the automation, so it's odd that i started getting the "no updates for 8 hours" message.

**Description of problem:**
See original problem description but please note that my theory about it being caused by no updates being sent until the user manually dismisses the "what's new" screen seems to be *wrong*, since this issue has happened again today without any sign of a companion app update.

**Traceback (if applicable)
The logs seem to only cover the past ten minutes.  Presumably I should wait for the problem to occur and then generate a log and add it?
Having said that, aren't we looking for no sensor updates for more than fifteen minutes to show that there is an issue?
The Battery Level update frequency is set to 15 minutes according to the UI, and it's an absence of such updates for 8 hours that triggers the automation.

**Screenshot of problem:**
It's just a text notification generated by my automation as a notify message to another cellphone that says that there were no updates from the U11+ for eight hours.

**Additional information:**
None for now.

**Comment by dshokouhi** [comment]
We still need to see the logs from when the issue occurs. There is an intent the app registers for and I am curious to see if this device is not getting that intent. This could be a device issue.

**Comment by dshokouhi** [comment]
In this case it looks like the worker schedule was killed by the android system or the app had a crash and we need to see the crash log. The worker schedule actually stays retained during device and app restarts which trigger from auto update. My wife is on the beta and never opens her app yet her updates always continue to come in, including after this weeks beta update in the play store.

Double check the app has permissions to run in the background by going to Settings > Companion app and then checking the background access tile. Next time this happens since you have an automation to detect the issue. You can also just use the notification command to update the sensors by sending a notification with `message: command_update_sensors` to the device. This will also start the update schedule again, at least until the next time the system kills the app. If that keeps happening you will want to look into additional settings your manufacturer may have added to let the HA app stay running in the background. dontkillmyapp.com usually has some good tips.

**Comment by dshokouhi** [comment]
Closing due to lack of response
