### ISSUE TITLE
3-fingers gesture (WebViewActivity?) doesnt work anymore

### ISSUE THREAD

**Issue by chertvl** [home-assistant/android#2686]
**Home Assistant Android version:** beta-2478-0883ada4-full

**Android version:** Android 12, OneUI 4.1

**Phone model:** Samsung Galaxy S10

**Home Assistant version:** 2022.7.5

**Last working Home Assistant release (if known):** a long time ago, idk

**Description of problem:** 3-fingers swype down does not work anymore for me (and for my friend with Xiaomi Redmi 8 Note Pro also), maybe problem still present since https://github.com/home-assistant/android/pull/2396
Any non-documented breaking-changes with this coolest feature with last releases? 
I dont know reason.

```

```

**Screenshot of problem:**

https://user-images.githubusercontent.com/38353584/179396514-d865d473-a2df-48ef-812a-4b6a260974f9.mp4

**Comment by jpelgrom** [comment]
After adding some logging, the detection still seems to be working fine for me, but the frontend is no longer responding to the event.

Temporary workaround for some: the toolbar at the top of the screen now also includes a button to open the entity search (in the overflow menu).

**Comment by dshokouhi** [comment]
This feature was originally intended to be a workaround until the frontend provided a way to bring up the dialog on mobile. Now that is present maybe it's time to remove our workaround?

**Comment by jpelgrom** [comment]
This seems to be caused by home-assistant/frontend#12892 - the keyboard event submitted by Android doesn't contain a `code`, only the `key`. 
![Chrome dev tools showing a `KeyboardEvent` with `key: 'e', code: ''`](https://user-images.githubusercontent.com/8148535/179417195-00104389-7657-4b24-91ca-57002a669dcd.png)
Not really in the scope of the app to fix this, or we have to manually trigger the JS event instead but then it's even more of a workaround...

> Now that is present maybe it's time to remove our workaround?

If users hide the default toolbar (like in the video in this issue) they still cannot trigger the quick bar. However, considering this is a choice and the problem mentioned above, I'd agree.

**Comment by chertvl** [comment]
> Remove WebViewActivity quick bar gesture #2690

I hope that we are on the right path. Thank you for the explanation!

**Comment by jpelgrom** [comment]
Discussed it with @dshokouhi in the PR and decided to not completely remove it yet.

Still not functional but the result is the same: the gesture isn't supported on HA core 2022.7.
