### ISSUE TITLE
Quick Tile Features

### ISSUE THREAD

**Issue by guarddog13** [home-assistant/android#2723]
**Is your feature request related to a problem? Please describe.**

It is not. 

**Describe the solution you'd like**

I would like see Quick Tiles have to ability to tell state of the device. It would also be nice to have Quick Tiles vibrate when you press them and to have the option to have them close or not when you press them. 

I would also like to see more "buttons" within one Quick Tile. For example currently I have one Quick Tile that when tapped starts my truck, when double tapped unlocks it, and when held locks it. 

Could also have Quick Tiles trigger Tasker tasks..

**Describe alternatives you've considered, if any**

I use third party apps tied into Tasker to do this. 

**Additional context**

**Comment by dshokouhi** [comment]
> I would like see Quick Tiles have to ability to tell state of the device. It would also be nice to have Quick Tiles vibrate when you press them and to have the option to have them close or not when you press them.
> 
> I would also like to see more "buttons" within one Quick Tile. For example currently I have one Quick Tile that when tapped starts my truck, when double tapped unlocks it, and when held locks it.

this sounds like multiple requests mixed into 1, lets make sure to split things up instead of combining them into the same request.

**Comment by dshokouhi** [comment]
> I would like see Quick Tiles have to ability to tell state of the device.

For this you can already tell by the active state of the device. Otherwise the tile will be off. So if the state is `on` or `open` you can expect it to be active, otherwise it will look inactive.



> It would also be nice to have Quick Tiles vibrate when you press them and to have the option to have them close or not when you press them.

Please split these into 2 separate feature requests. As vibration is not part of the current behavior we will probably make this a setting on a per tile basis. By default the stock tiles do not perform any feedback. Closing the panel is a separate request that will need to be added on a per tile basis, if possible. Looking at the [android docs](https://developer.android.com/reference/kotlin/android/service/quicksettings/TileService#startactivityandcollapse) we need to start an activity to collapse properly so we can't just close it.



> I would also like to see more "buttons" within one Quick Tile. For example currently I have one Quick Tile that when tapped starts my truck, when double tapped unlocks it, and when held locks it.

I don't think this is possible. Android only notifies the app that the tile has been clicked on. We can't differentiate between double clicks or the tile being held.

The long press action you see is reserved to either open the app or open a specific activity, [docs](https://developer.android.com/reference/android/service/quicksettings/TileService.html#ACTION_QS_TILE_PREFERENCES)

**Comment by guarddog13** [comment]
I had an app.. which may have been a Samsung app (via Goodlock) as I can't find it since I switched and uninstalled it...which I could attach 3 actions to it. Tap, double tap and hold.

**Comment by dshokouhi** [comment]
Samsung does like to modify Android a bit more so they may have added something only for their devices. For our app we try to go by official APIs so we would need to see it supported in documentation. As of now we only get notified on the `onClick` method.

**Comment by guarddog13** [comment]
I get it lol. I can't find it for the life of me and wish I wouldn't have deleted it..i wonder if it got removed. Hmm

**Comment by dshokouhi** [comment]
I am going to close this request, please feel free to submit individual feature requests for each feature you would like to add. Please make sure not to combine multiple features into the same request as they become difficult to track.
