### ISSUE TITLE
Unexpected IsCharging state reported

### ISSUE THREAD

**Issue by make-all** [home-assistant/android#2785]
**Home Assistant Android version:**
beta-2584-22df320f-full

**Android version:**
12.0.0.223

**Phone model:**
Huawei ALP-29

**Home Assistant version:**
2022.8.3

**Last working Home Assistant release (if known):**

**Description of problem:**

The is_charging binary sensor has unexpected behaviour.  My expectation was that it would report true if the charger is plugged in, and false if it is unplugged.  I would also not be surprised by the behaviour if it strictly followed the "charging" state of battery state, however it seems to report true when the battery state is either "charging" or "full", and false if the battery state is "discharging" or "not_charging".  The latter is the surprising one, as the phone's battery optimisation causes it to report this when it has partially charged but still plugged in but decides to stop the charging.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

![charging](https://user-images.githubusercontent.com/9624699/183877582-3eaf2552-4be6-4825-b7cd-a58f2dd55ec5.png)

**Additional information:**

The reason this was discovered is that I created an automation to switch my light to night mode (this particular light has a separate small led as a nightlight) for 10 minutes after I plug in my phone before turning the light off completely.  This was triggering at 3:30am, causing my nightlight to come on unexpectedly when the battery optimiser decided to finish the phone charging.

**Comment by jpelgrom** [comment]
The "is charging" sensor is [based on the battery state](https://github.com/home-assistant/android/blob/22df320fd92d977c65d8b6bc7ce9f9a8e94467cb/common/src/main/java/io/homeassistant/companion/android/common/sensors/BatterySensorManager.kt#L73-L78), not the charger type, as is visible from your graphs. `charging` and `full` are considered charging, and `discharging` and `not_charging` are considered not charging. Android only reports these states, no additional details like 'not charging because of battery optimisation'.

Even when plugged in it is possible that the device isn't charging - for example, the charger cannot supply the required voltage or the battery is overheated so it won't charge. Changing the "is charging" sensor to report it is charging while the state is `not_charging` doesn't make sense to me.

>  The latter is the surprising one, as the phone's battery optimisation causes it to report this when it has partially charged but still plugged in but decides to stop the charging.

I'm afraid this is down to each individual manufacturer, for example on my device it keeps showing `charging` even though it clearly isn't  constantly charging and waiting for me to wake up before completing the charge:

![A graph showing that the battery level stays at 80% for a few hours, with the battery state still showing `charging`](https://user-images.githubusercontent.com/8148535/183884820-4976b157-ab50-463d-b37e-4654e1e3855d.png)

For your use case, maybe it is better to use the "charger type" sensor (also updates instantly)? You want to know when the phone is plugged in, not whether or not it is charging.  Or you could check the states of both the "is charging" and "charger type" sensors?

**Comment by make-all** [comment]
To me it seems inconsistent to report is_charging for the full state, but not for the not_charging state.  I'm not sure what use the current information returned by is_charging can be useful for, due to the treatment of not_charging.

**Comment by jpelgrom** [comment]
The `full` state is only possible while the device is charging, when unplugged it will almost immediately change to `discharging`. This is why `full` is included in the "is charging" sensor as true. `not_charging` can happen both with and without a charger plugged in; if anything the name contradicts that "is charging" is true.

As mentioned it seems to depend on the device how it reports 'paused' charging for optimisation/smart purposes, some will continue to report `charging` (like in my example) while others will not (your device). I agree that for you the "is charging" sensor may not be useful, but for others it _is_ useful.

**Comment by make-all** [comment]
On the other hand, the device class for is_charging seems to be set to "plug", rather than "battery_charging", which adds to the confusion.

**Comment by dshokouhi** [comment]
> On the other hand, the device class for is_charging seems to be set to "plug", rather than "battery_charging", which adds to the confusion.

`battery_charging` was added after this sensor had already existed I believe.
