### ISSUE TITLE
History cards are difficult to tap single point

### ISSUE THREAD

**Issue by cliffjao** [home-assistant/android#2819]
It's very hard to tap on a single point in the history card. It'd be great if you could long press to scroll through the data points according to time.

**Comment by jpelgrom** [comment]
Hi 👋

The history card is provided by the frontend, and is not controlled by the app. Can you check a browser on the same device (for example Chrome), is it also difficult for you to tap on a single point in that case?

**Comment by jpelgrom** [comment]
Thanks for testing in Chrome!

Because the same issue also happens in a browser, please open [a new issue or feature request for the frontend](https://github.com/home-assistant/frontend/issues/new/choose) instead. I'm not entirely sure if this should be considered a bug (hard to tap when using touch), feature request (press+hold to navigate the graph), or both, but either way it is not something that should be handled by the app.

**Comment by cliffjao** [comment]
> 

Thanks! Filed it here: https://github.com/home-assistant/frontend/discussions/13494
