### ISSUE TITLE
Battery current does not always report in microamperes

### ISSUE THREAD

**Issue by CamFlyerCH** [home-assistant/android#2846]
**Home Assistant Android version:** 2022.8.0-full

**Android version:** 12

**Phone model:** Samsung Galaxy S21 5G / SM-G991B/DS

**Home Assistant version:** 2022.8.7

**Last working Home Assistant release (if known):**

**Description of problem:**
The sensor battery power measures the current 1000x to small. Hence the watt are also 1000x to small und unusable. Same issue during charging and discharging. I compared the values to a current meter in my charger and to an app AccuBattery pro.
Voltage seams fine !

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/25889580/188281646-95701ee9-e7d1-4329-8961-844b1802cc36.png)

![image](https://user-images.githubusercontent.com/25889580/188281678-8337d2dd-82bd-46a4-a088-da5e7b1aa488.png)

**Additional information:**

**Comment by dshokouhi** [comment]
The app is actually converting microamps to amps.

https://github.com/home-assistant/android/blob/ef5ec73a877f735112ac2a192e4717b83ecd7f69/common/src/main/java/io/homeassistant/companion/android/common/sensors/BatterySensorManager.kt#L323

https://developer.android.com/reference/android/os/BatteryManager#BATTERY_PROPERTY_CURRENT_NOW

It seems some manufacturers may not be providing microamp values? On my pixel the conversion is correct otherwise it would be very high.

![image](https://user-images.githubusercontent.com/1634145/188281966-eb641b40-58cd-4b73-8b6f-1e7a7b10a97e.png)

On my Amazon tablet its also completely different

![image](https://user-images.githubusercontent.com/1634145/188282076-601ead53-4d8b-4b0a-a7aa-64a4b178891e.png)

**Comment by CamFlyerCH** [comment]
After some searching it seams to be a known issue with this value ! 
[https://play.google.com/store/apps/details?id=com.competit.battery_monitor](https://play.google.com/store/apps/details?id=com.competit.battery_monitor)
This app has the same issue.

Since it seams to be that the only solution to make the divider configurable. Your Tablet reports probably nano Amperes, the Pixel correctly micro Amperes and the Samsung Galaxy series (I tested also an S8 and a S21 FE) report milli Amperes. Google should check that in a sort of certification program. 

Another way is to include a database of dividers per device or make an guess. A running device would normally use between 5 - 5000 mA wenn unlocked. At least we know now, that the companion app and the Google Pixel are configured to Googel's spec.

So now this issue should be converted to a feature request.

**Comment by dshokouhi** [comment]
> Since it seams to be that the only solution to make the divider configurable.

Thats a good suggestion and thank you for the research. Let's see if others experience the same or different values to determine if we need to worry about voltage and other possible units. Hopefully it is just the 3 units :)
