### ISSUE TITLE
Show settings chip even when trying to connect to Home Assistant (Wear OS)

### ISSUE THREAD

**Issue by SkechyWolf** [home-assistant/android#2850]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
 When trying to connect to HA on WearOS the settings chip does not show until it has succeeded in connecting or has failed to connect It would be nice if it showed no matter what state of connection 

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by leroyboerefijn** [comment]
This was actually recently removed. I think the issue was that most of the settings need a loaded list of entities, right @jpelgrom ?

We could just disable those options instead

**Comment by jpelgrom** [comment]
> This was actually recently removed. 

I'm not aware that it was removed, in fact I added the settings chip back if loading failed in #2825 to prevent users from getting stuck. 

> I think the issue was that most of the settings need a loaded list of entities, right @jpelgrom ? We could just disable those options instead

Right now they'll just display empty lists instead, which as far as I'm aware doesn't have any negative consequences (aside from maybe user confusion). Disabling when still loading or on error is a good improvement.

**Comment by leroyboerefijn** [comment]
> I'm not aware that it was removed, in fact I added the settings chip back if loading failed in #2825 to prevent users from getting stuck.

I could be mistaken, but that PR introduces an if statement around the Settings chip, to only show it when we're not loading on this line: https://github.com/home-assistant/android/blob/84aa4454b731e4058cce083d947c27a4d90c5469/wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt#L302

That is what I meant at least :)

**Comment by jpelgrom** [comment]
Before the PR, it was only included when `mainViewModel.loadingState.value == MainViewModel.LoadingState.READY`, while now it can also be `ERROR`.

**Comment by jpelgrom** [comment]
Trying to change this, but I want to add some padding because `fillMaxSize()` only works when there is one item in the list and otherwise everything is very close to each other and to the top of the screen. However, it always seems to scroll the list to the bottom/center the settings button in the middle of the screen, have any of you seen this issue before?

You can barely see the loading circle and no loading text:
![image](https://user-images.githubusercontent.com/8148535/195679755-87649e0e-5c53-4479-b1e5-40eb4e5db800.png)

However there is plenty of padding, when scrolled to the top:
![image](https://user-images.githubusercontent.com/8148535/195679890-e56900b2-47b5-4939-ba72-1acc6d9348d9.png)

**Comment by leroyboerefijn** [comment]
`ScalingLazyColumn` will try to show the second item at the center of the screen by default. I guess that's what you're seeing here. You can change it by providing `AutoCenteringParams`

**Comment by jpelgrom** [comment]
Thanks, I must've overlooked that setting. I opted to add an empty/spacer item while loading instead of changing the properties for the list as it is used everywhere and I don't want to unintentionally break other layouts, see the linked PR.
