### ISSUE TITLE
Android device control only shows camera preview when recording

### ISSUE THREAD

**Issue by JacobErnst98** [home-assistant/android#2870]
**Home Assistant Android version:**
2022.8.0-full
**Android version:**
12
**Phone model:**
Pixel 3XL
**Home Assistant version:**
2022.8.6
**Last working Home Assistant release (if known):**

**Description of problem:**
The Android device control section on my Pixel shows a preview of the cameras from home assistant. However the camera preview is only shown on the card if the camera status is "Recording", if the camera is idle no preview is shown.

**Screenshot of problem:**
![Screenshot_20220909-151608](https://user-images.githubusercontent.com/20033929/189427582-d88f49e7-0663-4caa-bf52-ab6ade28afda.jpg)
**Additional information:**
Using the developer tools I set the state of the camera to "Recording" manually while the camera was idle. The preview then showed up in Android device control.

**Comment by jpelgrom** [comment]
This is mostly correct - the app will always include the image and indicates if the camera is active (recording or streaming) or not. Google decided to only show the camera image if the camera is active.

(see also comments in #2663)

**Comment by jpelgrom** [comment]
Looking at the documentation, maybe we could switch to the `is_on` attribute to determine the active state and show images more often. @JacobErnst98 are these cameras on according to this attribute?

**Comment by JacobErnst98** [comment]
@jpelgrom Forgive me, how do I check that for you?
I'm looking under "Developer Tools" -> "States" and /config/devices/device/<UUID> and cant find that attribute.

**Comment by dshokouhi** [comment]
I do not see that attribute for my cameras either in the states tab

**Comment by JacobErnst98** [comment]
The cameras I have are from the "Unifi Protect", "Mail and Packages" and "ESPHome" integrations.
None of them have is_on attribute, at least that I can see from the front end.

**Comment by jpelgrom** [comment]
Sorry, spoke to soon, it appears that this is only a property that is available internally. I don't think there is any better way we can determine the state in that case 😔

**Comment by JacobErnst98** [comment]
@jpelgrom One of my cameras is offline and the sensor status is "Unavailable" Maybe we can just display the preview unless the sensor is unavailable

**Comment by jpelgrom** [comment]
> @jpelgrom One of my cameras is offline and the sensor state is "Unavailable" Maybe we can just display the preview unless the sensor is unavailable

We can't do anything with related sensors - it has to be the camera entity's state itself or one of its attributes. Also preferably something that isn't specific to one or a few integrations.

If `unavailable` is reliable I'd say indicating to the system that a camera is active as long as it isn't `unavailable` is an acceptable option to better match how the frontend handles cameras, even if it doesn't match Google's intended use. The label will still indicate HA's state. @dshokouhi Do you agree?

**Comment by AngellusMortis** [comment]
Just because a camera does not have their state set to `streaming` does not mean an image is not available to be shown. A camera can have an image source without having a live streaming source. If a camera is not `unavailable`, it should have an image display. 

Also, with a lot of things in core, there is not a lot of explanation for what some things do. `is_streaming` is not documented and _most_ camera integrations do not even implement it (only 4 do). It is also uncertain if `is_streaming` is suppost to refer to if [someone is watching the stream](https://github.com/home-assistant/core/blob/dev/homeassistant/components/hyperion/camera.py#L180) or just if that the [stream source if available](https://github.com/home-assistant/core/blob/dev/homeassistant/components/netatmo/camera.py#L173).

The HA Frontend does also show images when the camera is in the `idle` state as well. 
![image](https://user-images.githubusercontent.com/490848/189439972-04871812-5ce3-4e16-ae2f-40203c7e1505.png)

**Comment by dshokouhi** [comment]
@jpelgrom I think `unavailable` is a good indicator here to being active :)

**Comment by jpelgrom** [comment]
> Just because a camera does not have their state set to `streaming` does not mean an image is not available to be shown. 

As previously mentioned, the app currently always includes the image if it's available. Google/the system then decides if it should be shown or not.

It does sound like the consensus is to also indicate `idle` as 'active' to the system to make it show the image more often :) I'll do some tests and submit a PR to change the app's behaviour soon.

**Comment by jpelgrom** [comment]
Submitted, thanks for the quick responses and additional info about camera entities everyone!
