### ISSUE TITLE
App lock timeout not honored when app is left open on settings screen

### ISSUE THREAD

**Issue by RoboMagus** [home-assistant/android#2877]
**Home Assistant Android version:** 2022.8 & DEV

**Android version:** 12

**Phone model:** Samsong Galaxy S10

**Home Assistant version:** 2022.9.2

**Last working Home Assistant release (if known):** -

**Description of problem:**
When the app is suspended when the companion app settings screen is open, reopening the app does not present the user with the biometric prompt, even after the app lock timeout is expired. Only when navigating out of the settings screen to the webview the biometric prompt is shown. Meanwhile information such as the home assistant URL and settings to disable the lock are available and visible.

**Traceback:** N/a

**Screenshot of problem:**

**Additional information:**
I came accross this issue when working on #2868, but it replicates on the latest (non-beta) release as well.

Proposed solution would be to migrate handling of the lock timeout into the authenticationRepository and then also using that when resuming to the settings screen.

**Comment by dshokouhi** [comment]
So technically this is working as designed because when we first added the app lock it was only applied to the webview activity.  So we would need to check this in almost all of our activities to really prevent interaction because what about the case for creating a widget. Should you be allowed to create a widget when the app is locked if we are trying to prevent a user from accessing settings too?

**Comment by RoboMagus** [comment]
That's a valid point that I had not considered. 
However, from within the widget creation screen one would not be able to disable the app lock before leaving as is possible from within the settings screen. Also the HA url is not visible there. As such the impact from having the settings exposed is greater than that of e.g. a widget or tile creation screen.
