### ISSUE TITLE
Erratic activation of High Accuracy

### ISSUE THREAD

**Issue by Kedryn** [home-assistant/android#2895]
**Home Assistant Android version:**
2022.8.0

**Android version:**
11

**Phone model:**
Poco-X4 Pro and Redmi 9 Pro

**Home Assistant version:**
2022.9.5

**Last working Home Assistant release (if known):**

**Description of problem:**
Our (me and wife) companion app are set up for HighAccuracy with a 2km range outside zone.home.
Often we find that the High Accuracy mode is enabled even when we are inside zone.home, draining the battery.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

I have logs but they cointains location data, so i prefer to send them directly, not publish then on git.

**Comment by dshokouhi** [comment]
Please mask the location coordinate data and post the logs here so we can investigate.

**Comment by Kedryn** [comment]
[hacomp.txt](https://github.com/home-assistant/android/files/9596817/hacomp.txt)
i changed long e lat to other numbers (the integer part)

**Comment by dshokouhi** [comment]
Unfortunately these logs do not contain any instances of High accuracy mode turning on or off.  The best way to troubleshoot this issue is to look at the logs when the issue occurs. The app depends on location updates from google and this portion in particular is for Geofence events which also get printed to the logs.

Have you tried to maybe increase the home zone radius to see if that stops the issue? It could be reporting you just outside the zone.

**Comment by dshokouhi** [comment]
Closing due to lack of response
