### ISSUE TITLE
Companion app seems to occasionally open new Chrome instance when clicking on links

### ISSUE THREAD

**Issue by flyize** [home-assistant/android#2976]
**Home Assistant Android version: 2022.10.2-full

**Android version: 13

**Phone model: Pixel 6 Pro

**Home Assistant version: 2022.10.0

**Last working Home Assistant release (if known): n/a

**Description of problem: I have an Upwork job alert in HA NR that sends a message to my phone with the URL of the project. Occasionally, it seems to open a brand new Chrome instance. Once that happens, I’m unable to get to my original Chrome instance with all its tabs until some indeterminate amount of time.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem: n/a

**Additional information: This is NR code I'm using to send the notificaition
```
{
    "title": "Upwork Alert",
    "message": "{{article.title}}",
    "data": {
        "group": "Upwork",
        "actions": [
            {
                "action": "URI",
                "title": "Open Url",
                "uri": "{{{article.permalink}}}"
            }
        ],
        "clickAction": "{{{article.permalink}}}"
    }
}
```
Just in case, here's the thread I started first: https://community.home-assistant.io/t/companion-app-seems-to-occasionally-open-new-chrome-instance-when-clicking-on-links/477414

**Comment by flyize** [comment]
Anything else I can add to this?

**Comment by jpelgrom** [comment]
Managed to reproduce this on first try, now I have two Chrome tasks in recents:

![Android 13 recents screen with two Chrome instances visible](https://user-images.githubusercontent.com/8148535/204096226-8433d9e3-156a-405d-b99a-74be5bf1b4a2.png)

<details>
<summary>Sample notification (HA yaml)</summary>

```yaml
service: notify.mobile_app_pixeldev
data:
  message: A test
  title: Websites
  data:
    clickAction: https://home-assistant.io/
    actions:
      - action: URI
        title: HA site
        uri: https://home-assistant.io/
```

</details>

If Chrome is in recents it will launch a new task and only show one tab: for the link from the notification action. This is what you see in the screenshot above.

If Chrome is not in recents it will add the tab to the existing set of tabs instead.

If I have two (or more) tasks, launching Chrome again opens the last used task. I cannot access the other task with my other tabs until I close all tabs in the last used task and remove it, another launch will then open the previous task with the other tabs.

This seems to be caused by the app explicitly requesting new + multiple tasks:

https://github.com/home-assistant/android/blob/6a0b18525b9c5a7979bf855795c2bcd400f657dc/app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt#L1710-L1711

(not every app respects this - Firefox is adding a new tab and doesn't do multiple tasks it seems)

I think removing the flags when not dealing with the Home Assistant app would be a good 'fix', to better match expectations and other apps. What do you think @dshokouhi as you recently added more flags for recents handling based on user feedback?

**Comment by dshokouhi** [comment]
I can't remember why we had it this way, I would say if we are to change it then we need to just make sure it consistently works the way we want it to. We normally opt for a new task as usually when we reuse a task it does not behave as expected but I am not sure that applies to sending things to the browser but it will indeed impact our webview instance when it comes to navigating back and forth between views. So whatever fix we do here should only be applied to when we send things to the browser.

**Comment by flyize** [comment]
Thanks @jpelgrom!
