### ISSUE TITLE
Cannot activate Beacon monitor sensor on android 9 phone

### ISSUE THREAD

**Issue by Sophokles67** [home-assistant/android#3020]
<If I trie to activate beacon monitor sensor this is not possible because of geolocation permissions. But Pemission is granted füor the app. Other users report, that the "always on" permission for geolocation must to be chosen. But on my android 9 Note 8 there is no such option, so I think that geolocation is always "always on" if permission is granted.

**Comment by marazmarci** [comment]
You didn't fill the issue template, so we don't know which app version you're using, but I guess you're still using the latest Play Store release, which is [2022.10.2](https://github.com/home-assistant/android/releases/tag/2022.10.2).

The issue you encountered has been already fixed in #2964, and was first released in the [beta-2790-3e72f271](https://github.com/home-assistant/android/releases/tag/beta-2790-3e72f271) build. Try downloading that, or the [latest build](https://github.com/home-assistant/android/releases)'s APK.

**Comment by marazmarci** [comment]
Or you can also subscribe to beta on the Play Store [here](https://play.google.com/apps/testing/io.homeassistant.companion.android).

**Comment by Sophokles67** [comment]
Hi!,

many thanks for your immediate help. 

Thanks,

Michael

 

Von: Márton Maráz ***@***.*** 
Gesendet: Sonntag, 30. Oktober 2022 13:53
An: home-assistant/android
Cc: Sophokles67; Author
Betreff: Re: [home-assistant/android] Cannot activate Beacon monitor sensor on android 9 phone (Issue #3020)

 

Or you can also subscribe to beta on the Play Store here <https://play.google.com/apps/testing/io.homeassistant.companion.android> .

**Comment by dshokouhi** [comment]
Closing as per above, this should be fixed in the latest beta. If it is not please open a new issue and make sure to fill out the issue template completely.
