### ISSUE TITLE
Unable to connect to Home Assistant

### ISSUE THREAD

**Issue by b177y** [home-assistant/android#3106]
**Home Assistant Android version:**
Version 2022.11.0-full

**Android version:**
9

**Phone model:**
Moto G6

**Home Assistant version:**
Home Assistant 2022.8.7

**Last working Home Assistant release (if known):**
n/a

**Description of problem:**
Attempting to set up home assistant app on android phone, getting 'Unable to connect to Home Assistant. Server or proxy hostname failed, please check that the URL is a valid Home Assistant URL.'

**Additional information:**

* connecting from local network
* can connect from browser on same device, domain is resolving fine
* SSL is using LetsEncrypt, cert is valid
* Can log in to same instance from iOS devices.
* tried following networking troubleshooting guidance in companion app docs, could not fix issue
* Using Android System WebView

**Comment by dshokouhi** [comment]
Looks like our webview instance is returning the following error message

https://developer.android.com/reference/android/webkit/WebViewClient.html#ERROR_HOST_LOOKUP

This is unfortunately not something the app can solve. Do you have a proxy or custom DNS server setup? What happens if you bypass it?  Do you have any custom cards or views? its possible those could be giving an error but its tough to tell what is happening without looking at on device logs.   As of now logs are only available after you are logged in so we would need to use a logcat app or android studio to pull them.

**Comment by b177y** [comment]
I've ruled out custom cards / views causing errors by temporarily replacing the home assistant container with a fresh one with no added configuration and this makes no difference.

There is no proxy or VPN on the phone. There is a custom DNS server but the home assistant domain has a public DNS record so it is not relying on the local DNS server for resolution.

Is there a logcat app you would recommend that would avoid the need to install android studio?

**Comment by dshokouhi** [comment]
you can use logcat reader but it will require you to grant special USB permissions.

**Comment by b177y** [comment]
Using adb logcat I got the same error and nothing else helpful. I've decided to give up using this DNS configuration and I'm now using a public proxy in front of the instance. Very strange that a domain will resolve in chrome but not in Android System WebView, something I'll have to look into when I have more time.
