### ISSUE TITLE
Companion app still not uses dark theme if companion app settings are "Dark" or "Follow Home Assistant Settings" but Home Assistant is set to "Auto"

### ISSUE THREAD

**Issue by bcutter** [home-assistant/android#3107]
**Home Assistant Android version:** 2022.11.0-full

**Android version:** FireOS 7.3.2.6

**Phone model:** Fire HD 10 Plus (11th generation)

**Home Assistant version:** 2022.8.7

**Last working Home Assistant release (if known):**

**Description of problem:**
- Exactly the same as in https://github.com/home-assistant/android/issues/2985. 
- `Revert/set force dark again for webview by @jpelgrom in https://github.com/home-assistant/android/pull/2989` of https://github.com/home-assistant/android/releases/tag/2022.11.0 changed *nothing* for me.
- Force closed app and deleted app cache afterwards.
- More details: opening HA the splash screen background is using dark mode, as well as the mobile app settings area does. Everything else is still NOT using dark mode.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

![grafik](https://user-images.githubusercontent.com/13799156/204104275-ed3b738a-7f0c-44c8-b7bd-318229fe1d66.png)

![grafik](https://user-images.githubusercontent.com/13799156/204104283-b1d7aa58-6bd1-4097-a773-fc7797ca8510.png)

![grafik](https://user-images.githubusercontent.com/13799156/204104286-02fd0755-4c2d-4fe0-86e2-e3e9adf37e0a.png)

**Additional information:**
- https://github.com/home-assistant/android/issues/2985#issuecomment-1327933041
- WebView version on device: `Amazon System WebView 104.amazon-webview-v104.5112-tablet.5112.114.50`

**Comment by jpelgrom** [comment]
This is somewhat unexpected, the PR mentioned in your second bullet point basically undid all the changes to the webview for themes, returning to the state before 2022.10 Android.

Just to be sure this is a bug for the app: does manually switching to dark mode in your profile settings work? (Thema: Dunkel instead of Automatisch)

**Comment by jpelgrom** [comment]
The current theory is that this is caused by the app targeting Android 13 - which mentioned that providing dark theme info to the webview would stop working in a way, and that there was a new API. However the release notes for the latest version of that dependency now mention [this only starts working on Android <Q with webview 105+](https://developer.android.com/jetpack/androidx/releases/webkit#1.6.0-alpha03), which wasn't there before.

As a result, I don't think this can be fixed right now as we cannot downgrade our target version in the Play Store. It looks like Amazon has updated the webview to check the target Android version but not to support the new webview dark mode features, which is a bit odd. Amazon will need to update it to version 105 or newer (presumably). You can also set the theme manually in your profile which seems like a good idea as the device doesn't support automatic switching anyway ☺️

**Comment by dshokouhi** [comment]
> * A HA Companion app update broke a feature (automatic light/dark mode switching) which was working fine before.

Well it wasn't on purpose and judging from the responses in the original issue its actually fixed for some users but not all. The PR you referred to previously had the impacting changes reverted.

In that same HA app version Androids Webkit dependency had an update which we are assuming is causing this issue. There was an unmarked change at the time which meant that on Android versions 9 and lower the API we use no longer works. That is why all the users in that thread said the debug fixes were working for them. I guess you did not join in the test so we could catch this issue earlier but understandable when multiple users confirm its working for them. Personally I keep all Amazon devices on Dark theme because they do not support native dark mode which is also part of the issue here. The developer setting you are referring to is a workaround because Android did not get a proper dark theme until the next Android version.



> * Now fingers are pointed to Amazon (they didn't change the app...)

In this case its Amazon. All Google Play certified get updated WebView versions from the play store so they can be kept up to date with the latest technology.  Unfortunately Amazon did not decide to go this route in their Fire OS and the only way to update the WebView package is by Amazon sending an update. Had Amazon followed standard android practices to provide an updated WebView separate from System updates (which was the whole point of Android 5) we wouldn't be in this situation and all Amazon devices would use modern webviews. Technically it is still separated but its not like you can get immediate updates in the amazon app store as one would expect, they control when you get those updates.



> I need a **solution**, no further workarounds (like the "switch it manually twice a day on all your devices" or like downgrading the app on all my affected devices prior 2022.10.2 which also only buys time).

As of this moment if the current workaround is unacceptable for your own use case then yes you will want to downgrade the impacted devices to restore functionality. Unless of course the issue still exists after the downgrade in that case which will then suggest a HA frontend issue. Theres a lot of moving parts here as its not just the app but system components installed on the user device which can have an impact. The good news is that Amazon devices are on WebView 104 so hopefully the next time they get a version bump it will either just work or its something we can fix code wise.

**Comment by dshokouhi** [comment]
Just uninstall and reinstall the app. Shouldn't take that long to get it setup.

**Comment by dshokouhi** [comment]
As long as you give teh device name the same name as you previously had then all entities will keep the same name.  Keep it simple. It only takes about 10-15 min to setup the app. Longer if you need to do widgets, tiles and other things but sensors and entity names are simple.
