### ISSUE TITLE
Optional entity name in watch compilations

### ISSUE THREAD

**Issue by Nossnevs** [home-assistant/android#3190]
**Is your feature request related to a problem? Please describe.**

When using entities in watchface compilations almost all of my entity names takes the whole slot. Now it is 'entity_name / value'.
**Describe the solution you'd like**

I want it to be opinional after you choose entity for a compilation if want a name or not. The entity name can be pre-filled in but you can choose you own.
Nice to have is to be able to set icon. 

**Describe alternatives you've considered, if any**

Remove entity name from compilation and only show icon and value.

**Additional context**

Samsung watch 4

**Comment by jpelgrom** [comment]
Option to disable showing the entity name: #3465. I'm not sure an option to provide a custom name is a good idea because of the added complexity and very small watch screen. The complication (mostly) mirrors your entity in Home Assistant, if you want to change the appearance you'd preferably change it everywhere.

**Comment by dshokouhi** [comment]
Closing as the request is now complete, if multiple things were requested please file a separate request for each item.
