### ISSUE TITLE
Homeassistant app gets unresponsive if home network is unreachable

### ISSUE THREAD

**Issue by toskium** [home-assistant/android#3226]
**Home Assistant Android version:**  2022.12.0-full

**Android version:** Android 13

**Phone model:** Google Pixel 7 pro

**Home Assistant version:** 2023.1.4

**Last working Home Assistant release (if known):** never

**Description of problem:**

I am running Homeassistant without any cloud connection, so the HA Android app only has access to HA when I am connected to my home wifi network.
Unfortunately when I am not at home and therefore the network is unreachable the Homeassistant app crashes and presents the message shown in the screenshot below.

I would expect the app to recognize the home network as unavailable and just idle until it is available again, but it seems it doesn't.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

![image](https://user-images.githubusercontent.com/15872792/212372145-dec24dce-b7c8-4edd-8416-cea832785ffe.png)

**Additional information:**

**Comment by dshokouhi** [comment]
can you please check for the crash logs lthat were skipped over?

**Comment by toskium** [comment]
@dshokouhi as soon as the next crash happens I will gather the logs, the log seems to be truncated which I didn't know when it happened.

**Comment by dshokouhi** [comment]
@toskium try checking the logs to see if there is a Recent Crash tab, it may or may not have the logs but that will be the log we actually need.

**Comment by toskium** [comment]
@dshokouhi it really doesn't show anything more than this: 

[homeassistant_companion_log_0-13-2023_18-26-31.txt](https://github.com/home-assistant/android/files/10413888/homeassistant_companion_log_0-13-2023_18-26-31.txt)

**Comment by dshokouhi** [comment]
@toskium those are normal logs, I meant the Recent Crash tab that will only be visible in the logs section if the app was able to save the last crash , this is also only visible for 12 hours after the last saved crash. Sounds like you should be able to easily reproduce the issue by disconnecting wifi and staying on cellular.

**Comment by jpelgrom** [comment]
Looks like the app is sending `ping`/`pong` messages - do you have persistent connection enabled all the time? No excuse for unresponsiveness but if you're not able to connect outside the home network that might have something to do with it :)

**Comment by toskium** [comment]
@dshokouhi the latest crash was today, but frankly there is no recent crash tab. Would that mean the app was force closed by Android before it was able to capture anything?

Just to be clear where to look. This is the place where I check for log (highlighted)
![image](https://user-images.githubusercontent.com/15872792/212387153-746aff78-9a2d-4eb2-9e49-1af26f1baa88.png)

And this is what I see;
![image](https://user-images.githubusercontent.com/15872792/212387331-606fef71-e195-4593-abec-6f08ee9df5df.png)

I can confirm that the latest crash of the device was less than 12h ago.
Am I looking in the wrong place?

@jpelgrom I experimented with that setting to see if it would make any difference, but since the issue occurs on all family Pixel 7 devices I can say, that the others have only Google notifications active and so do I now.

**Comment by dshokouhi** [comment]
> Am I looking in the wrong place?

its not guaranteed that the app will be able to save the event every time, it will show up if we were able to.

Just out of curiosity but why are you using location tracking on a device that will not work outside the home network? It will never be able to change the state if it can only update on the home network. Like mentioned earlier we shouldnt be crashing like this but it may help the situation. In fact I am not sure if widgets and quick setting tiles will be good either as those will generate calls.  A device that can only work on the home network may benefit more from just using a browser since most app features will not work when away. For example you can get a notification but you can't do anything with it, you might be able to click to go to another app but you can't control a device or receive an event. 

In our case we are able to tell when the device is or isn't connected to the internet to make calls, when its come to the server we will only know its not reachable by attempting to reach it. The logs will be of help here so we can try to understand where the crash occurs so we can stop it from crashing but that doesn't mean the app still won't try to connect back to the server and become "idle".

**Comment by toskium** [comment]
Most importantly: disabling the location sensors can be accepted as a workaround, the app stays stable even if the device is away from the home network. Thank you @dshokouhi!

Another Pixel device which still had the sensors enabled captured the following logfile, unfortunately it isn't a crash log, but if I am reading it right, the app doesn't like trying to reach the HA server and I assume it eventually gets terminated by Android.

You can view it here: [homeassistant_companion_log_0-17-2023_11-42-56.txt](https://github.com/home-assistant/android/files/10449223/homeassistant_companion_log_0-17-2023_11-42-56.txt)

It would be OK with me to close the issue since it's an easy workaround. Maybe it could somehow become an out of the box fix in a later release.

**Comment by dshokouhi** [comment]
> Most importantly: disabling the location sensors can be accepted as a workaround, the app stays stable even if the device is away from the home network. Thank you @dshokouhi!

no problem location updates can occur every 60 seconds or every 30 seconds. By keeping those sensors enabled you are just telling the app to keep failing since its not at home. Location sensors don't make sense for a device that can never phone home when its away.



> Another Pixel device which still had the sensors enabled captured the following logfile, unfortunately it isn't a crash log, but if I am reading it right, the app doesn't like being unable to reach the HA server

the failures are because the server is unreachable, in those cases its acceptable to see errors but no crash



> and I assume it eventually gets terminated by Android.

The real issue for us is finding out which error is causing the app to crash and shut down, the errors in the logs are all caught exceptions so its behaving as we would expect there.



> It would be OK with me to close the issue since it's an easy workaround. Maybe it could somehow become an out of the box fix in a later release.

we should keep this open to see if we get an actual crash log so we can fix the issue.

**Comment by toskium** [comment]
> we should keep this open to see if we get an actual crash log so we can fix the issue.

Is there anything I can do to increase the probability of capturing an actual crash log?
It would be OK for me to provoke the issue if I eventually get the correct logfile.

**Comment by toskium** [comment]
Okay, great, that all sounds doable, I will report back as soon as I have something usable 🙂

**Comment by teemu-rossi** [comment]
Note that this is an ANR (Application Not Responding) where the OS kills the process for being unresponsive and not a crash due to an unhandled exception. This happens to me regularly and this time I grabbed the latest ANR log file grabbed using `adb bugreport` on Pixel 5 / Android 13. My Home Assistant installation is not currently accessible from my phone due to my network setup.

This seems to be the relevant part of the call stack:
```
  - waiting on an unknown object
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
  at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:88)
  at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
  at kotlinx.coroutines.BuildersKt.runBlocking(unavailable:1)
  at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
  at kotlinx.coroutines.BuildersKt.runBlocking$default(unavailable:1)
  at io.homeassistant.companion.android.sensors.LocationSensorManager.sendLocationUpdate(LocationSensorManager.kt:768)
  at io.homeassistant.companion.android.sensors.LocationSensorManager.sendLocationUpdate$default(LocationSensorManager.kt:753)
  at io.homeassistant.companion.android.sensors.LocationSensorManager.handleLocationUpdate(LocationSensorManager.kt:652)
  at io.homeassistant.companion.android.sensors.LocationSensorManager.onReceive(LocationSensorManager.kt:190)
  at android.app.ActivityThread.handleReceiver(ActivityThread.java:4306)
```

Here's the full log for completeness.
[anr_2023-01-23-15-22-23-866.log](https://github.com/home-assistant/android/files/10480796/anr_2023-01-23-15-22-23-866.log)

**Comment by Zixxorb** [comment]
I am having this issue as well.
Device is Samsung Galaxy S22 Ultra. No log files unfortunately.

Seems to be on wifi and cellular. I do have location on as a couple of automations require me to be at home.

**Comment by jpelgrom** [comment]
Recent changes have changed how location updates are processed which [move it off the main thread](https://github.com/home-assistant/android/blob/7412dd22ab81765600d10f25835ffdeabd1eb046/app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt#L662) and should prevent the ANR in teemu-rossi's comment. If any of you are still experiencing this with beta-3154 or newer*, please drop a comment.

\* currently the change isn't in any stable releases yet

**Comment by dshokouhi** [comment]
Closing as this issue should be fixed in the latest release and we have not heard back from any users yet. If you still experience an issue please comment back after ensuring you are on the latest version 2023.3.0
