### ISSUE TITLE
Support for custom icons for notifications

### ISSUE THREAD

**Issue by Proche72** [home-assistant/android#3365]
The notification_icon now supports only mdi, can you add support for custom icons which already works in HA?

for example:
https://github.com/elax46/custom-brand-icons
https://github.com/arallsopp/hass-hue-icons

**Comment by dshokouhi** [comment]
We can't add support just because they exist in Home assistant. There needs to be an Android library that contains the custom icons for us to use.

**Comment by Proche72** [comment]
Thank you for the clarification, I didn't know that.

**Comment by dshokouhi** [comment]
As these are home assistant specific icons (or at least created for it) I will be closing this issue since obviously an Android library does not exist. We may also need to worry about licensing issues (maybe?) but also only MDI is included in HA core so we should stick to what we know is supported for default installations.
