### ISSUE TITLE
Year of the voice: Allow microphone over http connections

### ISSUE THREAD

**Issue by conorlap** [home-assistant/android#3512]
**Is your feature request related to a problem? Please describe.**

I cannot use the microphone with my HA instance as I don't expose it to the internet via https. I use a vpn and access the local IP of my instance via http.

**Describe the solution you'd like**

As documented here, I'd like an option to enable the microphone for local unsecure origins. I've made this settings change on Chrome on my Android device hoping it would also affect the HA app but it doesn't seem to have.
https://medium.com/@Carmichaelize/enabling-the-microphone-camera-in-chrome-for-local-unsecure-origins-9c90c3149339

**Describe alternatives you've considered, if any**

Expose my HA instance to the web, however this presents a security risk.

**Additional context**

This is probably going to affect lots of HA users since 2023 is the year of the voice and more users will look to start interacting with HA using their voice.

The likes of [frigate-hass-card](https://github.com/dermotduffy/frigate-hass-card) also now support 2-way audio with some cameras and doorbells for which the microphone is required.

**Comment by dshokouhi** [comment]
I think this is specific to chrome. WebView does not offer these settings for users to adjust.

**Comment by jpelgrom** [comment]
https://chromium.googlesource.com/chromium/src/+/master/android_webview/docs/developer-ui.md#flag-ui WebView does offer flags but they don't include this one and are shared across all apps, not just HA.

![WebView Flags screen with 'secure' in search box but no results](https://user-images.githubusercontent.com/8148535/236299804-113efa40-25c0-45c5-bb8a-578980d18fc5.png)

Closing as non-feasible as restricting access to these features for insecure origins is intentional by the Chromium team so very unlikely to change in the future.
