### ISSUE TITLE
Multi Server support breaks/complicates tile usage

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/android#3529]
**Home Assistant Android app version(s):**

**Android version(s):**

**Device model(s):**

**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

Hey everyone,
after adding multi server support I now seem to have to re-do all my tiles.
For some reason I have to select the server for every single tile (which wipes my current tile entities) and then re-select the tile entities.
As the app still remembers the entities and only erases them after I select the mandatory server, there seems to be a bug.

In addition, IMHO, if only one server is registered in the companion app, that server should automatically be selected, hence also solving this issue for most users.

Thank you
Alex

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
Did you transfer the app to a new device recently or re-install it? It sounds like your tiles are still linked to an old server, which is why the app is asking for a server (as it thinks an invalid server has been selected).

> IMHO, if only one server is registered in the companion app, that server should automatically be selected

This is what is supposed to happen, if you have only one server the option shouldn't even show up.

**Comment by AleXSR700** [comment]
Nope, same mobile and same server. Did not uninstall anything.

I only have one server. I did recently try changing that servers address to https but then returned to http. But never added a second server.

And as I say, all tiles information is correct but it demands a server to be selected. And when I do, it suddenly forgets which entity I previously selected.

**Comment by jpelgrom** [comment]
Does it stop asking for a server after you select a server? For your example screenshots, if you choose your entity again and tap the update button, does it update correctly?

> I did recently try changing that servers address to https but then returned to http.

As long as you didn't use the "Add server" button it should be OK!

> all tiles information is correct but it demands a server to be selected. And when I do, it suddenly forgets which entity I previously selected.

This is correct, from a technical point of view. When the app doesn't know which server an entity belongs to (which is why you're seeing the choice), it will clear the selection after selecting the server to prevent non-existing entities from being selected.

**Comment by jpelgrom** [comment]
> it would be better to check if the entity_id is available on the selected server and then retain it. If it is not available, then erase it

I agree, submitting a change for it in a few minutes.

https://github.com/home-assistant/android/assets/8148535/17ac4d16-ebc6-4673-9609-de0f20404861

Unfortunately it'll be very hard to determine why it thinks your tiles belong to another server, I have just tested migration again and am not seeing this behavior. With the change, it should at least reduce your frustration (hopefully) (only entity ID was being reset).

**Comment by AleXSR700** [comment]
Hello @jpelgrom 
just a quick feedback that the entity now remains when selecting the server.

If possible, it would of course be nice if the app checked if there are multiple server registered and if not, automatically select the only one available :)

**Comment by jpelgrom** [comment]
> If possible, it would of course be nice if the app checked if there are multiple server registered and if not, automatically select the only one available :)

As previously mentioned, this is how it's supposed to work and it shouldn't even show the option but your data appears to not be linked correctly. Requiring you to select a server is only required once, and balances keeping stored data vs clearing (in)correct data on load, so this won't be changed.

**Comment by AleXSR700** [comment]
Sorry, yes, I meant that the app rechecks number of servers when clicking on "Manage tiles" and then fixes that data.

Can I somewhere check for you what is causing this? Or is the data only accessible as root user?

**Comment by jpelgrom** [comment]
Quoting myself here:

> the app doesn't know which server an entity belongs to (which is why you're seeing the choice)

As you didn't edit servers this might be due to a incorrect migration but at this point it's really hard to figure out what happened.

Re suggestion:

> the app rechecks number of servers when clicking on "Manage tiles" and then fixes that data

The app checks servers but plays it safe, which is why it is asking you to select a server _once_ to fix it but prevent data loss.

**Comment by AleXSR700** [comment]
```As you didn't edit servers this might be due to a incorrect migration but at this point it's really hard to figure out what happened.```
Yes, that's why I was asking where this information is being read from. I would assume the app is opening a specific file to see which servers exist and since there is an error in that file, it asks me to select one.

So if I know which file is the source of information, I can retrieve that file and check what might be causing the issue.

If that file is on the server and not stored on the Android phone, I should be easily able to access it :)

**Comment by jpelgrom** [comment]
It is in the app's database which isn't easily accessible

**Comment by AleXSR700** [comment]
> It is in the app's database which isn't easily accessible

Root only?
