### ISSUE TITLE
Extremely high battery usage with all sensors enabled/no external app features

### ISSUE THREAD

**Issue by deunlee** [home-assistant/android#3887]
**Is your feature request related to a problem? Please describe.**

When the HA app is installed, the phone's sensor information is collected and send to the server.
However, this behavior differs between Android and iOS.
iOS can turn off periodic update completely. But, it cannot be completely turned off in Android.

I don't know why there is the difference.
I just want to see the HA dashboard on the phone and I don't need to collect the phone state.

**Describe the solution you'd like**

Please add an option to turn it off like iOS.

<img src="https://github.com/home-assistant/android/assets/54697735/f5b62833-9093-41ee-bdaf-1f5822e2a583"   width="50%" height="50%"/>

**Describe alternatives you've considered, if any**

**Additional context**

It is also related to background battery use. I think it uses too much battery in the background.

**Comment by jpelgrom** [comment]
If you don't want sensor to update, turn off the individual sensors or use the website as an app instead of the full companion app.

Unless I'm mistaken, the iOS setting you're showing is for periodic updates "while the app is open in the foreground". It doesn't affect background updates.

**Comment by deunlee** [comment]
Even if I turn off all the sensors, the SensorWorker notification still seems to appear.

The iOS screenshot I posted says it's in the foreground, but when I go into the same menu (setting -> companion app -> sensors), it says it's in the background on Android, as shown below.

<img src="https://github.com/home-assistant/android/assets/54697735/b9316167-3d3b-4273-aa8d-1907a733e03d" width="50%" height="50%"/>

**Comment by jpelgrom** [comment]
> Even if I turn off all the sensors, the SensorWorker notification still seems to appear.

This is correct, because you can enable sensors on your server so the app still checks the server state. If you want to disable this check, disable "Remotely control app & device" in the server settings.

The notification might still appear because the app also periodically syncs information about the server and user for functioning of the app. If you want to hide the notification, you can use the "Manage sensor worker notification" link from your screenshot.

Once again, if you don't want any app features, don't use the full companion app and instead use the website :)

> but when I go into the same menu (setting -> companion app -> sensors), it says it's in the background on Android

Android and iOS have very different behavior for what apps can do, this is not the same setting. Sensor updates on Android always happen in the background.

**Comment by deunlee** [comment]
Thank you for quick reply :)

> If you want to disable this check, disable "Remotely control app & device" in the server settings.

I'm keeping it disabled and also turned off "Persistent connection". 

> If you want to hide the notification, you can use the "Manage sensor worker notification" link from your screenshot.

It's not just because the notifications are annoying. It uses the battery in the background.

> Once again, if you don't want any app features, don't use the full companion app and instead use the website :)

I'm using an automation that sends notifications to my phone triggered by certain sensors, so the website alone isn't enough.
As far as I know, notifications on Android use FCM, so there is no need to check them periodically in the background.


Are there any technical issues that make sensor updates completely disabled?

**Comment by jpelgrom** [comment]
With the settings you described, it is almost immediately finishing and not doing anything related to sensors (even if that is the title of the notification). A lot of apps have a periodic background task but may hide the notification. Battery impact should be negligible, if it is not you're likely facing a bug.

> As far as I know, notifications on Android use FCM, so there is no need to check them periodically in the background.

Correct, which are push based. The app is not polling for notifications.

**Comment by deunlee** [comment]
OK, I understand.

In my phone it runs almost in the background, but it's draining most of the battery.
I think this is a bug but I don't know how to fix it.
I don't use any features such as widget, and I only use it for dashboard and notifications.

<img src="https://github.com/home-assistant/android/assets/54697735/4c90c4d9-620b-42e5-b74d-6b6a9a95edf1" width="50%" height="50%"/>

**Comment by jpelgrom** [comment]
45% battery usage is a bug, yes, even if you enabled all features.

Can you check the app logs for any failures? What is the app's background access set to? Do you have the device in airplane mode perhaps (there is a known bug for that but no fix)?

**Comment by deunlee** [comment]
I did not allow background access. Also, it's not in airplane mode.
The logcat in the troubleshooting menu seems to be reset when the app is restart.
I'll wait until logs accumulate a bit.

**Comment by dshokouhi** [comment]
Do you have any live view cameras or streaming cards on your dashboard? There is an existing issue where the streams never stop and this ends up draining battery and causing high data usage. The only fix for now is to either remove them for your dashboard or leaving the app without them open or in view (i.e. navigate to a tab/dashboard without them before leaving the app).

**Comment by deunlee** [comment]
[Here](https://pastebin.com/raw/jMMXp2ic) is the log.

Unfortunately, it seems that if I quit the app, there is no log left, so I just turned off the screen and collected it while keeping the app in the foreground.

@dshokouhi There is no camera on my dashboard.
There are a lot of graphs, but I don't know if they use streaming.
Also, I am using custom components(Mushroom, button-card) downloaded from HACS. However they are just UI components.

**Comment by dshokouhi** [comment]
Not much to go by in the logs, they do show that we are not being super chatty.

> There are a lot of graphs, but I don't know if they use streaming.

so in the past I have seen users with a weather radar card or something similar that ended up being the source of the drain for them

Given that our official [battery drain steps](https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-app-battery-drain) do not apply here as you do not have any sensors enabled nor the persistent connection. Can you please follow our [start fresh steps](https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app) in order to rule out a bad data issue please? We have seen these steps correct battery drain issues in the past so we should try that here too.

**Comment by deunlee** [comment]
> Can you please follow our [start fresh steps](https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app) in order to rule out a bad data issue please?

It works. After checking for two days, battery consumption was normal.
Thank you :)
