### ISSUE TITLE
Notification history view

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/android#398]
Would be good to have a view of past notifications, although this might be better accomplished by storing notifications on backend and offering a frontend view so that its cross platform.

iOS has needed this for a long time.

**Comment by shbatm** [comment]
It would be nice, but maybe not practical or feasible, to show the notifications in the persistent_notification tray on the webview in the app.

**Comment by CodeFinder2** [comment]
+1 for this feature from me as well. Regardless of the solution for #372, very (I mean VERY) long messages are still not completely shown (which probably makes sense since it's just a notification 😁). To read them completely, one would probably need such a history view to be able to also view (arbitrarily?) long messages.

Also, IF there is a length limitation, a service call should properly fail for notifications exceeding this limit (to indicate this).

**Comment by shbatm** [comment]
Some Google-fu shows that the hard limit is 1024 characters, but what each device will display looks like it varies -- [example here](https://support.airship.com/hc/en-us/articles/213491643-What-are-the-Maximum-Characters-for-Push-Notifications-).
