### ISSUE TITLE
GPS updates to Ha freeze in three common situations

### ISSUE THREAD

**Issue by ShortRetired** [home-assistant/android#4136]
**Home Assistant Android app version(s):**
2023.9.2-full
**Android version(s):**
11 kernel4.14.193+
**Device model(s):**
nokia C01 plus model ta-1383
**Home Assistant version:**
2923.11.3
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
This bug relates to GPS updates from the phone device to Home assistant
The updates have been observed to freeze (ie stop updating the home assistant server) in the following situations
1. When transferring from home wifi to LTE mobile (problem goes away when wifi is disabled)
2. When the app updates the server after a long absence of gps signal ie greater than a few hour eg overnight) (problem is resolved by killing the app and restarting it)
3. When there is a temporary loss of gps signal such as walking beside a tall building. (This can be unfrozen without a restart of the android ha app by activating the owntracks gps app which seems to trigger something in android so that the ha android app then updates the gps position)
When these GPS freezes happen the app is still updating other sensors such as android battery level. 
I have made the app settings so that android is not trying to save battery by delaying GPS updates and the phone is plugged into power in any case.
These freezes make the tracking function so unreliable that it is of no value for most use cases. I need a GPS function that works when ever android has a GPS fix (even if its not perfectly accurate). 
I doubt that this issue has been fixed in any recent updates to ha or the android app but am willing to stand corrected. It has taken me 6 months of use of the app gps function to figure out the specific situations where the freezes occur. 

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
please share the location tracking history page when the issue occurs, we also need logs when the issue occurs including how long you have waited for things to restart as it takes about 15-30 minutes for tracking to restart when we detect updates from google have stopped. More information is needed to troubleshoot.

**Comment by dshokouhi** [comment]
> 2023.9.2-full

please also update to the latest app version

**Comment by ShortRetired** [comment]
Dear Daniel
Thanks for the lighting fast response. 
I think you might have to be more specific about what I need to collect. Where and what is the location tracking history page. And which logs do you need specifically. I understand ha logs but are there also android app logs? It is interesting that it takes 15-30 minutes for the app to start tracking again after google (you mean android os api stops updating don't you). How come when I bring  the opensource owntracks app to focus on the android ui it reports a position immediately even if it's not that accurate. 
It's quite onerous to debug this situation especially the wifi to lte transition-but I'll do my best. It will probably take a while :-)

**Comment by dshokouhi** [comment]
> Where and what is the location tracking history page

Settings > Companion App > Troubleshooting > Location Tracking

keeps track of all reports within the past 48 hours so you can see how frequent tehy are and if any failed. If they failed there will be a reason for it in the app logs, the logs are only retained recently so you'll need to check them soon after noticing the issue.



> which logs do you need specifically. I understand ha logs but are there also android app logs?

android app logs

Settings > Companion App > Troubleshooting > Show and share logs



> It is interesting that it takes 15-30 minutes for the app to start tracking again

We wait 15 minute because thats the fastest interval androids work manager will allow, thats only if we detect updates have stopped coming from Google.



> (you mean android os api stops updating don't you)

no Google Services

https://developers.google.com/location-context/fused-location-provider



> How come when I bring the opensource owntracks app to focus on the android ui it reports a position immediately even if it's not that accurate.

thats because teh app registers for passive updates which means anytime any other app requests location data we also get that. This would mean though that location tracking did not stop and there may just be errors in the logs that either need to be resolved or understood why it occurs. Only logs and tracking history will be of help here.

This page in the docs covers location tracking in depth:

https://companion.home-assistant.io/docs/core/location#android-location-sensors

The location history is covered in our troubleshooting steps:

https://companion.home-assistant.io/docs/troubleshooting/faqs#device-tracker-is-not-updating-in-android-app

**Comment by dshokouhi** [comment]
closing as we have not heard back from the author on the progress of troubleshooting
