### ISSUE TITLE
Minimal Companion App cannot add Matter-based devices

### ISSUE THREAD

**Issue by tommyserver** [home-assistant/android#4275]
**Home Assistant Android app version(s): 2024.1.5-minimal

**Android version(s): 13

**Device model(s): OnePlus 8

**Home Assistant version: 2024.3.1

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications: When i want to add a matter-device, the app tells me to use the companion app (same message as home assistant itself in the web interface). Since neither the matter docs ( https://www.home-assistant.io/integrations/matter/ ) nor the docs about the difference between the companion apps ( https://companion.home-assistant.io/docs/core/ ) do hint, that this is not possible with the minimal version, this seems like a bug in the minimal version of the companion app. With the full version from the google play store this issue does not exist and there you get to the next step (get the commision code) instead of the message to use the companion app.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
Matter commissioning is not supported with the minimal version of the app, as it uses Play Services. This is not a bug.

The prerequisites section in the core documentation hints at this, but I agree this could be more obvious (this looks like it was written by someone who doesn't understand the difference):

> Have an Android phone (a full Android, not F-Droid).

**Comment by reactormonk** [comment]
Would it be possible to reconsider the "not planned" part, as grapheneos has issues with the matter integration? https://github.com/GrapheneOS/os-issue-tracker/issues/2383

**Comment by RAYs3T** [comment]
especially with more matter devices in the wild, this becomes more important for grapheneOS. 

we have no non graphene device and can only pair devices with a Bluetooth dongle attached to HA. 

But moving devices nearby for paring is impractical for some.

**Comment by ilar** [comment]
Since other people are likely to be looking at this and wondering why Home Assistant effectively doesn't seem to support Matter for them, and seems to have no plan to, there is a workaround.

This example would be for Ikea's Temp/Humidity Sensors over thread. You will need Bluetooth, Thread, and Matter set up.

First, go to Settings -> Bluetooth -> Adapters -> click the "⚙" icon for one of your bluetooth adapters. You will need to set scanning mode to 'Active' for this. You will not want to keep it this way, there's some kind of bug in HA or BlueZ or somewhere that causes this to eventually break Bluetooth (requiring you to restart/unplug-replug the bluetooth dongle), but for Matter Commissioning we'll need it on.

Then go to Settings -> Matter -> Options.

The first time you do this, you will need to set your thread credentials. Head to Settings -> Thread and then click the "ⓘ" icon for your main thread border router. You will want to copy the 'Active Dataset TLVs'. Back in the Matter Options tab, click 'Set Thread Credentials' and paste the TLV in. You will only need to do this once.

Finally, you can click Settings -> Matter -> Options -> Add manually. The pairing code is either the MT:### code that you get from the scanning the QR code on the device, or the plain number ####-###-#### code on it. Either works. 

There will be no response, but just leave it alone. Within 10 seconds-ish, it should suddenly redirect you to the new device page for your matter device. If after ~5min or so passes, something has went wrong. You can look at Settings -> Apps -> Matter Server -> Logs to see, but keep in mind you will need to reset/restart pairing mode on the matter device to try again. At least on the ikea matter stuff, if there's a problem pairing, it will hang the pairing process until you restart the device.


EDIT: Oh yeah, and don't forget to go back into your bluetooth settings and turn the scanning mode back to 'auto.'
