### ISSUE TITLE
Android Auto - Allow Automations to be triggered when selecting somewhere to navigate

### ISSUE THREAD

**Issue by theverex** [home-assistant/android#4315]
**Is your feature request related to a problem? Please describe.**
No - this is a new feature request.

**Describe the solution you'd like**
The Android Auto App is quite handy already with the ability to toggle entities and use favourites, however I notice that there is a navigation feature that works great to be able to navigate to certain zones.

It would be great if we could trigger an automation based on the zone / location that is selected to navigate to. At the moment, we can only trigger when you enter / leave a zone, not when you are navigating to a zone.

I would love to be able to jump in the car, use the HA Android Auto App, select Navigation -> Home and and have automations run when selecting that zone.

EG: Turn on lights, send vacuum to home base, open blinds etc.

Alternatively, when selecting 'Work' zone, turn on vacuum.

**Describe alternatives you've considered, if any**
The only current way to do the above is to use location based automations (enter / leave), however there might be times I don't want the automation to run when I enter / leave a zone, only when I navigate to that zone.

**Additional context**
No additional context to add.

Thanks!

**Comment by dshokouhi** [comment]
we can probably send back an event when an item is clicked on from the car, not sure if that should only be in navigate entities or extended to actionable entities as well.

**Comment by theverex** [comment]
@dshokouhi it would be great to have it for navigation entities, but all entities would also be powerful because we could then build automations based on if 

I assume that the 'Android Auto' entity / attribute could work here as well, but if you can understand where the entity was clicked from, that could open up all sort of great automations!

**Comment by dshokouhi** [comment]
well the thing is that we dont do this behavior anywhere else and the expectation may be that if we implement this, things like widgets and device controls are very similar. I wonder if there is a better way to get the data you want. Have you tried using the Last Notification sensor to see if Google Maps gives you that information to go by? 

If that doesnt work you can also try adding an item to your favorites so you can execute the script or whatever you need before you start navigating. 

Some specifics need to be worked out here if we plan on adding this as we need to consider all other app features.

**Comment by theverex** [comment]
@dshokouhi understood about all entities - if a change could be made just for the navigation entity only, that would work.

I tried the last notification sensor, but two main issues in this use case with navigation:

1. Battery usage is high for immediate notification syncing with HomeAssistant
2. Google Maps app doesn't give useful information in the notification itself - it will show the turn by turn text but it won't provide the data needed in the notification to understand the destination location.

**Comment by DarkWolf7** [comment]
I've been wanting this exact feature for a while. Another use case would be sending a text (via Tasker) that I'm on my way home with an ETA (Tasker used to be able to do this by itself but Google neutered the feature), or setting the air conditioning to home mode to precool the house before you get home.

**Comment by NODeeJay** [comment]
I have a different use case
I want HA to become my semi-automatic "routing engine", since for example Waze only knows a single stop on the route. My idea for the automatic way works already, by calendar, shopping list or fuel level I check a couple of things and then send the Waze intent to set the destination. However, sometimes I just jump into the car and drive to one of my favorites in Android Auto, or I need to plan a trip to more than two destinations (the Waze issue). But now HA either does not know that I have a destination and sometimes overwrites my final destination by its "assumption" from calendar or shopping list, or, I want to plan a trip and would press the navigation targets after each other in the car. If each of them fires an event I could catch the events, store the different locations in helpers and set them as new target, each time a target is reached.

I assume the navigation feature is purely handeled on the device itself, HA Android app creates the intent with coordinates, HA itself does not know about it?

My use case would be fulfilled with an event.
