### ISSUE TITLE
Secure Notfications

### ISSUE THREAD

**Issue by iulko** [home-assistant/android#4451]
As #4447 was closed witchout good explanation, and I feel that companion app is being dragged down by "not planned" spam. So I have to make issue one more time.

Local push notifications are not the alternative to firebase notifications when they are super unreliable and drain battery. I saw many of issues here or on forum about that. Also there is no way to tell if the instance is even up because you said that "connection down" info will not be implemented because so much changes to the app was made. Its like a maze of "not planned" features that make it imposible to have a good, reliable app. What I suggest is best of both worlds and would render local push notifcations not needed in 99% of cases. Could you explain your decision to ignore such a obvious improvement? Atleast let this issue  stay open so I could offer some bounty for somebody.

----------------
What I propose

Notifications in HA app could not pass any informations in them for privacy sake, just wake up the app to fetch the data. The same is introduced in Signal app, this is a quote from CEO of signal:

"In Signal, push notifications simply act as a ping that tells the app to wake up. They don't reveal who sent the message or who is calling (not to Apple, Google, or anyone). Notifications are processed entirely on your device. This is different from many other apps. "

**Comment by dshokouhi** [comment]
> As #4447 was closed witchout good explanation, and I feel that companion app is being dragged down by "not planned" spam. So I have to make issue one more time.

instead of spamming multiple requests for the same thing the correct approach would be ask for more information and clarity when the original request is closed. As you literally created a duplicate I am going to close this issue. 



> Notifications in HA app could not pass any informations in them for privacy sake, just wake up the app to fetch the data.

if this is truly what you want then you need to start with creating a HA forum feature request as changes will be required for HA core to wake the device. From there the app can make whatever changes are required by HA core.

in the meantime you can create your own "wake the device" schedule and control local push using the existing notification command: https://companion.home-assistant.io/docs/notifications/notification-commands#persistent

more than likely the app will still continue to use a websocket connection to retrieve the notifications so changes from HA core will be required here.
