### ISSUE TITLE
HA Certificate Authority is not trusted when using Website Card error.

### ISSUE THREAD

**Issue by MarkHofmann11** [home-assistant/android#4577]
**Home Assistant Android app version(s):**
2024.7.3-full
**Android version(s):**
10
**Device model(s):**
Galaxy Note 9
**Home Assistant version:**
2024.08.01
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![meh3hnsfgezc1](https://github.com/user-attachments/assets/88e9a53d-bb8d-4ed1-9f5d-625aca962bdc)

**Additional information:**
When using Website Card and viewing in the Android App for HA, receiving "HA certificate authority is not trusted, please review the Home Assistant certificate or the connection settings and try again" error.  I'm not sure when this error started, but maybe within the last month or two.  It doesn't matter what URL you use in the Website Card, all get the error.  Viewing via Web Browser on the phone or desktop, there are no certificate errors and everything works fine.

**Comment by dshokouhi** [comment]
The companion app requires a valid certificate, you will either need to use a valid certificate or add the CA to your on device trust store to fix the issue. This is not an error that will be fixed by the app. Even if you dont get an error in a browser, the app will still get an error. You can try checking the companion app logs to see which exact URL has an issue but we still wont be able to fix that here.
