### ISSUE TITLE
Description for "Single accurate location" sensor badly worded

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/android#4705]
**Home Assistant Android app version:**
2024.10.1-full (beta)

**Android version:**
15

For the so-called "single accurate location" sensor the current description is found in

     sensor_description_location_accurate

The first sentence is a quite convoluted repeating the words "request(ing) an accurate location":

_"Allow Home Assistant to send a notification to **request an accurate location** along with the application periodically **requesting an accurate location**. …"_

I have a very hard time translating this into proper German (working on that in Lokalise) so it explains well what is actually meant here.
Perhaps someone with deeper knowledge of how this works technically can reword this a bit. This will certainly help anyone using this with the English UI, too.

As I understand it I would just write something like:

_"Allow the Home Assistant app to periodically send a notification to (???) to request an accurate location. …"_

But that might be completely wrong…

I consulted the Help page about this and did not find a useful hint either.

**Comment by jpelgrom** [comment]
I can see this being confusing, thanks for the feedback. Your suggestion makes it more obvious that it is not clear because it is incorrect :) 

This toggle controls two behaviors:

 - allow using the [`request_location_update` notification command](https://companion.home-assistant.io/docs/notifications/notification-commands#request-location-updates) (= Home Assistant/your server can request the device location now, instead of waiting for the device to report a location)
 - allow the app to actively get your location if needed, usually using GPS, instead of relying only on background updates

The result is the app actively getting a location which is most of the time much more _accurate_, and do it once (_single_).

(I'm thinking about how to rewrite this but doing it in one or two sentences is hard)

**Comment by NoRi2909** [comment]
@jpelgrom Thanks for the quick reply. 

Much clearer already: So it means the server sending a notification to the app, which triggers a single location services call at that moment – instead of the app having to continously monitor the location "just in case" the server wants to do something based on it.

Thus the "single" in the name. Correct me if I'm still wrong … ;-)

**Comment by jpelgrom** [comment]
> it means the server sending a notification to the app, which triggers a single location services call at that moment

Correct, that is the first bullet point in my comment.

> instead of the app having to continously monitor the location "just in case" the server wants to do something based on it

No, this is not intended as a replacement. You theoretically can, but there are some limits which make it impractical as mentioned in the linked documentation, especially if you want to be battery efficient or use zones.

**Comment by NoRi2909** [comment]
OK, so as a first step in coming up with a better wording the explanation could start with

"Allow Home Assistant **Server** to send a notification to request **the current** location …"

instead of the current wording without "server" and repeating "accurate location".

I stay tuned for the rest. ;-)
