### ISSUE TITLE
The HomeAssistant app does not connect to the server when WireGuard VPN is active on my phone.

### ISSUE THREAD

**Issue by NyariG** [home-assistant/android#4852]
**Home Assistant Android app version(s):**
2024.10.3
**Android version(s):**
12
**Device model(s):**
S61Pro
**Home Assistant version:**
Core
2024.11.3
Supervisor
2024.11.4
Operating System
13.2
Kezelőfelület
20241106.2

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

I have a WireGuard server running on my router, and the WireGuard app is also installed on my phone. When I activate the connection, I can access all my home devices. However, when I launch the Home Assistant app, it loads for a while and then displays an error saying it cannot connect to the server. I assume this is because it is not trying to connect using the internal IP but rather the external URL. I couldn’t find any settings in the app to specify which address it should use when a VPN connection is active.

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
Internal/external URL switching in the app only uses your Wi-Fi information. If you always want to use the same (internal) URL, don't add another one.

Using VPN status to determine the URL to be used is an existing request in #4780 - but the HA app doesn't integrate with 3rd party apps like WireGuard.

**Comment by dshokouhi** [comment]
> Testing my instance via chromium on android results ina connection failure too (home wifi with wg)

That's not an app bug if it happens on a browser in the same device. 😉 SSL error is not an error the app can solve. Based on your research given the fact that you only use one URL the app is working as expected.

**Comment by dshokouhi** [comment]
the SSL error comes from the network call, the app cannot fix that at all.

> Testing my instance via chromium on android results ina connection failure too (home wifi with wg)

 As you said the issue also happens in chromium you need to solve that before it works in the app. The app does not expect to get any SSL errors, those can ONLY be solved on the client end.

Try this bypass your VPN, if it works the issue is with VPN. The app just uses the URL as normal and expects it to work without any HTTP or SSL errors. The app is not in control of your server nor your network setup, those 2 are controlled by the user.
