### ISSUE TITLE
Search settings is broken

### ISSUE THREAD

**Issue by TheCarpetMerchant** [home-assistant/android#4885]
**Home Assistant Android app version(s):** 2024.10.3-full

**Android version(s):** 13

**Device model(s):** A55 5G

**Home Assistant version:** Don't know where to find it, 3-days old Raspberry 4 version.

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Searching for "notifications" after tapping the search icon in Settings does not give any results.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
can you please share a screenshot of where you encountered the issue?

**Comment by TheCarpetMerchant** [comment]
![Screenshot_20241212_093147_Home Assistant.jpg](https://github.com/user-attachments/assets/3a8221d1-2ce4-4132-8034-d22a68c4f552)

![Screenshot_20241212_093158_Home Assistant.jpg](https://github.com/user-attachments/assets/533b4c66-95d7-4054-883c-0499e2829b99)

This is in Settings -> tap the search icon.

**Comment by jpelgrom** [comment]
Unfortunately this is by design / a technical constraint. For the app settings you _must_ tap on Companion app, the main interface doesn't know about the options in there.

I can see how this might be confusing, so I suggest submitting a feature request for the frontend: https://community.home-assistant.io/c/feature-requests/13.
