### ISSUE TITLE
Cookies support for html pages in webpage card

### ISSUE THREAD

**Issue by radokk** [home-assistant/android#548]
**Home Assistant Android version:**
1.8.0-144
**Android version:**
10
**Phone model:**
Samsung Note 10
**Home Assistant version:**
0.108.1
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
Hello, I added simple webpage card to lovelace (it's public transport time table). It's ok on my laptop, but in Companion App (android)  it's telling me that I need to enable cookies. Page loaded, but I have it covered with that cookie notification.  
When I signed to HA via chrome browser on mobile phone, same webcard asked me if I want to accept cookies. Once accepted, webcard loaded page without any notification properly.

Is it possible to add to Companion support for cookies?  

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
Lovelace card in Companion with cookies notification:

![image](https://user-images.githubusercontent.com/60854491/78921498-4a17a200-7a95-11ea-90fe-03c06dcc1afd.png)

Notification in black: 
![image](https://user-images.githubusercontent.com/60854491/78920841-50594e80-7a94-11ea-9963-d144f9cfe6aa.png)
Translation: Enable cookies in browser to get fully functional page. 

Lovelace card in Android chrome web on my mobile phone once cookies were accepted. 
So in browser, it asked me if I want to accept cookies, but in app is telling me cookies support is not enabled. 

![image](https://user-images.githubusercontent.com/60854491/78921567-6287bc80-7a95-11ea-9a28-250afe01a2d3.png)

**Additional information:**
Pages I added to lovelace: 
1) https://bit.ly/2RlAvuw
2) https://bit.ly/39XQ8i6

**Comment by N1c093** [comment]
Would be a great feature :)
I need the cookies to save my authentication credentials for an webpage in the iframe.

**Comment by smithbill17** [comment]
I appreciate this issue is closed, but my experience using Home Assistant 0.115.1 freshly installed on Raspberry Pi 4b, indicates that the issue is still present.

I'm using Chrome 85.0.4183.101 installed on Android 10. I am not using Home Assistant with SSL.

With a Web Page card for  http://www.itv.com/news  it constantly requests allowing Cookies.  I've tried enabling the Chrome Flags for #same-site-by-default-cookies, #improved-cookie-controls & #improved-cookie-controls-for-third-party-cookie-blocking as well as switching Chrome to allow all 3rd Party cookies. Nothing works.

If I install Firefox, it works perfectly with the iframe cookie being stored and not re-requested on page refresh. But I don't want to use Firefox just for Home Assistant.

Given that 90% of Android users use Chrome, shouldn't this just work? Can we re-open this issue?

**Comment by smithbill17** [comment]
Sorry - I should've clarified:  I'm using the Chrome **web-browser** on Android 10 to access my Home Assistant installation on the RPi4b.  If I use the Home Assistant 'app' installed from the Playstore, then the cookie is saved correctly (but if I revert back to using the Chrome web-browser, the cookie problem remains).

**Comment by dshokouhi** [comment]
@smithbill17 this repo is for the Android app only, if you experience an issue in the browser then you need to open an issue with the frontend.

**Comment by fraintt** [comment]
@radokk Have you solved this? I would like to add the station-view as well, Im fighting with this, the cookie accept, and now also with the location permission.. 

Insane that DPB or imhd.sk do not have an public API.. -.- 

Thanks.

**Comment by filipondra** [comment]
@fraintt @radokk have you solved this? I'm struggling with the cookies on imhd.sk aswell

**Comment by radokk** [comment]
Hi,
I didnt do anything special, but after some HA update its working for me.
I do not remember details, version or so. I have  latest vereion of HA

Rado

Dňa po 4. 3. 2024, 9:46 filipondra ***@***.***> napísal(a):

**Comment by fraintt** [comment]
Hello, 
I do not use the view anymore.
