### ISSUE TITLE
Self-signed SSL is not supported

### ISSUE THREAD

**Issue by pipip** [home-assistant/android#589]
**Home Assistant Android version:**
1.9.0-167

**Android version:**
9.1.0

**Phone model:**
Honor 7x

**Home Assistant version:**
0.109.6

**Last working Home Assistant release (if known):**
none

**Description of problem:**
- Connection via the Android app with self-signed certificate (https://www.home-assistant.io/docs/ecosystem/certificates/tls_self_signed_certificate/) does not work
- Connection via Android browser with self-signed certificate works fine
- Connection via the Android app without SSL works fine

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**
Maybe add a switch to allow "not safe" certificates in the app settings? (ignore SSL errors)

**Comment by dshokouhi** [comment]
The app won't work if you have to accept the ssl certificate, can you try these steps?

https://companion.home-assistant.io/docs/troubleshooting/faqs/#using-a-self-signed-certificate-leads-to-a-blank-page-in-android

**Comment by pipip** [comment]
@dshokouhi 
Thanks for you fast feedback.
I have just tried that again:
- Deleted cache/app data
- Imported certificate (it is listed under user certificates)
- Start HA app --> error: "Unable to communicate with HOme Assistant because of SSL error. Please ensure you certificate is valid"

**Comment by j3ffpa1n3** [comment]
I'm having the same issue. Followed instructions in first link to create .crt file, imported using steps in second link, still get error message: "Unable to communicate with Home Assistant because of SSL error. Please ensure you certificate is valid"

CRT Steps: https://coderwall.com/p/wv6fpq/add-self-signed-ssl-certificate-to-android-for-browsing

Cert Import Steps: https://support.google.com/pixelphone/answer/2844832?hl=en&visit_id=637256100715376070-1062021008&rd=1

**Comment by uxdesignerhector** [comment]
I remember having the same type of problem. You need to change access permissions to files in SSL folder as it stated in the link you have posted [Certificate Authority and self-signed certificate for SSL/TLS](https://community.home-assistant.io/t/certificate-authority-and-self-signed-certificate-for-ssl-tls/196970)

` sudo chmod 600 fullchain.pem privkey.pem`

I remember that there were a clear and easy tutorial about Self Signed SSL in Hassio documentation but it can't found it anymore, maybe it's gone.

**Comment by Elkropac** [comment]
Hi,
the certificate has to be generated "properly". So it has to have subjectaltname and CA extension.
When you import it to android, you can test it in chrome. It should not complain.

I used this command to generate it
```
openssl req -new -x509 -days 3560 -key privkey.pem -out fullchain.pem  -config req.conf
```

req.conf contains
```
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_ca
prompt = no
[ v3_ca ]
basicConstraints = critical,CA:TRUE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer:always
subjectAltName = @alt_names
[req_distinguished_name]
C = CZ
L = Location
CN = hassio.example.net
[alt_names]
DNS.1 = hassio.example.net
```

**Comment by pipip** [comment]
thanks for the ideas but they do not work.
I use letsencrypt now... that works fine :)

**Comment by api2001** [comment]
Hi,
this would really be worth a fix.
I use a private VPN connection (because this is really safer than port forwarding stuff) but now I struggle with this self-signed certificates. Of course my local homeassistant box neither has a valid www-domain nor is directly connected to the internet.
It would be great if there was an optional setting in the app "[x] I know what I do and would really like to accept this certificate" , hidden somewhere, where unexperienced users do not accidentally set it.
I also tried manually importing the HTTP server's ssl certificate to Android but this did not work.

**Comment by kabo** [comment]
I'm in the same boat as api2001. Would be useful to be able manually accept self-signed certificates.

**Comment by api2001** [comment]
Hi,
I solved it now by creating a local CA (certificate authority), creating local SSL keys signed by this CA and import the CA certificate to the list of Trusted CAs on my phones:

Create SSL/CA for local usage:
https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/

Add CA cert to Trusted CAs in Android:
https://www.lastbreach.com/blog/importing-private-ca-certificates-in-android

This is a bit more effort but acceptable and just works.
api

**Comment by kabo** [comment]
Thanks @api2001 !
I was able to create a CA and cert using the guide. However, after installing the myCA.pem on my phone, I still get the same error from the home assistant android app :/

**Comment by kabo** [comment]
Deleted cache, deleted app storage, uninstalled app, rebooted phone, reinstalled app, same issue. I've double checked that HA is serving the cert issued by my CA. Hmm...

**Comment by kabo** [comment]
Ah, got it working. The extfile is not optional when generating the cert, and since I'm using an IP to connect to it worked once I set

```
[alt_names]
IP.1 = xxx.xxx.xxx.xxx
```

Thanks!

**Comment by api2001** [comment]
Great! However for all non-IT-professional users it would be great to have the option to accept the self-signed certificates as well!
+1

**Comment by Elkropac** [comment]
@api2001 it worked for me, with self-signed, as i wrote before. It's important to have subject alt name in your cert, otherwise chrome won't accept it as valid

**Comment by rs443** [comment]
+1 !

I would also like to see it possible to use self signed certificates, without the hassle to manually import it to the local certificate store.

Also, on my childrens phone running Google Family Link (parental managing system), importing certificates is disabled.

Managing letsencrypt certificates, autorenewing and so on is way to advanced, even for the more advanced users.

**Comment by Lovely-Maisonette** [comment]
Terribly frustrating (and I am an IT professional), it does not work onno matter what, delete cache, different certificate chains, nothing.

I just use it internally, no proxy, no router. Just direct connection in a private network with a self signed certificate everywhere.
I even tried Elkropac's example to the last detail. new cert, HA restart... Web browsers have no problems (after accepting the warning), this app, even with the certs installed in Android, fails with Unable to communicate with Home Assitant because of a SSL error.

The app should have an option (central or interactive) like any other https capable app, Firefox, Chrome, curl, wget, Mosquitto, Caddy Nginx, etc. to bypass certificate validation. self signed certificates need no validation

**Comment by mvdwoord** [comment]
+1
Would like to see an option where HA possibly generates a self signed cert, or allows you to add one you generated yourself, using default tools. Then have the app simply allow for these to work, using some sort of option to ignore SSL errors.

**Comment by dshokouhi** [comment]
The app will not ignore SSL errors, we have already made the decision not to allow it https://github.com/home-assistant/android/issues/448#issuecomment-724724968

I am going to close this now as we cannot allow bypassing certificate errors.  There are also several solutions offered in the comments so others who come by can look into alternatives.

**Comment by ondras12345** [comment]
I don't think adding a system-wide CA and potentially compromising the security of the whole system is a good solution. We don't need to ignore SSL errors, just add an option to specify a custom certificate that will be trusted even though it it self-signed.

**Comment by iamdaniu** [comment]
> If we were to ignore SSL errors you are just as vulnerable as someone using unencrypted traffic.

Well since SSL is unusable as is, I guess we _will_ be using unencrypted traffic for the time being.
I'm not sure how that improves the users' security.

**Comment by Lovely-Maisonette** [comment]
This makes no sense. The user is the one who can decide if a self signed certificate is trusted or not. Ask the user, as firefox or any other app does. Going unencrypted is the security risk.
