### ISSUE TITLE
Notifications on Android without Internet

### ISSUE THREAD

**Issue by angeltonio** [home-assistant/android#592]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
In some countries Google blocks access to its services, such as the Firebase server, so notifications for HA are useless, in addition to not all countries having cheap internet and sometimes HA keeps working offline

**Describe alternatives you've considered, if any**

What possibility would exist to enable any option to access these notifications without the need for Internet access and offline using only the wifi of a house. 
Are there ways that perhaps by accessing the Rest APIs we can implement any of these functionalities? Perhaps allowing access to notifications by MQTT. Greetings and thanks for your great work

**Comment by balloob** [comment]
This is out of scope of what we want to offer with our Android app.

**Comment by angeltonio** [comment]
Well I going to convence another people to create a fork with that...

**Comment by R5fan** [comment]
Humble request to reconsider the scope. Particularly for wall mounted panels, it would make so much more sense to have local control using MQTT or REST, instead of (ab)using android notifications which require internet access and a cloud round trip, can be painfully slow, are throttled and actually cost someone some money.  Use cases include things like controlling the screen (turn on synced with lights and upon PIR motion detection in the room), navigating to a specific view (eg open camera view when doorbell is pressed),  TTS messages,.. 

Wallpanel is an alternative that does provide MQTT and REST for those things, and local control is the only reason I still use it. For pretty much everything else companion has become far superior, so I end up using both :/
