### ISSUE TITLE
Fix "Zone Based Tracking" to only track zones, not exact coordinates

### ISSUE THREAD

**Issue by adarazs** [home-assistant/android#670]
**Home Assistant Android version:** 1.11.0-215

**Android version:** 9

**Phone model:** OnePlus 5

**Home Assistant version:** 0.112.2

**Last working Home Assistant release (if known):** n/a

**Description of problem:**

The `Zone Based Tracking` option heavily implies that the exact location won't be shared with the HA instance, just the zones, calculated phone-side. I realized a bit late that it still means that very accurate location data is shared. I think there should be a separate option on the app for "Share exact location" in the location settings.

I consider this as a bug, as it's really unclear for users who install the companion app that they will be fully tracked. I think most users of HA are privacy conscious, and don't want to track all their family all the time, just use the app to automate certain geofenced locations. At minimum the current behavior should be clarified in the app.

I found this topic that discusses this problem, as it seems I'm not alone with my expectation, or the need for less invasive tracking: https://community.home-assistant.io/t/how-to-use-location-tracking-only-to-detect-home-away-states-without-knowing-the-exact-location/187038

**Comment by dshokouhi** [comment]
So one thing to keep in mind is that in home assistant these device trackers are GPS based trackers.  The zone based tracking option only pulls in zone data into the app to setup geofences, hence the import.  The geofences are used to determine how quickly an update should be sent out by the app.  This is for faster entry/exit of the zones to be notified to HA but again we are just sending GPS coordinates because that is what the device tracker expects and that is how zones work in HA.  What you are asking for when it comes to zones is not possible.  HA core itself takes the GPS coordinates and designates when a device is in a zone.

If you are looking for only home/away then consider another device tracker and disable the device tracker for the mobile app.

**Comment by adarazs** [comment]
>  What you are asking for when it comes to zones is not possible.

That doesn't seem right. The phone app has the zones as you say for geofencing. So it knows both the zone centers, radii and its own coordinates. It should be a relatively simple calculation if the current GPS coordinate is within the radius of the zone's center point on the app's side. I.e. here's a simple implementation: https://stackoverflow.com/questions/365826/calculate-distance-between-2-gps-coordinates

This is akin to saying that all you know is that you're putting cereal and milk in your empty bowl, so there's no way to know what you're eating. :)

Can you explain more the technological limitations why this is impossible?

Currently I'm doing this with a simple Tasker profile and an enter/exit condition, where I set home/not_home for a device tracker through REST API. Works fine, but it would be very handy to have this in the Companion app. But even if it's not implemented, please consider clarifying in the app that full location is sent when enabling the "zone based tracking".

**Comment by dshokouhi** [comment]
Just keep in mind you are asking for the logic of the device tracker to leave HA core and stay within the android app.  You need to also consider that a GPS based device tracker needs to send its GPS data for HA to perform the calculation you are talking about.  Don't forget there are other device trackers outside of the android app that also does the same thing and depend on this.  The logic lives within the [zone](https://www.home-assistant.io/integrations/zone/) itself and you can see that longitude and latitude are required.

https://github.com/home-assistant/core/blob/dev/homeassistant/components/zone/__init__.py#L136

When you use tasker to just send the zone name instead of GPS thats all your doing.   You are arbitrarily setting the location name instead of letting HA do the calculation and placing the device in the zone.  If that is what you want then you should consider using tasker for this purpose because that is how `device_tracker.see` service works when you create your own entity.  You are in control of your own logic there.

> But even if it's not implemented, please consider clarifying in the app that full location is sent when enabling the "zone based tracking".

Actually full location is sent the moment you grant location permissions for the app.  These toggles are only to speed up the update.  I believe during onboarding when we ask for location permission we mention this there.  The user is explicitly granting location permission of their device to the app when they accept the prompt.

**Comment by adarazs** [comment]
Thanks for the explanation, @dshokouhi. You're making good points regarding how much easier it is to let Home Assistant Core handle the zone calculations.  I understand the concept of these various GPS trackers, however I never used any of them, exactly for privacy reasons. If I would be the only user of my HA instance, it wouldn't matter, but I don't want to fully track other users of the home automation.

I guess the right thing to do here is to open a separate issue with an feature request for this to be implemented on the app-side, as it seems to me that doing these calculations phone side is not impossible, just "duplicating functionality" from HA Core. Usually that's not great, but in this case it would serve a good purpose, namely increased privacy, by the coordinates not leaving the phone. 

Do I understand it correctly that this is possible as, the zone centers and radii are known?

> I believe during on-boarding when we ask for location permission we mention this there. The user is explicitly granting location permission of their device to the app when they accept the prompt.

Huh, okay, I think I installed the companion app very early on before the on-boarding part was added to the app. In this case I will close this issue, but I'd still like your input on whether it's worth asking for a proper phone based zone tracking.

**Comment by pepjo** [comment]
@adarazs did you open a separate issue with a feature request for this? I have the same concerns you have and I am surprise that this feature is not available on HA.

**Comment by adarazs** [comment]
@pepjo I did not open an issue about it, sorry. My Tasker automation and a REST API call to update things in HA worked solidly over the years when entering/exiting zones, so I did not need it that badly. However it would be still neat to have this in the companion app, so please open an issue if you feel strongly about it, I'd +1 it. :)
