### ISSUE TITLE
Storage sensor not picking up my SD card

### ISSUE THREAD

**Issue by jesserockz** [home-assistant/android#763]
**Home Assistant Android version:** 2.1.1-14-gf04f846-263-full

**Android version:** 10

**Phone model:** Motorola Moto One Vision

**Home Assistant version:** 0.114.0

**Last working Home Assistant release (if known):**

**Description of problem:**
New storage sensor not picking up my SD card storage.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

![Screenshot_20200815-131054](https://user-images.githubusercontent.com/3060199/90302286-3d9ace80-def9-11ea-8ff2-7fa4deda9bfe.jpg)

**Additional information:**
I have a 32GB SD card in my phone and FX File manager can see it just fine.

Does it have to do with HA Android not having storage permissions?

Related to #750

**Comment by dshokouhi** [comment]
Could you please tell me the full path to the SD card for your device? I think certain manufacturers may use a different path than what is default.  I was talking to another user and he has a Samsung device with the same issue.  We may need to get a list of SD card paths so we can see which one is mounted.  Unfortunately the android emulator does not have a SD card and I only have Pixel devices here.  This one may be a little bit difficult since Google just deprecated the API that made this easy, for privacy concerns.

https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory()

Thanks for reporting the issue!

**Comment by jesserockz** [comment]
Here is a screenshot:
![Screenshot_20200815-133201](https://user-images.githubusercontent.com/3060199/90302655-cadf2280-defb-11ea-8ff6-3985ce319d3c.jpg)

**Comment by dshokouhi** [comment]
Do you have ADB access by any chance? I may have a fix for this but need to read the response.

in `adb shell` type in `printenv` then I need the full line that lists the path to your external storage.

You should see something similar to `EXTERNAL_STORAGE=/sdcard`

**Comment by jesserockz** [comment]
Yeah, got these (removed the other unrelated lines)

```
SECONDARY_STORAGE=/storage/sdcard:/storage/usb1:/storage/usb2
ANDROID_STORAGE=/storage
EXTERNAL_STORAGE=/sdcard
```

**Comment by dshokouhi** [comment]
darn didn't give the value we were expecting :( i'll need to spend sometime to think of a proper solution for manufacturers that override the default.

**Comment by jesserockz** [comment]
I was just playing with it on my phone.

First point is that `Environment.isExternalStorageRemovable()` is returning false
Second point is `context.getExternalFilesDir(null)` returns the directory on local storage not the SD card.

Not sure how to solve the first, but the second can be solved:
`context.getExternalFilesDirs(null)` (notice the `s` at the end of `Dirs`) returns an array of storage directories. 
The second item in that list on my phone was my SD card, and if I get the `StatFs` for that path then the rest works as expected and I get the correct storage values.

You probably could use just that array and iterate it for all available storage media on the device. Maybe...

**Comment by jesserockz** [comment]
The same array can be used when I have a usb flash drive plugged into my phone at the same time. But there is no guarantee on the order of them.

<img width="1051" alt="Screen Shot 2020-08-15 at 11 01 28 PM" src="https://user-images.githubusercontent.com/3060199/90311049-503df380-df4b-11ea-9279-55c91d0d9eb2.png">

**Comment by dshokouhi** [comment]
Thanks @jesserockz yea so the first point actually needs to be resolved first as we need to ensure the storage we are checking is indeed removable.  I'll need to see if we can get that list during our condition check and then loop through and see which one is removable.  In terms of the USB device that may be tricky but we can see how that plays out.

**Comment by dshokouhi** [comment]
So in terms of having a USB drive, I don't see that as a typical use case because when you have your phone in your pocket how often do you keep it plugged in to the drive :) I think most users will just have an SD card and I believe I have a fix for that.  There is one caveat that if you do have a USB drive plugged in then the reading may not be right.  The only thing I am not certain of is devices that have an internal SD card, usually those are not removable but I don't have a device like that to test.  I think I will submit this as a quick fix to get some real values for now.

Thank you for your getting back to me and troubleshooting what I did :)
