### ISSUE TITLE
Replacing the Home Assistant Icon in Notifications 

### ISSUE THREAD

**Issue by shokwaav** [home-assistant/android#793]
Home assistant notifications are great to inform me of what's happening at home, but with the current system, I have to unlock my phone to view the text of each notification. I thought the method described [here ](https://companion.home-assistant.io/docs/notifications/notifications-basic/#notification-icon) in the docs would replace the notification icon, but it instead displays it over the right, similar to where the image would go.

I think a method to replace the home assistant icon in the notification would be helpful, so I can glance at my phone's AOD and immediately see what's happening, and then decide if I want to unlock my phone to see the details.

I'm not too familiar with how Android notifications work, so I understand if custom uploaded icons may not be an option, but an option to choose from the material design icons would already be much more flexible. 

(I'm talking about the small icon at the top left of each notification. The current system only changes the picture at the right)

![Tge6W](https://user-images.githubusercontent.com/41905519/90709335-87efc700-e2ce-11ea-9222-e0b03ec303f7.png)

**Comment by chriss158** [comment]
I understood your intentions for changing this icon to something different. But i think this icon should be a fixed home assistant icon. Just to see which app send this notification. But that just my opinion.

**Comment by klejejs** [comment]
I agree. That icon is ment to see which app the notification is from. It is not supposed to be changed.

**Comment by shokwaav** [comment]
That's not true though.

Google and Whatsapp have different icons shown there. Google shows their weather icon there, while Whatsapp shows a little computer icon when Whatsapp web is in use.

**Comment by shokwaav** [comment]
You can see which app sent you the notification because it will still mention "Home Assistant" next to the icon, but I feel that allowing more information be available at a glance would make notifications much more helpful.

**Comment by dgwood12** [comment]
I agree that this feature would be a great one to implement. As to some of the arguments that the icon should not be changed as it shows which app the notification comes from I am not sure they understand the reason for doing this. With home assistant becoming the go to for many people's home automation, interaction between their home and phone is vital. Implementing many automations in my home assistant server, I want to be notified on my smart phone of certain events taking place. With the possibility of dozens of different instances my phone would be notified (Front door opened, kitchen light turned on, 3d printer powered down just to name a few), it makes sense to allow customization of the notification icon. I want to be able to distinguish the event by glancing at the notification icon (color customization does this too but not to the same extent). 

For those who are saying you shouldn't be able to change the icon, what's the harm in allowing users who want to customize the icon to do so? The notification already clearly says "Home Assistant" in the notification heading and users can very easily in android long press the icon to see what app is displaying the notification. The purpose of home assistant is to allow users to take control of their smart homes and home automation. Restricting changing the icon for others who want to change it because you feel a certain way about how icons should work on android doesn't make much sense to me. If I make it a custom icon, when I see that icon i'm going to know what app its coming from. The default would be the home assistant icon anyways so users who are less savvy or don't want to change it wouldn't get confused.

For users who want this feature, there is a work around by using the Join API (an app by joaoapps who is now the developer of tasker) in node red which allows this. It's a pretty powerful tool but I certainly would like this a lot more if it were implemented natively. +1000 from me to add this to the home assistant android app.
