### ISSUE TITLE
Geolocation Sensors - Geocoded Location cached?

### ISSUE THREAD

**Issue by Thrasher2020** [home-assistant/android#836]
**Home Assistant Android version:**

2.3.0-306-full

**Android version:**

10

**Phone model:**

Pixel 3

**Home Assistant version:**

Home Assistant 0.114.4

**Last working Home Assistant release (if known):**

**Description of problem:**

Geolocation Sensors - Geocoded Location changing to a previous zone and even making google maps think I've relocated back to the zone. I'm not sure what the app is doing but it's certainly confusing my phone. I can't use the Zone functionality at all now, it keeps deciding I'm at work, then home. It does not, however, put me at any other zones that I have not visited. It's only seems to be recently visited zones and seems to hang about for 24-48 hours. 

It's almost as if it's remembering where I have been and then telling the phone I am there - thus confusing google maps too. Hope this is enough info. If you need anything else just ask.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

I can supply if needed but I think the text description covers it.

**Additional information:**

**Comment by dshokouhi** [comment]
The geocoded location sensor is not meant for zone based tracking, use the device tracker instead.  Also check the manage sensors screen and make sure both location toggles are enabled.

**Comment by Thrasher2020** [comment]
I have tried both - and both are putting my phone in the zone I am not in - see screenshot. The light blue is "work" - I am working from home right now and haven't been the work zone since midday yesterday.

![image](https://user-images.githubusercontent.com/65713394/91583954-d6920680-e949-11ea-91db-ba3cef5dbdc1.png)

**Comment by dshokouhi** [comment]
So that data you see there...is the GPS coordinates correct? The app goes by the GPS accuracy that is reported and you can see its set to 20 which is well within the 200m range.  If you open up google maps do you see the correct value get reported?  Thats a really odd issue since we all have pixels and dont see teleportation issues.

**Comment by Thrasher2020** [comment]
Hi,

The GPS data is bang on the middle of my office 15 miles away. Let me show you 👍 

![image](https://user-images.githubusercontent.com/65713394/91584389-79e31b80-e94a-11ea-89d1-56331b94fea6.png)

and at "home"

![image](https://user-images.githubusercontent.com/65713394/91584597-c9c1e280-e94a-11ea-9001-5237d9a88f3f.png)

**Comment by Thrasher2020** [comment]
If I open up maps, wait 10-15 seconds, I am magically teleported back to "home". Then for some reason the app will put me back exactly at my work address after a random amount of time.

**Comment by eyager1** [comment]
I am having a very similar issue since upgrading to 2.3.0-306.   When I leave one zone and enter another the location changes alternately rapidly back and forth between the two for 1-5 seconds.   It spams the log book with up to 15 location changes.   

I have the geolocation sensor turned off in the app.   I have zone and background location turned on.

**Comment by dshokouhi** [comment]
We have made a lot of improvements to location tracking, I am going to close this now as you are probably already on the latest version with all the new fixes.  If you still face an issue please open a new issue with details about the issue.
