### ISSUE TITLE
Lovelace Card Widget

### ISSUE THREAD

**Issue by yaroto98** [home-assistant/android#839]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The Widgets in the app seem too limited. What I would like to see is a Widget where I can choose from a list of existing Lovelace Cards and make one of them the Widget. Clicking on the widget would bring up the app into the same page that comes up when you click on the card in the app.

Example: I can have 2 widgets on a page in Android. Top one is my weather card from HA, and the bottom one is a my thermostat card.

**Describe alternatives you've considered, if any**

One of the annoying parts of HA is that there is sooooo much I have in it that I want it easier to get to. Itt annoying to get into the app and go over to the page I want, and scroll down to the card. Not only does it make HA more available and easier to access, but its much quicker too.

**Additional context**

**Comment by skynetua** [comment]
We are not able to add it directly as you proposed. Android widget does not support webview, so it can be only imitation of lovelace card.

**Comment by yaroto98** [comment]
I'm no mobile developer, and don't know how to best implement the feature. I'm just here to say that this would be an awesome feature. An imitation or if you need to take individual Lovelace cards and write a Widget for each kind to take the data and display it in a pretty way is up to your developers. I'm just pointing out a desired feature as a user.

**Comment by dshokouhi** [comment]
So one thing to keep in mind about this great idea is the tendency for the widget to be out of sync with HA.  I don't think it would be useful if the data is updated every 15 minutes because that is currently how the entity state widget works.  We don't want to check into HA so frequently due to battery and other concerns and there is no way for HA to push those updates to the device currently.  One thing you can do today is to navigate to a lovelace view via the notification, I wonder if a app shortcut to a lovelace view would be helpful instead? It would get to your updated destination faster.

**Comment by LuxStatera** [comment]
How did you add a thermostat widget?
