### ISSUE TITLE
Translations for the entities states

### ISSUE THREAD

**Issue by anybody84** [home-assistant/android#855]
**Is your feature request related to a problem? Please describe.**
It's very nice that each new release introduces new sensors, but the issue is that there are no translations for the entities states. They are always in english (e.g. 'idle' for the phone state or 'tilting' for the detected activity), no matter what language is set up in HA.

**Describe the solution you'd like**
It would be good to have the entities states also translated to the local language.

**Comment by balloob** [comment]
So this only impacts sensor entities that have string values. 

For those, we should be able to leverage https://developers.home-assistant.io/docs/internationalization/core#stringssensorjson

- It will require us to have an integration in HA, ie `android_app`
- It will require `mobile_app` to set up the related integration that the registered device so that `android_app` gets loaded
- Sensors that need to be translated need to get a device class like `android_app__phone_state`
- Translations need to be added to `android_app` so they will become available in Lokalise
- Community can translate in Lokalise
