### ISSUE TITLE
Race condition beween next_alarm sensor and homeassistant can prevent automations from firing 

### ISSUE THREAD

**Issue by eyager1** [home-assistant/android#898]
**Home Assistant Android version:**
2.3.3-full
**Android version:**
8.1.0
**Phone model:**
Moto G5 Plus
**Home Assistant version:**
0.114.0
**Last working Home Assistant release (if known):**

**Description of problem:**
I use the google default alarm app.  I have noticed an issue that may cause automations not to fire when using next_alarm sensor.  When the alarm app goes off and the alarm is ringing it immediately causes the next_alarm sensor to go to "unknown".  When the alarm is done ringing, or is snoozed the next_alarm goes to the time of the next alarm.

Here is where the race condition comes in.   As the next_alarm sensor is typically used in home assistant the template using the alarm data is evaluated at the 0 second mark of every minute.  Right now my phone and home assistant are both using highly accurate system clocks.   The alarm goes off at the exact time, home assistant looks at the template at the 0 second mark, triggers, the next_alarm sensor is updated to 'unknown' in home assistant at the 1 second after mark until I dismiss the alarm.  But if the android's clock is running a little fast, things go wrong.   The alarm goes off early at the 59 or 58 second mark, and updates the next_alarm sensor to 'unknown' before home assistant evaluates the template at the 0 second mark causing the template to never trigger.

Fixing this on the home assistant end would be tricky.  I would have to create another sensor that updates based on next_alarm on a delayed basis.   Changing home assistant to evaluate the template every second isn't a fix either as the race condition can still occur at a split second interval.  It would be much easier to fix this in the app.   I would propose something like this... When the next_alarm sensor changes value allow for a 30 second delay before sending the value to home assistant to allow for discrepancies between the system clocks and give time for home assistant to evaluate the template.   

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Delaying the sensors wont work because we listen to a broadcast receiver that sends out the next scheduled alarm.  I don't know how you are getting the `unknown` value because we definitely do not set that and the android API is designed to give us the time in milliseconds for the event. 

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt#L70

 If we do not get an event meaning they send `null` then we set the entity to `unavailable`.  

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt#L51

Not all alarms apps will function the same as the rest.  I suggest you look at the `package` attribute for the alarm and see where `unknown` is coming from because we are not setting that.  I do not see this value coming from the stock google alarm clock nor from sleep as android, one thing to keep in mind is that manufacturers have been known to alter stock app behavior.  You may need to adjust your automations because all we are doing is sending the date/time the moment we get it and causing any delay in this sensor will cause all sensors to be delayed.  We try to provide as much data as we can so you can adjust for your own use cases :)
