### ISSUE TITLE
New notifications should be silent by default

### ISSUE THREAD

**Issue by tycrek** [home-assistant/android#936]
**Home Assistant Android version:** 2.4.0-full

**Android version:** 10 (security Aug 1)

**Phone model:** LG G8X (LM-G850UM)

**Home Assistant version:** 0.114.4

**Last working Home Assistant release (if known):** N/A

**Description of problem:** random silent notifications with no information. Triggers Always On Display and various smart devices connected to phone via bluetooth. 

**Traceback (if applicable):**

```

```

**Screenshot of problem:** ![Capture+_2020-09-14-13-41-51.png](https://user-images.githubusercontent.com/29926144/93131382-3221fb00-f691-11ea-9122-a20294db05ec.png)

**Additional information:** Updating Sensors may be helpful, but the default notification channel should be silent. The "Home Assistant: A new notification" is not helpful and in my opinion is useless. I'm not sure whether this would count as a bug.

While I can definitely go into settings and change the notification channels, I feel notifications of this type should be silent *by default*.

**Comment by dshokouhi** [comment]
It seems that you are using a 3rd party app to read app notifications that is unable to handle low priority notifications properly.  The SensorWorker itself uses a low priority notification that does not make a sound and it is indeed silent when it does not have intervention from another app.

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/sensors/SensorWorker.kt#L68

It also has its own channel which by default it is set to silent because its low priority:
![image](https://user-images.githubusercontent.com/1634145/93132068-e455c480-f689-11ea-8874-4a6a23b31386.png)

Please check your 3rd party app for these settings to make sure it respects default behavior.

**Comment by tycrek** [comment]
@dshokouhi That's not what this app is doing; I've had issues with ghost notifications from Bluetooth devices in the past so this keeps a log of all notifications (the built in log on Android is disabled by LG). 

I'll double check a few things. These notifications aren't making noise or vibrating but they do show up in the notification bar and briefly flash the AOD.

**Comment by tycrek** [comment]
![Capture+_2020-09-14-14-09-29.png](https://user-images.githubusercontent.com/29926144/93133131-f50b3800-f693-11ea-8bb2-0f540a1af2a8.png)

These are the options I have. I think by "silent" I was thinking "Low Priority"

**Comment by dshokouhi** [comment]
> These notifications aren't making noise or vibrating but they do show up in the notification bar and briefly flash the AOD.

This is because they are a foreground service now, its much like the Google Phone and Calendar apps that have been updated and follow the same standard set by Google.  Given that it is set as a notification channel as a user you can set it to be minimized or turn off the channel completely.  Google's recommendation was to keep it at low priority which is what our app is doing.  More on the details of that can be found in the release blog post: https://www.home-assistant.io/blog/2020/09/12/android-240-release/#foreground-service-worker

**Comment by tycrek** [comment]
> Google's recommendation was to keep it at low priority which is what our app is doing

Per my screenshot, the app is actually using Medium, not Low. Perhaps Android Oreo uses different channels than Android Q?

**Comment by dshokouhi** [comment]
Its your phone manufacturer that has changed the name to `Medium` instead of `Low` but if you notice in your screenshot it says "no sound" which means it still follows the Low priority standard they just changed the name.   Channels behave the same from Android Oreo and on, the code looks only for that API level.  Remember not all manufacturers stick to Google's guidelines.

https://developer.android.com/reference/androidx/core/app/NotificationCompat#PRIORITY_LOW

Notice how "medium" is missing from the list lol

**Comment by tycrek** [comment]
*Sigh* LG does the weirdest things sometimes (they previously had video output through Type-C disabled in favour of wireless displays, then re-enabled video output in an update). Oh well, I'll set it to "LG Low" haha.

**Comment by dshokouhi** [comment]
Yea I get it lol Google still keeps video output disabled on the Type-C port and its been around since Nexus 6P and it drives me crazy.
